import Stripe from 'npm:stripe@^22'
import { createClient } from 'npm:@supabase/supabase-js@2'

const normalize=(value:string)=>value.trim().replace(/\/$/,'')
const allowedOrigins=()=>new Set([
  'https://ordered.food',
  'https://www.ordered.food',
  normalize(Deno.env.get('SITE_URL')??''),
  normalize(Deno.env.get('PLATFORM_ADMIN_URL')??''),
  ...(Deno.env.get('CORS_ALLOWED_ORIGINS')??'').split(',').map(normalize),
].filter(Boolean))
const cors=(req:Request)=>{
  const origin=normalize(req.headers.get('origin')??'')
  return {
    'Access-Control-Allow-Origin':origin&&allowedOrigins().has(origin)?origin:'null',
    'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods':'POST, OPTIONS',
    'Access-Control-Max-Age':'86400',
    'Cache-Control':'no-store',
    'Vary':'Origin',
  }
}
const out=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json'}})
const err=(e:unknown)=>e instanceof Error?e.message:'Subscription administration failed.'
const idOf=(v:unknown)=>!v?null:typeof v==='string'?v:typeof v==='object'&&v!==null&&'id'in v?String((v as{id:unknown}).id):null

Deno.serve(async req=>{
 const headers=cors(req)
 if(req.method==='OPTIONS')return new Response('ok',{headers})
 if(req.method!=='POST')return out(req,{error:'Method not allowed'},405)
 if(req.headers.get('origin')&&headers['Access-Control-Allow-Origin']==='null')return out(req,{error:'Origin is not allowed.'},403)
 const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),stripeKey=Deno.env.get('STRIPE_SECRET_KEY'),auth=req.headers.get('Authorization')
 if(!url||!anon||!service||!stripeKey||!auth)return out(req,{error:'Subscription administration is not configured'},500)
 let body:Record<string,unknown>;try{body=await req.json()}catch{return out(req,{error:'Invalid request'},400)}
 const action=typeof body.action==='string'?body.action:''
 const user=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}}),db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),stripe=new Stripe(stripeKey)
 const{data:identity,error:identityError}=await user.rpc('get_current_platform_admin')
 if(identityError||!identity||!Array.isArray(identity.permissions)||!identity.permissions.includes(action==='dashboard'?'finance:view':'finance:manage'))return out(req,{error:'Finance administrator access required'},403)
 try{
  if(action==='dashboard'){const{data,error}=await user.rpc('get_platform_subscription_management');if(error)throw error;return out(req,data)}
  const restaurantId=typeof body.restaurant_id==='string'?body.restaurant_id:''
  if(!/^[0-9a-f-]{36}$/i.test(restaurantId))return out(req,{error:'Valid restaurant is required'},400)
  const{data:sub,error:subError}=await db.from('restaurant_subscriptions').select('*,subscription_plans(*)').eq('restaurant_id',restaurantId).maybeSingle();if(subError)throw subError
  async function audit(type:string,details:Record<string,unknown>){await db.from('platform_admin_audit_log').insert({actor_user_id:identity.user_id,action:type,target_type:'restaurant',target_id:restaurantId,details})}
  async function ensurePrice(plan:Record<string,unknown>,interval:'monthly'|'annual',custom:number|null){const amount=custom??Number(interval==='annual'?plan.annual_price_pence:plan.monthly_price_pence);let priceId=custom===null?(interval==='annual'?plan.stripe_annual_price_id:plan.stripe_monthly_price_id) as string|null:null;if(priceId)return priceId;const product=await stripe.products.create({name:`ordered.food ${plan.name}`,metadata:{ordered_food_plan_id:String(plan.id),ordered_food_plan_code:String(plan.code),...(custom!==null?{restaurant_id:restaurantId}:{})}},{idempotencyKey:custom===null?`ordered-food-plan-product-${plan.id}`:`ordered-food-custom-product-${restaurantId}-${plan.id}`});const price=await stripe.prices.create({currency:String(plan.currency||'gbp'),unit_amount:amount,recurring:{interval:interval==='annual'?'year':'month'},product:product.id,metadata:{ordered_food_plan_id:String(plan.id),billing_interval:interval,...(custom!==null?{restaurant_id:restaurantId}:{})}},{idempotencyKey:`ordered-food-admin-price-${restaurantId}-${plan.id}-${interval}-${amount}`});if(custom===null)await db.from('subscription_plans').update(interval==='annual'?{stripe_annual_price_id:price.id}:{stripe_monthly_price_id:price.id}).eq('id',plan.id);return price.id}
  if(action==='assign_plan'){const planId=typeof body.plan_id==='string'?body.plan_id:'',interval=body.billing_interval==='annual'?'annual':'monthly',custom=Number.isInteger(body.custom_price_pence)?Number(body.custom_price_pence):null;const{data:plan,error}=await db.from('subscription_plans').select('*').eq('id',planId).eq('is_active',true).single();if(error||!plan)return out(req,{error:'Plan not found'},404);if(custom!==null&&!plan.custom_pricing)return out(req,{error:'Custom price is only allowed on custom-pricing plans'},400);if(sub?.stripe_subscription_id){const priceId=await ensurePrice(plan,interval,custom);const remote=await stripe.subscriptions.retrieve(sub.stripe_subscription_id),item=remote.items.data[0];if(!item)throw new Error('Stripe subscription item not found');await stripe.subscriptions.update(remote.id,{items:[{id:item.id,price:priceId}],metadata:{...remote.metadata,restaurant_id:restaurantId,plan_id:plan.id,billing_interval:interval},proration_behavior:'none'});await db.from('restaurant_subscriptions').update({stripe_price_id:priceId}).eq('id',sub.id)}const{data:assigned,error:assignError}=await user.rpc('admin_assign_restaurant_plan',{p_restaurant_id:restaurantId,p_plan_id:planId,p_billing_interval:interval,p_custom_price_pence:custom});if(assignError)throw assignError;return out(req,{subscription_id:assigned})}
  if(!sub)return out(req,{error:'Subscription not found'},404)
  if(action==='credit'){const amount=Number(body.amount_pence),reason=typeof body.reason==='string'?body.reason.trim().slice(0,350):'Platform billing credit';if(!Number.isInteger(amount)||amount<=0)return out(req,{error:'Credit amount must be a positive integer'},400);if(!sub.stripe_customer_id)return out(req,{error:'Restaurant has no Stripe customer'},409);const{data:creditId,error:createError}=await user.rpc('admin_create_billing_credit',{p_restaurant_id:restaurantId,p_amount_pence:amount,p_reason:reason});if(createError)throw createError;try{const tx=await stripe.customers.createBalanceTransaction(sub.stripe_customer_id,{amount:-amount,currency:'gbp',description:reason,metadata:{restaurant_id:restaurantId,credit_id:creditId}},{idempotencyKey:`billing-credit-${creditId}`});await db.from('restaurant_billing_credits').update({status:'applied',stripe_customer_balance_transaction_id:tx.id,applied_at:new Date().toISOString()}).eq('id',creditId);await audit('subscription.credit',{credit_id:creditId,amount_pence:amount,stripe_transaction_id:tx.id});return out(req,{credit_id:creditId,stripe_transaction_id:tx.id})}catch(caught){await db.from('restaurant_billing_credits').update({status:'failed',metadata:{error:err(caught)}}).eq('id',creditId);throw caught}}
  if(action==='refund'){const invoiceId=typeof body.invoice_id==='string'?body.invoice_id:'',amount=body.amount_pence==null?null:Number(body.amount_pence);const{data:invoice,error}=await db.from('restaurant_subscription_invoices').select('*').eq('restaurant_id',restaurantId).eq('stripe_invoice_id',invoiceId).single();if(error||!invoice)return out(req,{error:'Invoice not found'},404);const refundable=Math.max(0,invoice.amount_paid_pence-invoice.refunded_pence),refundAmount=amount===null?refundable:amount;if(!Number.isInteger(refundAmount)||refundAmount<=0||refundAmount>refundable)return out(req,{error:'Invalid refund amount'},400);const remote=await stripe.invoices.retrieve(invoice.stripe_invoice_id,{expand:['payment_intent','charge']} as never) as Stripe.Invoice&{payment_intent?:unknown;charge?:unknown};const paymentIntent=idOf(remote.payment_intent),charge=idOf(remote.charge);if(!paymentIntent&&!charge)return out(req,{error:'No refundable Stripe payment was found on this invoice'},409);const refund=await stripe.refunds.create({...(paymentIntent?{payment_intent:paymentIntent}:{charge:charge!}),amount:refundAmount,metadata:{restaurant_id:restaurantId,subscription_invoice_id:invoice.id}},{idempotencyKey:`subscription-refund-${invoice.id}-${invoice.refunded_pence}-${refundAmount}`});await db.from('restaurant_subscription_invoices').update({refunded_pence:invoice.refunded_pence+refundAmount,updated_at:new Date().toISOString()}).eq('id',invoice.id);await db.from('restaurant_subscription_events').insert({restaurant_id:restaurantId,subscription_id:sub.id,event_type:'subscription_refund',details:{invoice_id:invoice.id,stripe_refund_id:refund.id,amount_pence:refundAmount}});await audit('subscription.refund',{invoice_id:invoice.id,stripe_refund_id:refund.id,amount_pence:refundAmount});return out(req,{refund_id:refund.id,amount_pence:refundAmount})}
  if(action==='extend_trial'){const days=Number(body.days),reason=typeof body.reason==='string'?body.reason.slice(0,500):'Admin extension';if(!Number.isInteger(days)||days<1||days>90)return out(req,{error:'Trial extension must be 1 to 90 days'},400);if(sub.stripe_subscription_id&&sub.status==='trialing'){const next=Math.floor((Math.max(new Date(sub.trial_ends_at||Date.now()).getTime(),Date.now())+days*86400000)/1000);await stripe.subscriptions.update(sub.stripe_subscription_id,{trial_end:next,proration_behavior:'none'})}const{data,error}=await user.rpc('admin_extend_subscription_trial',{p_restaurant_id:restaurantId,p_days:days,p_reason:reason});if(error)throw error;await audit('subscription.trial_extend',{days,reason,trial_ends_at:data});return out(req,{trial_ends_at:data})}
  if(action==='comp'){const until=typeof body.until==='string'?new Date(body.until):null,reason=typeof body.reason==='string'?body.reason.slice(0,500):'Complimentary period';if(!until||Number.isNaN(until.getTime())||until.getTime()<=Date.now())return out(req,{error:'A future comp end date is required'},400);if(sub.stripe_subscription_id)await stripe.subscriptions.update(sub.stripe_subscription_id,{pause_collection:{behavior:'void',resumes_at:Math.floor(until.getTime()/1000)}});const{error}=await user.rpc('admin_comp_restaurant_subscription',{p_restaurant_id:restaurantId,p_until:until.toISOString(),p_reason:reason});if(error)throw error;await audit('subscription.comp',{until:until.toISOString(),reason});return out(req,{comped_until:until.toISOString()})}
  return out(req,{error:'Unsupported action'},400)
 }catch(caught){console.error('Platform subscription admin failed',caught);return out(req,{error:err(caught)},500)}
})
