import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney } from '../types'
import './AIIntelligence.css'

type Benchmark={restaurant_id:string;name:string;restaurant_health_score:number;growth_score:number;customer_health_score:number;marketing_score:number;operations_score:number;weekly_revenue_forecast_pence:number|null;high_churn_customers:number}
type Data={summary:{restaurants_with_ai:number;customers_scored:number;high_churn_customers:number;active_growth_opportunities:number;active_risk_alerts:number;average_health_score:number};platform_forecasts:{weekly_revenue_pence:number;monthly_revenue_pence:number;weekly_delivery_orders:number;weekly_collection_orders:number};benchmarking:Benchmark[];marketing:{restaurants_adopted?:number;campaign_volume?:number;revenue_generated_pence?:number;retention_percent?:number;customer_growth?:number};adoption:{marketing_restaurants:number;loyalty_restaurants:number;vip_restaurants:number;challenge_restaurants:number};fraud_intelligence:{restaurants_with_fraud_insights:number};generated_at:string;period_days:number;methodology:{version:string;provider:string;explainable:boolean}}
type ExtendedForecasts={weekly_customer_growth:number;monthly_customer_growth:number;weekly_campaign_revenue_pence:number;monthly_campaign_revenue_pence:number;weekly_repeat_customer_percent:number;monthly_repeat_customer_percent:number;average_engagement_score:number;average_return_probability:number;generated_at:string}

export default function AIIntelligence(){
 const [days,setDays]=useState(90),[data,setData]=useState<Data|null>(null),[extended,setExtended]=useState<ExtendedForecasts|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [main,forecasts]=await Promise.all([supabase.rpc('get_platform_ai_dashboard',{p_days:days}),supabase.rpc('get_platform_ai_intelligence_forecasts')]);const failure=main.error||forecasts.error;if(failure)setError(failure.message);else{setData(main.data as Data);setExtended(forecasts.data as ExtendedForecasts)}setLoading(false)},[days])
 useEffect(()=>{void load()},[load])
 const benchmarks=useMemo(()=>[...(data?.benchmarking??[])].sort((a,b)=>Number(b.restaurant_health_score||0)-Number(a.restaurant_health_score||0)),[data?.benchmarking])
 const benchmarkLeader=benchmarks[0]
 const attentionCount=benchmarks.filter(r=>Number(r.restaurant_health_score||0)<60).length
 return <div className="admin-page analytics-page"><header className="page-heading"><div><span className="admin-kicker">Platform AI intelligence</span><h1>Forecast growth, risk and restaurant health.</h1><p>Explainable platform-wide intelligence built from restaurant performance, customer engagement, marketing and fraud signals.</p></div><div className="analytics-actions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select><button className="secondary-button" type="button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></div></header>
 {error&&<div className="admin-alert error" role="alert">{error}</div>}
 <section className="metric-grid"><Metric label="Restaurants with AI" value={loading?'—':String(data?.summary.restaurants_with_ai??0)} detail={`${data?.summary.average_health_score??0} average health`} tone="blue"/><Metric label="Weekly revenue forecast" value={loading?'—':formatMoney(data?.platform_forecasts.weekly_revenue_pence)} detail={`Monthly ${formatMoney(data?.platform_forecasts.monthly_revenue_pence)}`} tone="green"/><Metric label="High churn customers" value={loading?'—':String(data?.summary.high_churn_customers??0)} detail={`${data?.summary.active_risk_alerts??0} active risk signals`} tone="red"/><Metric label="Engagement forecast" value={loading?'—':`${Math.round(extended?.average_engagement_score??0)}/100`} detail={`${Math.round(extended?.average_return_probability??0)}% average return probability`} tone="amber"/></section>
 <div className="overview-grid analytics-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Demand forecast</h2><p>Current aggregate restaurant forecasts.</p></div></div><div className="analytics-table"><Row label="Weekly delivery orders" value={String(Math.round(data?.platform_forecasts.weekly_delivery_orders??0))}/><Row label="Weekly collection orders" value={String(Math.round(data?.platform_forecasts.weekly_collection_orders??0))}/><Row label="Weekly customer growth" value={String(Math.round(extended?.weekly_customer_growth??0))}/><Row label="Monthly customer growth" value={String(Math.round(extended?.monthly_customer_growth??0))}/><Row label="Weekly repeat-customer forecast" value={`${Number(extended?.weekly_repeat_customer_percent??0).toFixed(1)}%`}/></div></section><section className="admin-panel"><div className="panel-heading"><div><h2>Marketing & engagement forecast</h2><p>Attributed campaign revenue and customer-engagement outlook.</p></div></div><div className="analytics-table"><Row label="Weekly campaign revenue" value={formatMoney(extended?.weekly_campaign_revenue_pence)}/><Row label="Monthly campaign revenue" value={formatMoney(extended?.monthly_campaign_revenue_pence)}/><Row label="Average engagement score" value={`${Math.round(extended?.average_engagement_score??0)}/100`}/><Row label="Average return probability" value={`${Math.round(extended?.average_return_probability??0)}%`}/><Row label="Current retention" value={`${data?.marketing?.retention_percent??0}%`}/></div></section></div>
 <div className="overview-grid analytics-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Current platform signals</h2><p>Observed marketing and customer movement in the selected analysis window.</p></div></div><div className="analytics-table"><Row label="Marketing-attributed revenue" value={formatMoney(data?.marketing?.revenue_generated_pence)}/><Row label="Customer growth" value={String(data?.marketing?.customer_growth??0)}/><Row label="Growth opportunities" value={String(data?.summary.active_growth_opportunities??0)}/><Row label="Customers scored" value={String(data?.summary.customers_scored??0)}/><Row label="Risk alerts" value={String(data?.summary.active_risk_alerts??0)}/></div></section><section className="admin-panel"><div className="panel-heading"><div><h2>Feature adoption</h2><p>Restaurants actively represented in engagement systems.</p></div></div><div className="analytics-table"><Row label="Marketing" value={String(data?.adoption.marketing_restaurants??0)}/><Row label="Loyalty" value={String(data?.adoption.loyalty_restaurants??0)}/><Row label="VIP" value={String(data?.adoption.vip_restaurants??0)}/><Row label="Challenges" value={String(data?.adoption.challenge_restaurants??0)}/><Row label="Fraud insights" value={String(data?.fraud_intelligence.restaurants_with_fraud_insights??0)}/></div></section></div>
 <section className="admin-panel benchmark-panel"><div className="panel-heading benchmark-heading"><div><h2>Restaurant benchmarking</h2><p>Compare restaurant health across growth, customers, marketing and operations. Forecasts are decision-support estimates, not guarantees.</p></div><div className="benchmark-legend" aria-label="Benchmark score guide"><span className="strong">80–100 Strong</span><span className="watch">60–79 Watch</span><span className="risk">Below 60 Attention</span></div></div>
 {loading?<div className="benchmark-loading"><span/><span/><span/></div>:benchmarks.length===0?<div className="panel-empty"><strong>No benchmark data yet</strong><span>Restaurant comparisons will appear after the AI scoring cycle has run.</span></div>:<><div className="benchmark-summary"><article><small>Restaurants compared</small><strong>{benchmarks.length}</strong><span>Latest scoring cycle</span></article><article><small>Health leader</small><strong>{benchmarkLeader?.name??'—'}</strong><span>{benchmarkLeader?`${roundedScore(benchmarkLeader.restaurant_health_score)}/100 overall health`:'No score available'}</span></article><article className={attentionCount>0?'attention':''}><small>Needs attention</small><strong>{attentionCount}</strong><span>Below 60 overall health</span></article></div><div className="benchmark-list">{benchmarks.map((restaurant,index)=><BenchmarkCard key={restaurant.restaurant_id} restaurant={restaurant} rank={index+1}/>)}</div></>}
 </section>
 <section className="admin-panel"><div className="panel-heading"><div><h2>Methodology & traceability</h2><p>Provider {data?.methodology.provider||'internal'} · version {data?.methodology.version||'5.9.1'} · explainable {data?.methodology.explainable?'yes':'no'}. The provider/model fields are stored with every run so a future OpenAI, Anthropic or other adapter can be swapped without changing the reporting contract.</p></div></div></section></div>
}

function BenchmarkCard({restaurant,rank}:{restaurant:Benchmark;rank:number}){
 const health=roundedScore(restaurant.restaurant_health_score)
 const tone=scoreTone(health)
 return <article className={`benchmark-card ${tone}`}><header className="benchmark-card-header"><div className="benchmark-identity"><span className="benchmark-rank">#{rank}</span><div><strong>{restaurant.name}</strong><span className={`benchmark-status ${tone}`}>{scoreLabel(health)}</span></div></div><div className="benchmark-commercial"><span><small>Weekly forecast</small><strong>{formatMoney(restaurant.weekly_revenue_forecast_pence??0)}</strong></span><span className={restaurant.high_churn_customers>0?'risk':''}><small>High churn</small><strong>{restaurant.high_churn_customers}</strong></span></div></header><div className="benchmark-score-grid"><ScoreCell label="Overall health" value={restaurant.restaurant_health_score} featured/><ScoreCell label="Growth" value={restaurant.growth_score}/><ScoreCell label="Customer" value={restaurant.customer_health_score}/><ScoreCell label="Marketing" value={restaurant.marketing_score}/><ScoreCell label="Operations" value={restaurant.operations_score}/></div></article>
}

function ScoreCell({label,value,featured=false}:{label:string;value:number;featured?:boolean}){
 const scoreValue=roundedScore(value)
 const tone=scoreTone(scoreValue)
 return <div className={`benchmark-score ${featured?'featured':''}`}><div><span>{label}</span><strong>{scoreValue}<small>/100</small></strong></div><div className="benchmark-score-track" aria-label={`${label}: ${scoreValue} out of 100`}><i className={tone} style={{width:`${Math.max(0,Math.min(100,scoreValue))}%`}}/></div></div>
}

function Metric({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}){return <article className="metric"><span className={`metric-dot ${tone}`}/><small>{label}</small><strong>{value}</strong><p>{detail}</p></article>}
function Row({label,value}:{label:string;value:string}){return <article><span>•</span><div><strong>{label}</strong></div><strong>{value}</strong></article>}
function roundedScore(value:number){return Math.round(Number(value||0))}
function scoreTone(value:number){return value>=80?'strong':value>=60?'watch':'risk'}
function scoreLabel(value:number){return value>=80?'Strong':value>=60?'Watch':'Needs attention'}
