import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { formatDate, hasAdminPermission } from '../types'

type Rule={id:string;rule_key:string;name:string;description:string;is_enabled:boolean;severity:string;threshold:number;window_minutes:number;cooldown_minutes:number;email_recipients:string[];updated_at:string;updated_by_name:string}
type AlertEvent={id:string;rule_key:string;rule_name:string;title:string;message:string;severity:string;metric_value:number|null;context:Record<string,unknown>;status:string;created_at:string;acknowledged_at:string|null;acknowledged_by_name:string|null;resolved_at:string|null;resolved_by_name:string|null}
type Snapshot={rules:Rule[];events:AlertEvent[];summary:{open:number;urgent:number;acknowledged:number;enabled_rules:number}}
type Draft={is_enabled:boolean;severity:string;threshold:string;window_minutes:string;cooldown_minutes:string;email_recipients:string;reason:string}

export default function Alerts(){
 const {admin}=useAdmin();const canManage=hasAdminPermission(admin,'settings:manage')
 const [data,setData]=useState<Snapshot|null>(null),[selected,setSelected]=useState<Rule|null>(null),[draft,setDraft]=useState<Draft|null>(null)
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:r,error:e}=await supabase.rpc('get_platform_alert_centre');if(e)setError(e.message);else{const next=r as Snapshot;setData(next);setSelected(current=>next.rules.find(x=>x.id===current?.id)??next.rules[0]??null)}setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(selected)setDraft({is_enabled:selected.is_enabled,severity:selected.severity,threshold:String(selected.threshold),window_minutes:String(selected.window_minutes),cooldown_minutes:String(selected.cooldown_minutes),email_recipients:selected.email_recipients.join(', '),reason:''});else setDraft(null)},[selected])
 async function save(event:FormEvent){event.preventDefault();if(!selected||!draft)return;setSaving(true);setError('');setSuccess('');const recipients=draft.email_recipients.split(',').map(x=>x.trim()).filter(Boolean);const {error:e}=await supabase.rpc('update_platform_alert_rule',{p_rule_id:selected.id,p_payload:{is_enabled:draft.is_enabled,severity:draft.severity,threshold:Number(draft.threshold),window_minutes:Number(draft.window_minutes),cooldown_minutes:Number(draft.cooldown_minutes),email_recipients:recipients},p_reason:draft.reason});setSaving(false);if(e)return setError(e.message);setSuccess('Alert rule updated.');await load()}
 async function manage(id:string,action:string){const reason=action==='acknowledge'?null:window.prompt(`Reason to ${action} this alert:`);if(action!=='acknowledge'&&!reason)return;setSaving(true);setError('');const {error:e}=await supabase.rpc('manage_platform_alert_event',{p_event_id:id,p_action:action,p_reason:reason});setSaving(false);if(e)return setError(e.message);setSuccess(`Alert ${action}d.`);await load()}
 return <div className="admin-page alerts-page"><header className="page-heading"><div><span className="admin-kicker">Operational notifications</span><h1>Alert centre</h1><p>Configure alert thresholds and manage the platform’s operational notification inbox.</p></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></header>
 {error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="risk-metrics"><article><small>Open alerts</small><strong>{data?.summary.open??0}</strong></article><article><small>Urgent</small><strong>{data?.summary.urgent??0}</strong></article><article><small>Acknowledged</small><strong>{data?.summary.acknowledged??0}</strong></article><article><small>Enabled rules</small><strong>{data?.summary.enabled_rules??0}</strong></article></section>
 <div className="alerts-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Alert rules</h2><p>{loading?'Loading…':`${data?.rules.length??0} configurable rules`}</p></div></div><div className="alert-rule-list">{data?.rules.map(rule=><button key={rule.id} className={selected?.id===rule.id?'active':''} onClick={()=>{setSelected(rule);setSuccess('')}}><span><strong>{rule.name}</strong><small>{rule.description}</small></span><span><i className={`risk-severity ${rule.severity}`}>{rule.severity}</i><small>{rule.is_enabled?'Enabled':'Disabled'}</small></span></button>)}</div></section>
 <section className="admin-panel alert-rule-editor">{!draft||!selected?<div className="panel-empty">Select an alert rule.</div>:<form onSubmit={save}><div className="panel-heading"><div><h2>{selected.name}</h2><p>Last updated by {selected.updated_by_name} · {formatDate(selected.updated_at)}</p></div></div><div className="configuration-toggle-list"><label className="configuration-toggle"><input type="checkbox" checked={draft.is_enabled} disabled={!canManage||saving} onChange={e=>setDraft({...draft,is_enabled:e.target.checked})}/><span className="configuration-switch"><i/></span><span><strong>Rule enabled</strong><small>Allow this condition to generate administrator alerts.</small></span></label></div><div className="admin-profile-grid"><label>Severity<select value={draft.severity} disabled={!canManage||saving} onChange={e=>setDraft({...draft,severity:e.target.value})}><option>normal</option><option>high</option><option>urgent</option></select></label><label>Threshold<input type="number" min="0" value={draft.threshold} disabled={!canManage||saving} onChange={e=>setDraft({...draft,threshold:e.target.value})}/></label><label>Window (minutes)<input type="number" min="5" max="10080" value={draft.window_minutes} disabled={!canManage||saving} onChange={e=>setDraft({...draft,window_minutes:e.target.value})}/></label><label>Cooldown (minutes)<input type="number" min="5" max="10080" value={draft.cooldown_minutes} disabled={!canManage||saving} onChange={e=>setDraft({...draft,cooldown_minutes:e.target.value})}/></label><label className="wide">Email recipients<input value={draft.email_recipients} disabled={!canManage||saving} onChange={e=>setDraft({...draft,email_recipients:e.target.value})} placeholder="ops@ordered.food, support@ordered.food"/><small>Comma-separated. Empty means inbox only.</small></label>{canManage&&<label className="wide">Reason for change<textarea required minLength={5} rows={3} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>}</div>{canManage&&<button className="admin-primary-button" disabled={saving}>{saving?'Saving…':'Save rule'}</button>}</form>}</section></div>
 <section className="admin-panel"><div className="panel-heading"><div><h2>Alert history</h2><p>Open and recently handled alerts from the last 30 days.</p></div></div>{!data?.events.length?<div className="panel-empty"><strong>No alerts generated</strong><span>Rules are configured and ready.</span></div>:<div className="risk-list">{data.events.map(item=><article key={item.id}><span className={`risk-severity ${item.severity}`}>{item.severity}</span><div><strong>{item.title}</strong><p>{item.message}</p><small>{item.rule_name} · {formatDate(item.created_at)}</small></div><span className={`case-status ${item.status}`}>{item.status}</span>{canManage&&<div>{item.status==='open'&&<button className="secondary-button" onClick={()=>void manage(item.id,'acknowledge')}>Acknowledge</button>}{item.status!=='resolved'&&<button className="admin-primary-button" onClick={()=>void manage(item.id,'resolve')}>Resolve</button>}{item.status==='resolved'&&<button className="secondary-button" onClick={()=>void manage(item.id,'reopen')}>Reopen</button>}</div>}</article>)}</div>}</section></div>
}
