import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { formatMoney } from '../types'

type Daily={day:string;paid_orders:number;failed_payments:number;gross_pence:number;refunded_pence:number}
type RestaurantPerf={id:string;name:string;order_count:number;gross_pence:number;avg_accept_minutes:number|null;avg_fulfilment_minutes:number|null;cancelled_orders:number}
type Analytics={range:{days:number;from:string;to:string};summary:{paid_orders:number;failed_payments:number;gross_pence:number;refunded_pence:number;average_order_value_pence:number;payment_failure_rate:number;online_restaurants:number;offline_active_restaurants:number};daily:Daily[];top_restaurants:RestaurantPerf[];slow_restaurants:RestaurantPerf[];alerts:{orders_waiting_over_10_minutes:number;failed_payments_last_24h:number;failed_print_jobs:number;overdue_support_cases:number;pending_restaurant_applications:number;failed_payouts:number}}

export default function Analytics(){
 const [days,setDays]=useState(30),[data,setData]=useState<Analytics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:r,error:e}=await supabase.rpc('get_platform_analytics',{p_days:days});if(e)setError(e.message);else setData(r as Analytics);setLoading(false)},[days])
 useEffect(()=>{void load()},[load])
 const maxGross=useMemo(()=>Math.max(...(data?.daily.map(x=>x.gross_pence)??[1]),1),[data])
 return <div className="admin-page analytics-page"><header className="page-heading"><div><span className="admin-kicker">Platform intelligence</span><h1>Analytics & monitoring</h1><p>Track demand, revenue, payment health and operational risk across ordered.food.</p></div><div className="analytics-actions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option></select><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></div></header>
 {error&&<div className="admin-alert error" role="alert">{error}</div>}
 <section className="metric-grid"><Metric label="Paid orders" value={loading?'—':String(data?.summary.paid_orders??0)} detail={`${days}-day period`} tone="blue"/><Metric label="Gross order value" value={loading?'—':formatMoney(data?.summary.gross_pence)} detail={`AOV ${formatMoney(data?.summary.average_order_value_pence)}`} tone="green"/><Metric label="Payment failure rate" value={loading?'—':`${data?.summary.payment_failure_rate??0}%`} detail={`${data?.summary.failed_payments??0} failed attempts`} tone="red"/><Metric label="Restaurants online" value={loading?'—':String(data?.summary.online_restaurants??0)} detail={`${data?.summary.offline_active_restaurants??0} active but offline`} tone="amber"/></section>
 <section className="admin-panel analytics-trend"><div className="panel-heading"><div><h2>Daily gross sales</h2><p>{data?.range.from} to {data?.range.to}</p></div></div><div className="analytics-bars">{data?.daily.map(d=><article key={d.day} title={`${d.day}: ${formatMoney(d.gross_pence)}`}><div style={{height:`${Math.max(4,(d.gross_pence/maxGross)*100)}%`}}/><small>{new Date(`${d.day}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</small></article>)}</div></section>
 <div className="overview-grid analytics-grid"><section className="admin-panel"><div className="panel-heading"><div><h2>Operational alerts</h2><p>Issues requiring attention now.</p></div></div><Alert to="/orders?status=placed" label="Orders waiting over 10 minutes" value={data?.alerts.orders_waiting_over_10_minutes??0}/><Alert to="/payments?status=failed" label="Failed payments in 24 hours" value={data?.alerts.failed_payments_last_24h??0}/><Alert to="/order-recovery" label="Failed print jobs" value={data?.alerts.failed_print_jobs??0}/><Alert to="/support-sla?queue=overdue" label="Overdue support cases" value={data?.alerts.overdue_support_cases??0}/><Alert to="/restaurants?status=pending_approval" label="Applications pending" value={data?.alerts.pending_restaurant_applications??0}/><Alert to="/payouts?status=failed" label="Failed payouts" value={data?.alerts.failed_payouts??0}/></section>
 <section className="admin-panel"><div className="panel-heading"><div><h2>Top restaurants</h2><p>Ranked by gross order value.</p></div></div><div className="analytics-table">{data?.top_restaurants.map((r,i)=><article key={r.id}><span>{i+1}</span><div><strong>{r.name}</strong><small>{r.order_count} orders</small></div><strong>{formatMoney(r.gross_pence)}</strong></article>)}</div></section></div>
 <section className="admin-panel"><div className="panel-heading"><div><h2>Restaurant response performance</h2><p>Highest average acceptance times appear first.</p></div></div><div className="financial-table-scroll"><table><thead><tr><th>Restaurant</th><th>Orders</th><th>Average accept</th><th>Average fulfilment</th><th>Cancelled/rejected</th><th>Gross</th></tr></thead><tbody>{data?.slow_restaurants.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.order_count}</td><td>{minutes(r.avg_accept_minutes)}</td><td>{minutes(r.avg_fulfilment_minutes)}</td><td>{r.cancelled_orders}</td><td>{formatMoney(r.gross_pence)}</td></tr>)}</tbody></table></div></section></div>
}
function Metric({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}){return <article className="metric"><span className={`metric-dot ${tone}`}/><small>{label}</small><strong>{value}</strong><p>{detail}</p></article>}
function Alert({to,label,value}:{to:string;label:string;value:number}){return <Link className={`attention-row ${value>0?'has-alert':''}`} to={to}><span className="attention-icon red">!</span><span><strong>{value} {label.toLowerCase()}</strong><small>{value>0?'Open the related control centre.':'No current issues.'}</small></span><span>›</span></Link>}
function minutes(value:number|null){return value===null?'No data':`${value} min`}
