import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney, hasAdminPermission } from '../types'
import { useAdmin } from '../components/AdminLayout'

type Summary={restaurant_adoption:number;active_restaurants:number;participants:number;completions:number;completion_percent:number;reward_cost_pence:number;revenue_generated_pence:number;open_fraud_flags:number}
type TypeRow={condition_type:string;challenges:number;completions:number}
type RestaurantRow={restaurant_id:string;restaurant_name:string;challenges:number;participants:number;completions:number;reward_cost_pence:number;revenue_generated_pence:number}
type FraudFlag={id:string;challenge_id:string|null;restaurant_id:string;restaurant_name:string;customer_user_id:string|null;order_id:string|null;flag_type:string;severity:string;status:string;details:Record<string,unknown>;created_at:string}
type Dashboard={summary:Summary;challenge_types:TypeRow[];restaurants:RestaurantRow[];fraud_flags:FraudFlag[]}
const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())
const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'})
export default function Challenges(){const{admin}=useAdmin();const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const canManage=hasAdminPermission(admin,'restaurants:manage')
 async function load(){setLoading(true);setError('');const{data,error:rpcError}=await supabase.rpc('get_platform_challenge_dashboard');if(rpcError)setError(rpcError.message);else setDash(data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
 async function review(flag:FraudFlag,status:'reviewed'|'dismissed'|'confirmed'){const note=window.prompt(`Optional note for ${status}:`,'');setBusy(flag.id);const{error:e}=await supabase.rpc('platform_review_challenge_fraud_flag',{p_flag_id:flag.id,p_status:status,p_note:note||''});if(e)setError(e.message);else await load();setBusy('')}
 async function disableChallenge(challengeId:string){const reason=window.prompt('Reason for disabling this challenge?','Challenge abuse investigation');if(!reason)return;setBusy(challengeId);const{error:e}=await supabase.rpc('platform_set_challenge_disabled',{p_challenge_id:challengeId,p_disabled:true,p_reason:reason});if(e)setError(e.message);else await load();setBusy('')}
 if(loading)return <section className="admin-page"><p>Loading challenge intelligence…</p></section>;const s=dash?.summary||{restaurant_adoption:0,active_restaurants:0,participants:0,completions:0,completion_percent:0,reward_cost_pence:0,revenue_generated_pence:0,open_fraud_flags:0};const roi=s.reward_cost_pence?((s.revenue_generated_pence-s.reward_cost_pence)/s.reward_cost_pence)*100:s.revenue_generated_pence?100:0
 return <section className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Gamification & retention</span><h1>Challenges</h1><p>Platform adoption, engagement, reward economics, successful mission types and fraud signals.</p></div><button type="button" className="admin-button" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="admin-alert admin-alert-danger">{error}</div>}
 <div className="admin-stat-grid"><article><span>Restaurant adoption</span><strong>{s.restaurant_adoption}</strong><small>{s.active_restaurants} currently active</small></article><article><span>Participants</span><strong>{s.participants}</strong><small>Unique challenge customers</small></article><article><span>Completions</span><strong>{s.completions}</strong><small>{Number(s.completion_percent).toFixed(1)}% completion</small></article><article><span>Revenue generated</span><strong>{formatMoney(s.revenue_generated_pence)}</strong><small>Tracked post-reward revenue</small></article><article><span>Reward cost</span><strong>{formatMoney(s.reward_cost_pence)}</strong><small>Challenge campaign cost</small></article><article><span>ROI</span><strong>{roi.toFixed(1)}%</strong><small>Revenue versus reward cost</small></article><article><span>Open fraud flags</span><strong>{s.open_fraud_flags}</strong><small>Needs investigation</small></article></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Popularity</span><h2>Most successful challenge types</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Challenge condition</th><th>Configured</th><th>Completions</th><th>Completion signal</th></tr></thead><tbody>{dash?.challenge_types.length?dash.challenge_types.map(row=><tr key={row.condition_type}><td><strong>{text(row.condition_type)}</strong></td><td>{row.challenges}</td><td>{row.completions}</td><td>{row.challenges?`${(row.completions/row.challenges).toFixed(1)} per campaign`:'—'}</td></tr>):<tr><td colSpan={4}>No challenge campaigns yet.</td></tr>}</tbody></table></div></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Restaurant comparison</span><h2>Challenge performance</h2></div><small>Compare adoption, engagement, revenue and reward cost.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Challenges</th><th>Participants</th><th>Completions</th><th>Revenue</th><th>Reward cost</th><th>ROI</th></tr></thead><tbody>{dash?.restaurants.length?dash.restaurants.map(row=>{const rowRoi=row.reward_cost_pence?((row.revenue_generated_pence-row.reward_cost_pence)/row.reward_cost_pence)*100:row.revenue_generated_pence?100:0;return <tr key={row.restaurant_id}><td><strong>{row.restaurant_name}</strong></td><td>{row.challenges}</td><td>{row.participants}</td><td>{row.completions}</td><td>{formatMoney(row.revenue_generated_pence)}</td><td>{formatMoney(row.reward_cost_pence)}</td><td>{rowRoi.toFixed(1)}%</td></tr>}):<tr><td colSpan={7}>No restaurants have configured challenges.</td></tr>}</tbody></table></div></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Fraud monitoring</span><h2>Challenge risk signals</h2></div><small>Rewards are server-side and idempotent; these signals surface abnormal behaviour for review.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Signal</th><th>Severity</th><th>Status</th><th>Detected</th><th>Details</th><th>Review</th></tr></thead><tbody>{dash?.fraud_flags.length?dash.fraud_flags.map(flag=><tr key={flag.id}><td>{flag.restaurant_name}</td><td><strong>{text(flag.flag_type)}</strong></td><td>{text(flag.severity)}</td><td>{text(flag.status)}</td><td>{date.format(new Date(flag.created_at))}</td><td><small>{Object.entries(flag.details||{}).slice(0,3).map(([k,v])=>`${text(k)}: ${String(v)}`).join(' · ')||'—'}</small></td><td>{flag.status==='open'&&canManage?<div className="admin-inline-actions"><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'reviewed')}>Review</button><button type="button" className="admin-button admin-button-small admin-button-secondary" disabled={busy===flag.id} onClick={()=>void review(flag,'dismissed')}>Dismiss</button><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'confirmed')}>Confirm</button>{flag.challenge_id&&<button type="button" className="admin-button admin-button-small" disabled={busy===flag.challenge_id} onClick={()=>void disableChallenge(flag.challenge_id!)}>Disable challenge</button>}</div>:<small>{flag.status==='open'?'View only':'Reviewed'}</small>}</td></tr>):<tr><td colSpan={7}>No challenge fraud signals.</td></tr>}</tbody></table></div></div></section>}
