import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney } from '../types'

type Row = { restaurant_id:string; restaurant_name:string; order_count:number; captured_pence:number; gross_sales_pence:number; refunded_pence:number; service_fees_pence:number; commission_pence:number; commission_vat_pence:number; net_revenue_pence:number; payout_status:string }
type Report = { rows:Row[]; summary:Omit<Row,'restaurant_id'|'restaurant_name'|'payout_status'>; range:{ from:string; to:string }; restaurants:Array<{id:string;name:string}> }
const iso=(date:Date)=>date.toISOString().slice(0,10)
const csvCell=(value:string|number)=>`"${String(value).replaceAll('"','""')}"`

export default function Financials(){
  const today=useMemo(()=>new Date(),[]); const initialFrom=useMemo(()=>{const d=new Date(today);d.setDate(d.getDate()-29);return iso(d)},[today])
  const [from,setFrom]=useState(initialFrom); const [to,setTo]=useState(iso(today)); const [restaurant,setRestaurant]=useState('')
  const [data,setData]=useState<Report|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');const {data:result,error:e}=await supabase.rpc('get_restaurant_financial_overview',{p_from:from,p_to:to,p_restaurant_id:restaurant||null});if(e)setError(e.message);else setData(result as Report);setLoading(false)},[from,to,restaurant])
  useEffect(()=>{void load()},[load])
  function download(){if(!data?.rows.length)return;const headers=['Restaurant','Orders','Captured','Gross sales','Refunds','Service fees','Commission','Commission VAT','Net revenue','Payout status'];const rows=data.rows.map(r=>[r.restaurant_name,r.order_count,r.captured_pence/100,r.gross_sales_pence/100,r.refunded_pence/100,r.service_fees_pence/100,r.commission_pence/100,r.commission_vat_pence/100,r.net_revenue_pence/100,r.payout_status]);const csv=[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`restaurant-financials-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url)}
  const s=data?.summary
  return <div className="admin-page financials-page"><header className="page-heading"><div><span className="admin-kicker">Restaurant economics</span><h1>Financial overview</h1><p>Reconcile captured sales, refunds, platform deductions and restaurant net revenue from immutable order snapshots.</p></div><button className="secondary-button" onClick={download} disabled={!data?.rows.length}>↓ Export CSV</button></header>
  {error&&<div className="admin-alert error" role="alert">{error}</div>}
  <section className="financial-metrics"><article><small>Captured</small><strong>{formatMoney(s?.captured_pence)}</strong><span>{s?.order_count??0} paid orders</span></article><article><small>Refunds</small><strong>{formatMoney(s?.refunded_pence)}</strong><span>Successful refunds</span></article><article><small>Platform revenue</small><strong>{formatMoney((s?.service_fees_pence??0)+(s?.commission_pence??0)+(s?.commission_vat_pence??0))}</strong><span>Fees, commission and VAT</span></article><article><small>Restaurant net</small><strong>{formatMoney(s?.net_revenue_pence)}</strong><span>After deductions and refunds</span></article></section>
  <section className="financial-toolbar"><label>From<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} max={iso(today)} onChange={e=>setTo(e.target.value)}/></label><label>Restaurant<select value={restaurant} onChange={e=>setRestaurant(e.target.value)}><option value="">All restaurants</option>{data?.restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></section>
  <section className="admin-panel financial-table"><div className="panel-heading"><div><h2>Restaurant statement</h2><p>{loading?'Loading financial data…':`${data?.rows.length??0} restaurants · ${from} to ${to}`}</p></div></div>{!loading&&!data?.rows.length?<div className="panel-empty"><strong>No settled sales in this period</strong><span>Change the date range or restaurant filter.</span></div>:<div className="financial-table-scroll"><table><thead><tr><th>Restaurant</th><th>Orders</th><th>Gross</th><th>Refunds</th><th>Commission</th><th>VAT</th><th>Service fees</th><th>Net revenue</th><th>Payouts</th></tr></thead><tbody>{data?.rows.map(r=><tr key={r.restaurant_id}><td><strong>{r.restaurant_name}</strong></td><td>{r.order_count}</td><td>{formatMoney(r.gross_sales_pence)}</td><td className="negative">−{formatMoney(r.refunded_pence)}</td><td>{formatMoney(r.commission_pence)}</td><td>{formatMoney(r.commission_vat_pence)}</td><td>{formatMoney(r.service_fees_pence)}</td><td><strong>{formatMoney(r.net_revenue_pence)}</strong></td><td><span className="payout-badge">{r.payout_status}</span></td></tr>)}</tbody></table></div>}</section>
  <p className="financial-note">Refunds are deducted from restaurant net revenue up to the restaurant-funded value of each order. Payout tracking will activate when Stripe Connect is configured.</p></div>
}
