import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney, hasAdminPermission } from '../types'
import { useAdmin } from '../components/AdminLayout'

type Summary={birthday_adoption:number;milestone_adoption:number;rewards_issued:number;redemption_rate:number;open_fraud_flags:number;revenue_generated_pence:number;campaign_cost_pence:number}
type RestaurantRow={restaurant_id:string;restaurant_name:string;birthday_enabled:boolean;birthday_disabled_by_platform:boolean;milestones_enabled:number;rewards_issued:number;redemptions:number;revenue_generated_pence:number;campaign_cost_pence:number}
type FraudFlag={id:string;restaurant_id:string;restaurant_name:string;customer_user_id:string|null;reward_issuance_id:string|null;source_type:string;flag_type:string;severity:string;status:string;details:Record<string,unknown>;created_at:string}
type Dashboard={summary:Summary;restaurants:RestaurantRow[];fraud_flags:FraudFlag[]}
const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase());const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'})
export default function Milestones(){const{admin}=useAdmin();const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const canDisable=hasAdminPermission(admin,'moderation:manage');const canReview=hasAdminPermission(admin,'moderation:manage')
async function load(){setLoading(true);setError('');const{data,error:rpcError}=await supabase.rpc('get_platform_milestone_dashboard');if(rpcError)setError(rpcError.message);else setDash(data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
async function toggleBirthday(row:RestaurantRow){const disabling=!row.birthday_disabled_by_platform;if(disabling&&!row.birthday_enabled)return;const reason=disabling?window.prompt('Reason for disabling this birthday programme?','Suspected birthday reward abuse'):null;if(disabling&&!reason)return;setBusy(row.restaurant_id);const{error:rpcError}=await supabase.rpc('platform_set_birthday_program_disabled',{p_restaurant_id:row.restaurant_id,p_disabled:disabling,p_reason:reason});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
async function review(flag:FraudFlag,status:'confirmed'|'dismissed'){const note=window.prompt(`Optional note for ${status} decision:`,'');setBusy(flag.id);const{error:rpcError}=await supabase.rpc('platform_review_reward_fraud_flag',{p_flag_id:flag.id,p_status:status,p_note:note||''});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
if(loading)return <section className="admin-page"><p>Loading birthday and milestone intelligence…</p></section>;const s=dash?.summary||{birthday_adoption:0,milestone_adoption:0,rewards_issued:0,redemption_rate:0,open_fraud_flags:0,revenue_generated_pence:0,campaign_cost_pence:0};
return <section className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Retention & trust</span><h1>Birthdays & milestones</h1><p>Platform adoption, reward economics, conversions and abuse monitoring.</p></div><button type="button" className="admin-button" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="admin-alert admin-alert-danger">{error}</div>}
<div className="admin-stat-grid"><article><span>Birthday adoption</span><strong>{s.birthday_adoption}</strong><small>Restaurants enabled</small></article><article><span>Milestone adoption</span><strong>{s.milestone_adoption}</strong><small>Restaurants with active milestones</small></article><article><span>Rewards issued</span><strong>{s.rewards_issued}</strong><small>Birthday + milestone</small></article><article><span>Redemption rate</span><strong>{Number(s.redemption_rate).toFixed(1)}%</strong><small>Reward engagement</small></article><article><span>Revenue generated</span><strong>{formatMoney(s.revenue_generated_pence)}</strong><small>Attributed repeat visits</small></article><article><span>Campaign cost</span><strong>{formatMoney(s.campaign_cost_pence)}</strong><small>Issued / redeemed value</small></article><article><span>Open fraud flags</span><strong>{s.open_fraud_flags}</strong><small>Needs review</small></article></div>
<div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Restaurant comparison</span><h2>Campaign performance</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Birthday</th><th>Milestones</th><th>Issued</th><th>Redeemed</th><th>Revenue</th><th>Cost</th><th>Control</th></tr></thead><tbody>{dash?.restaurants.map(row=><tr key={row.restaurant_id}><td><strong>{row.restaurant_name}</strong></td><td>{row.birthday_disabled_by_platform?'Platform disabled':row.birthday_enabled?'Enabled':'Paused'}</td><td>{row.milestones_enabled}</td><td>{row.rewards_issued}</td><td>{row.redemptions}</td><td>{formatMoney(row.revenue_generated_pence)}</td><td>{formatMoney(row.campaign_cost_pence)}</td><td>{canDisable?<button type="button" className="admin-button admin-button-small" disabled={busy===row.restaurant_id||(!row.birthday_enabled&&!row.birthday_disabled_by_platform)} onClick={()=>void toggleBirthday(row)}>{row.birthday_disabled_by_platform?'Re-enable birthday':row.birthday_enabled?'Disable birthday':'Restaurant paused'}</button>:<small>View only</small>}</td></tr>)}</tbody></table></div></div>
<div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Fraud monitoring</span><h2>Birthday and reward risk signals</h2></div><small>DOB values are never exposed here.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Signal</th><th>Source</th><th>Severity</th><th>Status</th><th>Detected</th><th>Review</th></tr></thead><tbody>{dash?.fraud_flags.length?dash.fraud_flags.map(flag=><tr key={flag.id}><td>{flag.restaurant_name}</td><td><strong>{text(flag.flag_type)}</strong></td><td>{text(flag.source_type)}</td><td>{text(flag.severity)}</td><td>{text(flag.status)}</td><td>{date.format(new Date(flag.created_at))}</td><td>{flag.status==='open'&&canReview?<div className="admin-inline-actions"><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'confirmed')}>Confirm</button><button type="button" className="admin-button admin-button-small admin-button-secondary" disabled={busy===flag.id} onClick={()=>void review(flag,'dismissed')}>Dismiss</button></div>:<small>{flag.status==='open'?'View only':'Reviewed'}</small>}</td></tr>):<tr><td colSpan={7}>No suspicious birthday or milestone activity.</td></tr>}</tbody></table></div></div></section>}
