import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { hasAdminPermission } from '../types'

type Group={id:string;name:string;slug:string;group_type:string;status:string;default_currency:string;countries:string[];enterprise_plan_code:string|null;locations:number;brands:number;members:number;created_at:string}
const pretty=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())
export default function Organisations(){const{admin}=useAdmin(),canManage=hasAdminPermission(admin,'restaurants:manage'),[groups,setGroups]=useState<Group[]>([]),[selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<any>(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[create,setCreate]=useState({name:'',slug:'',group_type:'parent_company',currency:'GBP',countries:'GB',plan:''}),[action,setAction]=useState({type:'',reason:'',restaurant_id:'',target_restaurant_id:'',target_group_id:'',brand_id:'',plan:''});
 const load=useCallback(async()=>{setLoading(true);setError('');const{data,error:e}=await supabase.rpc('get_platform_restaurant_groups',{p_search:search.trim()||null,p_page:1,p_page_size:100});if(e){setError(e.message);setGroups([])}else{const rows=(data as any)?.groups??[];setGroups(rows);setSelectedId(current=>rows.some((r:Group)=>r.id===current)?current:rows[0]?.id??'')}setLoading(false)},[search]);
 const loadDetail=useCallback(async(id:string)=>{if(!id){setDetail(null);return}const{data,error:e}=await supabase.rpc('get_platform_restaurant_group',{p_group_id:id});if(e)setError(e.message);else setDetail(data)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?250:0);return()=>window.clearTimeout(timer)},[load,search]);useEffect(()=>{if(selectedId)void loadDetail(selectedId)},[selectedId,loadDetail]);
 const selected=useMemo(()=>groups.find(g=>g.id===selectedId)??null,[groups,selectedId]);
 async function refresh(messageText?:string){await load();if(selectedId)await loadDetail(selectedId);if(messageText)setMessage(messageText)}
 async function createGroup(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');const{data,error:e2}=await supabase.rpc('platform_create_restaurant_group',{p_name:create.name,p_slug:create.slug,p_group_type:create.group_type,p_default_currency:create.currency.toUpperCase(),p_countries:create.countries.split(',').map(v=>v.trim().toUpperCase()).filter(Boolean),p_enterprise_plan_code:create.plan||null});if(e2)setError(e2.message);else{setCreate({name:'',slug:'',group_type:'parent_company',currency:'GBP',countries:'GB',plan:''});await load();if(data)setSelectedId(String(data));setMessage('Organisation created with enterprise roles and security defaults.')}setSaving(false)}
 async function manage(type:string,payload:Record<string,unknown>={}){if(!selected)return;setSaving(true);setError('');setMessage('');const{error:e}=await supabase.rpc('platform_manage_restaurant_group',{p_group_id:selected.id,p_action:type,p_payload:payload,p_reason:action.reason||null});if(e)setError(e.message);else{setAction({...action,type:'',reason:''});await refresh(`Organisation ${type} completed.`)}setSaving(false)}
 async function transfer(e:FormEvent){e.preventDefault();setSaving(true);const target=action.target_group_id||selectedId;const{error:e2}=await supabase.rpc('platform_transfer_restaurant_to_group',{p_restaurant_id:action.restaurant_id,p_group_id:target,p_brand_id:null,p_region_id:null,p_reason:action.reason||'Platform organisation transfer'});if(e2)setError(e2.message);else await refresh('Restaurant transferred with audit history preserved.');setSaving(false)}
 async function merge(e:FormEvent){e.preventDefault();setSaving(true);const{error:e2}=await supabase.rpc('platform_merge_restaurants',{p_source_restaurant_id:action.restaurant_id,p_target_restaurant_id:action.target_restaurant_id,p_reason:action.reason});if(e2)setError(e2.message);else await refresh('Restaurants merged; the source location was suspended and history retained.');setSaving(false)}
 async function moveBrand(e:FormEvent){e.preventDefault();setSaving(true);const{error:e2}=await supabase.rpc('platform_move_brand',{p_brand_id:action.brand_id,p_target_group_id:action.target_group_id,p_reason:action.reason});if(e2)setError(e2.message);else await refresh('Brand moved to the target organisation.');setSaving(false)}
 return <div className="admin-page restaurants-page"><header className="page-heading"><div><span className="admin-kicker">Enterprise operations</span><h1>Organisations</h1><p>Create groups, manage enterprise plans, move brands and restaurants, merge locations and inspect corporate audit history.</p></div></header>{error&&<div className="admin-alert error">{error}</div>}{message&&<div className="admin-alert success">{message}</div>}
 <div className="restaurant-toolbar"><label className="admin-search"><span>⌕</span><input type="search" placeholder="Search organisations…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <div className="restaurant-workspace"><section className="restaurant-list"><div className="list-heading"><strong>{loading?'Loading…':`${groups.length} organisations`}</strong><small>Enterprise & multi-location</small></div>{groups.map(g=><button type="button" className={`restaurant-list-row ${selectedId===g.id?'active':''}`} onClick={()=>setSelectedId(g.id)} key={g.id}><span className="restaurant-logo">{g.name.slice(0,1).toUpperCase()}</span><span><strong>{g.name}</strong><small>{g.locations} locations · {g.brands} brands · {g.members} staff</small></span><span className={`status-badge ${g.status}`}>{pretty(g.status)}</span></button>)}</section>
 <section className="restaurant-detail">{!selected?<div className="panel-empty"><strong>Select an organisation</strong></div>:<><div className="restaurant-detail-header"><div className="restaurant-identity"><span className="restaurant-logo large">{selected.name.slice(0,1).toUpperCase()}</span><div><span className={`status-badge ${selected.status}`}>{pretty(selected.status)}</span><h2>{selected.name}</h2><p>{pretty(selected.group_type)} · {selected.default_currency} · {selected.countries?.join(', ')}</p></div></div></div>
 <div className="restaurant-summary"><Summary label="Locations" value={String(selected.locations)}/><Summary label="Brands" value={String(selected.brands)}/><Summary label="Enterprise plan" value={selected.enterprise_plan_code||'Not assigned'}/></div>
 {detail&&<><section className="admin-card"><span className="admin-kicker">Organisation structure</span><h3>Brands & locations</h3><div className="table-scroll"><table><thead><tr><th>Location</th><th>Brand</th><th>Region</th><th>Status</th><th>Currency</th></tr></thead><tbody>{(detail.locations??[]).map((l:any)=><tr key={l.restaurant_id}><td><strong>{l.name}</strong><small>/{l.slug}</small></td><td>{detail.brands?.find((b:any)=>b.id===l.brand_id)?.name||'—'}</td><td>{detail.regions?.find((r:any)=>r.id===l.region_id)?.name||'—'}</td><td>{pretty(l.status)}</td><td>{l.currency}</td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><span className="admin-kicker">Corporate audit log</span><h3>Latest activity</h3><div className="table-scroll"><table><thead><tr><th>When</th><th>Action</th><th>Target</th><th>Reason</th></tr></thead><tbody>{(detail.audit??[]).slice(0,50).map((a:any)=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('en-GB')}</td><td>{a.action}</td><td>{a.target_type}</td><td>{a.reason||'—'}</td></tr>)}</tbody></table></div></section></>}
 {canManage&&<><div className="restaurant-actions"><button className="secondary-button" onClick={()=>setAction({...action,type:'plan',plan:selected.enterprise_plan_code||''})}>Enterprise plan</button>{selected.status==='active'?<button className="danger-button ghost" onClick={()=>setAction({...action,type:'suspend'})}>Suspend organisation</button>:<button className="admin-primary-button" onClick={()=>void manage('resume')}>Resume organisation</button>}</div>
 {action.type&&<section className="action-confirmation"><div><span className="admin-kicker">Platform control</span><h3>{pretty(action.type)} organisation</h3></div>{action.type==='plan'?<><label>Enterprise plan code<input value={action.plan} onChange={e=>setAction({...action,plan:e.target.value})}/></label><div className="confirmation-buttons"><button className="secondary-button" onClick={()=>setAction({...action,type:''})}>Cancel</button><button className="admin-primary-button" disabled={saving} onClick={()=>void manage('update',{enterprise_plan_code:action.plan||null})}>Save plan</button></div></>:<><label>Reason<textarea required rows={3} value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})}/></label><div className="confirmation-buttons"><button className="secondary-button" onClick={()=>setAction({...action,type:''})}>Cancel</button><button className="danger-button" disabled={saving||action.reason.trim().length<5} onClick={()=>void manage(action.type)}>Confirm</button></div></>}</section>}
 <div className="admin-grid two"><form className="admin-card" onSubmit={transfer}><span className="admin-kicker">Restaurant transfer</span><h3>Move restaurant</h3><input required placeholder="Restaurant UUID" value={action.restaurant_id} onChange={e=>setAction({...action,restaurant_id:e.target.value})}/><select value={action.target_group_id} onChange={e=>setAction({...action,target_group_id:e.target.value})}><option value="">This organisation</option>{groups.filter(g=>g.id!==selected.id).map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><textarea required placeholder="Reason" value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})}/><button className="admin-primary-button" disabled={saving}>Transfer</button></form>
 <form className="admin-card" onSubmit={merge}><span className="admin-kicker">Safe merge</span><h3>Merge restaurants</h3><input required placeholder="Source restaurant UUID" value={action.restaurant_id} onChange={e=>setAction({...action,restaurant_id:e.target.value})}/><input required placeholder="Target restaurant UUID" value={action.target_restaurant_id} onChange={e=>setAction({...action,target_restaurant_id:e.target.value})}/><textarea required minLength={5} placeholder="Reason" value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})}/><button className="danger-button" disabled={saving}>Merge & suspend source</button></form>
 <form className="admin-card" onSubmit={moveBrand}><span className="admin-kicker">Brand ownership</span><h3>Move brand</h3><select required value={action.brand_id} onChange={e=>setAction({...action,brand_id:e.target.value})}><option value="">Select brand</option>{(detail?.brands??[]).map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select><select required value={action.target_group_id} onChange={e=>setAction({...action,target_group_id:e.target.value})}><option value="">Target organisation</option>{groups.filter(g=>g.id!==selected.id).map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><textarea required minLength={5} placeholder="Reason" value={action.reason} onChange={e=>setAction({...action,reason:e.target.value})}/><button className="admin-primary-button" disabled={saving}>Move brand</button></form></div></>}</>}</section></div>
 {canManage&&<form className="admin-card" onSubmit={createGroup} style={{marginTop:20}}><span className="admin-kicker">New enterprise customer</span><h2>Create organisation</h2><div className="admin-grid two"><label>Name<input required value={create.name} onChange={e=>setCreate({...create,name:e.target.value})}/></label><label>Slug<input required value={create.slug} onChange={e=>setCreate({...create,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/></label><label>Type<select value={create.group_type} onChange={e=>setCreate({...create,group_type:e.target.value})}>{['parent_company','franchise_group','independent_chain','corporate_ownership'].map(v=><option value={v} key={v}>{pretty(v)}</option>)}</select></label><label>Currency<input maxLength={3} value={create.currency} onChange={e=>setCreate({...create,currency:e.target.value.toUpperCase()})}/></label><label>Countries<input placeholder="GB, IE" value={create.countries} onChange={e=>setCreate({...create,countries:e.target.value})}/></label><label>Enterprise plan<input placeholder="enterprise-pro" value={create.plan} onChange={e=>setCreate({...create,plan:e.target.value})}/></label></div><button className="admin-primary-button" disabled={saving}>{saving?'Saving…':'Create organisation'}</button></form>}
 </div>}
function Summary({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
