import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { formatDate, formatMoney, hasAdminPermission } from '../types'

type PaymentRow = { id:string; order_number:number; restaurant_name:string; customer_email:string|null; total_pence:number; refunded_pence:number; refundable_pence:number; currency:string; payment_status:string; paid_at:string|null; created_at:string; stripe_payment_intent_id:string|null }
type RefundRow = { id:string; amount_pence:number; reason:string; status:string; stripe_refund_id:string|null; failure_message:string|null; requested_by_name:string; created_at:string; completed_at:string|null }
type Snapshot = { payments:PaymentRow[]; summary:{ captured_pence:number; refunded_pence:number; failed_count:number; refund_pending_count:number }; pagination:{ page:number; total:number; total_pages:number } }
type Detail = { payment:PaymentRow; refunds:RefundRow[] }

export default function Payments(){
  const { admin }=useAdmin(); const canRefund=hasAdminPermission(admin,'finance:manage')
  const [params]=useSearchParams()
  const [status,setStatus]=useState(''); const [search,setSearch]=useState(params.get('search')??''); const [page,setPage]=useState(1)
  const [data,setData]=useState<Snapshot|null>(null); const [selected,setSelected]=useState<string|null>(null); const [detail,setDetail]=useState<Detail|null>(null)
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [submitting,setSubmitting]=useState(false)
  const [form,setForm]=useState({ amount:'', reason:'' })
  const load=useCallback(async()=>{ setLoading(true); setError(''); const {data:result,error:e}=await supabase.rpc('get_platform_payments',{p_payment_status:status||null,p_search:search.trim()||null,p_page:page,p_page_size:40}); if(e)setError(e.message); else { const next=result as Snapshot; setData(next); setSelected(current=>next.payments.some(x=>x.id===current)?current:next.payments[0]?.id??null) } setLoading(false) },[page,search,status])
  const loadDetail=useCallback(async(id:string)=>{ const {data:result,error:e}=await supabase.rpc('get_platform_payment',{p_order_id:id}); if(e)setError(e.message); else { const next=result as Detail; setDetail(next); setForm({amount:(next.payment.refundable_pence/100).toFixed(2),reason:''}) } },[])
  useEffect(()=>{const t=window.setTimeout(()=>void load(),search?300:0);return()=>clearTimeout(t)},[load,search])
  useEffect(()=>{if(selected)void loadDetail(selected);else setDetail(null)},[loadDetail,selected])
  async function submitRefund(event:FormEvent){event.preventDefault();if(!detail)return;setError('');setSuccess('');setSubmitting(true);const amount=Math.round(Number(form.amount)*100);const {data:result,error:e}=await supabase.functions.invoke('admin-refund-payment',{body:{order_id:detail.payment.id,amount_pence:amount,reason:form.reason}});setSubmitting(false);if(e||result?.error){setError(result?.error||e?.message||'Refund failed.');return}setSuccess(`${formatMoney(amount)} refund submitted successfully.`);await load();await loadDetail(detail.payment.id)}
  return <div className="admin-page payments-page"><header className="page-heading"><div><span className="admin-kicker">Money movement</span><h1>Payments & refunds</h1><p>Inspect captured and failed payments, issue controlled refunds and retain a complete financial record.</p></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></header>
  {error&&<div className="admin-alert error" role="alert">{error}</div>}{success&&<div className="admin-alert success" role="status">{success}</div>}
  <section className="payment-metrics"><article><small>Captured</small><strong>{formatMoney(data?.summary.captured_pence)}</strong></article><article><small>Refunded</small><strong>{formatMoney(data?.summary.refunded_pence)}</strong></article><article><small>Failed payments</small><strong>{data?.summary.failed_count??0}</strong></article><article><small>Refunds processing</small><strong>{data?.summary.refund_pending_count??0}</strong></article></section>
  <section className="payment-toolbar"><input type="search" placeholder="Order, restaurant, email or payment ID…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All payment statuses</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="partially_refunded">Partially refunded</option><option value="refunded">Refunded</option></select></section>
  <div className="payment-workspace"><section className="payment-list"><div className="list-heading"><strong>{loading?'Loading…':`${data?.pagination.total??0} payments`}</strong></div>{!loading&&!data?.payments.length&&<div className="panel-empty"><strong>No payments found</strong><span>Try changing the filters.</span></div>}{data?.payments.map(p=><button className={selected===p.id?'active':''} onClick={()=>{setSelected(p.id);setError('');setSuccess('')}} key={p.id}><span><strong>#{p.order_number} · {p.restaurant_name}</strong><small>{p.customer_email||'Customer details restricted'} · {formatDate(p.created_at)}</small></span><span><strong>{formatMoney(p.total_pence)}</strong><small className={`payment-badge ${p.payment_status}`}>{p.payment_status.replaceAll('_',' ')}</small></span></button>)}{(data?.pagination.total_pages??1)>1&&<div className="order-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹ Previous</button><span>Page {page} of {data?.pagination.total_pages}</span><button disabled={page>=(data?.pagination.total_pages??1)} onClick={()=>setPage(page+1)}>Next ›</button></div>}</section>
  <section className="payment-detail">{!detail?<div className="panel-empty">Select a payment to inspect it.</div>:<><div className="payment-detail-head"><div><span className="admin-kicker">Order #{detail.payment.order_number}</span><h2>{detail.payment.restaurant_name}</h2></div><span className={`payment-badge ${detail.payment.payment_status}`}>{detail.payment.payment_status.replaceAll('_',' ')}</span></div><div className="payment-facts"><article><small>Captured</small><strong>{formatMoney(detail.payment.total_pence)}</strong></article><article><small>Refunded</small><strong>{formatMoney(detail.payment.refunded_pence)}</strong></article><article><small>Available</small><strong>{formatMoney(detail.payment.refundable_pence)}</strong></article></div>{detail.payment.stripe_payment_intent_id&&<code className="payment-id">{detail.payment.stripe_payment_intent_id}</code>}
  {canRefund&&detail.payment.refundable_pence>0&&detail.payment.payment_status!=='failed'&&<form className="refund-form" onSubmit={submitRefund}><h3>Issue refund</h3><label>Amount (£)<input required type="number" min="0.01" max={(detail.payment.refundable_pence/100).toFixed(2)} step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Reason<textarea required minLength={3} maxLength={500} rows={3} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Required for the permanent audit record…"/></label><button className="admin-primary-button" disabled={submitting}>{submitting?'Processing refund…':'Confirm refund'}</button><small>Refunds cannot be reversed. The amount is reserved before Stripe is contacted to prevent duplicate refunds.</small></form>}
  <section className="refund-history"><h3>Refund history</h3>{!detail.refunds.length&&<div className="panel-empty">No refunds have been requested.</div>}{detail.refunds.map(r=><article key={r.id}><span><strong>{formatMoney(r.amount_pence)}</strong><small>{r.reason}</small></span><span className={`refund-state ${r.status}`}>{r.status}</span><span><small>{r.requested_by_name}</small><time>{formatDate(r.created_at)}</time></span>{r.failure_message&&<p>{r.failure_message}</p>}</article>)}</section></>}</section></div></div>
}
