import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { formatDate, formatMoney, hasAdminPermission } from '../types'

type Balance={restaurant_id:string;restaurant_name:string;restaurant_status:string;earned_pence:number;committed_pence:number;paid_pence:number;available_pence:number;last_paid_at:string|null}
type Payout={id:string;restaurant_id:string;restaurant_name:string;period_from:string;period_to:string;amount_pence:number;status:string;external_reference:string|null;notes:string|null;processed_at:string|null;paid_at:string|null;failed_at:string|null;created_at:string;created_by_name:string}
type Dashboard={balances:Balance[];payouts:Payout[];summary:{available_pence:number;processing_pence:number;paid_pence:number;failed_count:number}}
const today=()=>new Date().toISOString().slice(0,10)

export default function Payouts(){
 const {admin}=useAdmin(),canManage=hasAdminPermission(admin,'finance:manage')
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [selectedRestaurant,setSelectedRestaurant]=useState(''),[selectedPayout,setSelectedPayout]=useState<string|null>(null)
 const [form,setForm]=useState({from:'',to:today(),amount:'',notes:''}),[actionForm,setActionForm]=useState({reference:'',notes:''})
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:r,error:e}=await supabase.rpc('get_platform_payout_dashboard',{p_search:search.trim()||null,p_status:status||null});if(e)setError(e.message);else{const next=r as Dashboard;setData(next);setSelectedRestaurant(current=>next.balances.some(x=>x.restaurant_id===current)?current:next.balances[0]?.restaurant_id??'');setSelectedPayout(current=>next.payouts.some(x=>x.id===current)?current:next.payouts[0]?.id??null)}setLoading(false)},[search,status])
 useEffect(()=>{const t=setTimeout(()=>void load(),search?250:0);return()=>clearTimeout(t)},[load,search])
 const balance=useMemo(()=>data?.balances.find(x=>x.restaurant_id===selectedRestaurant)??null,[data,selectedRestaurant])
 const payout=useMemo(()=>data?.payouts.find(x=>x.id===selectedPayout)??null,[data,selectedPayout])
 useEffect(()=>{if(balance)setForm(f=>({...f,amount:(balance.available_pence/100).toFixed(2)}))},[balance])
 async function create(event:FormEvent){event.preventDefault();if(!balance)return;setSaving(true);setError('');setSuccess('');const amount=Math.round(Number(form.amount)*100);const {error:e}=await supabase.rpc('create_platform_restaurant_payout',{p_restaurant_id:balance.restaurant_id,p_period_from:form.from,p_period_to:form.to,p_amount_pence:amount,p_notes:form.notes.trim()||null});setSaving(false);if(e){setError(e.message);return}setSuccess('Draft payout created.');setForm({...form,from:'',amount:'',notes:''});await load()}
 async function act(action:string){if(!payout)return;setSaving(true);setError('');setSuccess('');const {error:e}=await supabase.rpc('manage_platform_restaurant_payout',{p_payout_id:payout.id,p_action:action,p_external_reference:actionForm.reference.trim()||null,p_notes:actionForm.notes.trim()||null});setSaving(false);if(e){setError(e.message);return}setSuccess('Payout updated.');setActionForm({reference:'',notes:''});await load()}
 function exportCsv(){if(!data?.payouts.length)return;const rows=[['Restaurant','Period from','Period to','Amount','Status','Reference','Created','Paid'],...data.payouts.map(p=>[p.restaurant_name,p.period_from,p.period_to,(p.amount_pence/100).toFixed(2),p.status,p.external_reference||'',p.created_at,p.paid_at||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`ordered-food-payouts-${today()}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="admin-page"><header className="page-heading"><div><span className="admin-kicker">Restaurant settlement</span><h1>Payouts & reconciliation</h1><p>Track restaurant balances, prepare payouts and retain external payment references.</p></div><button className="secondary-button" onClick={exportCsv} disabled={!data?.payouts.length}>↓ Export CSV</button></header>
 {error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="financial-metrics"><article><small>Available</small><strong>{formatMoney(data?.summary.available_pence)}</strong></article><article><small>Processing</small><strong>{formatMoney(data?.summary.processing_pence)}</strong></article><article><small>Paid</small><strong>{formatMoney(data?.summary.paid_pence)}</strong></article><article><small>Failed payouts</small><strong>{data?.summary.failed_count??0}</strong></article></section>
 <section className="financial-toolbar"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Restaurant or reference…"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All payouts</option>{['draft','processing','paid','failed','cancelled'].map(x=><option key={x}>{x}</option>)}</select></label><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></section>
 <div className="payment-workspace"><section className="payment-list"><div className="list-heading"><strong>Restaurant balances</strong></div>{data?.balances.map(b=><button key={b.restaurant_id} className={selectedRestaurant===b.restaurant_id?'active':''} onClick={()=>setSelectedRestaurant(b.restaurant_id)}><span><strong>{b.restaurant_name}</strong><small>{b.restaurant_status} · Last paid {formatDate(b.last_paid_at,false)}</small></span><span><strong>{formatMoney(b.available_pence)}</strong><small>available</small></span></button>)}</section>
 <section className="payment-detail">{!balance?<div className="panel-empty">Select a restaurant.</div>:<><div className="payment-detail-head"><div><span className="admin-kicker">Available balance</span><h2>{balance.restaurant_name}</h2></div><strong>{formatMoney(balance.available_pence)}</strong></div><div className="payment-facts"><article><small>Earned</small><strong>{formatMoney(balance.earned_pence)}</strong></article><article><small>Committed</small><strong>{formatMoney(balance.committed_pence)}</strong></article><article><small>Paid</small><strong>{formatMoney(balance.paid_pence)}</strong></article></div>{canManage&&balance.available_pence>0&&<form className="refund-form" onSubmit={create}><h3>Create draft payout</h3><label>Period from<input required type="date" max={form.to} value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label>Period to<input required type="date" max={today()} value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></label><label>Amount (£)<input required type="number" min="0.01" max={(balance.available_pence/100).toFixed(2)} step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Notes<textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="admin-primary-button" disabled={saving}>Create payout</button></form>}</>}</section></div>
 <section className="admin-panel financial-table"><div className="panel-heading"><div><h2>Payout ledger</h2><p>{data?.payouts.length??0} records</p></div></div><div className="financial-table-scroll"><table><thead><tr><th>Restaurant</th><th>Period</th><th>Amount</th><th>Status</th><th>Reference</th><th>Created</th></tr></thead><tbody>{data?.payouts.map(p=><tr key={p.id} onClick={()=>setSelectedPayout(p.id)}><td><strong>{p.restaurant_name}</strong></td><td>{p.period_from} – {p.period_to}</td><td>{formatMoney(p.amount_pence)}</td><td><span className="payout-badge">{p.status}</span></td><td>{p.external_reference||'—'}</td><td>{formatDate(p.created_at)}</td></tr>)}</tbody></table></div></section>
 {payout&&canManage&&<section className="admin-panel"><div className="panel-heading"><div><h2>Manage {payout.restaurant_name} payout</h2><p>{formatMoney(payout.amount_pence)} · {payout.status}</p></div></div><div className="refund-form"><label>External reference<input value={actionForm.reference} onChange={e=>setActionForm({...actionForm,reference:e.target.value})} placeholder="Required when marking paid"/></label><label>Internal notes<textarea rows={2} value={actionForm.notes} onChange={e=>setActionForm({...actionForm,notes:e.target.value})}/></label><div className="confirmation-buttons">{payout.status==='draft'&&<><button onClick={()=>void act('cancel')} className="danger-button ghost">Cancel</button><button onClick={()=>void act('start')} className="admin-primary-button">Start processing</button></>}{payout.status==='processing'&&<><button onClick={()=>void act('mark_failed')} className="danger-button ghost">Mark failed</button><button onClick={()=>void act('mark_paid')} className="admin-primary-button">Mark paid</button></>}{payout.status==='failed'&&<><button onClick={()=>void act('cancel')} className="danger-button ghost">Cancel</button><button onClick={()=>void act('retry')} className="admin-primary-button">Retry</button></>}</div></div></section>}
 </div>
}
