import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney, hasAdminPermission } from '../types'
import { useAdmin } from '../components/AdminLayout'

type Summary={restaurant_adoption:number;total_programmes:number;referrals:number;qualified:number;rewarded:number;conversion_rate:number;referred_revenue_pence:number;reward_cost_pence:number;open_fraud_flags:number}
type RestaurantRow={restaurant_id:string;restaurant_name:string;enabled:boolean;disabled_by_platform:boolean;referrals:number;qualified:number;rewarded:number;revenue_pence:number}
type FraudFlag={id:string;restaurant_id:string;restaurant_name:string;referral_id:string|null;flag_type:string;severity:string;status:string;details:Record<string,unknown>;created_at:string}
type Dashboard={summary:Summary;restaurants:RestaurantRow[];fraud_flags:FraudFlag[]}
const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase());const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'})
export default function Referrals(){const{admin}=useAdmin();const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const canDisable=hasAdminPermission(admin,'restaurants:manage');const canReview=hasAdminPermission(admin,'moderation:manage')
async function load(){setLoading(true);setError('');const{data,error:rpcError}=await supabase.rpc('get_platform_referral_dashboard');if(rpcError)setError(rpcError.message);else setDash(data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
async function toggle(row:RestaurantRow){const reason=row.disabled_by_platform?null:window.prompt('Reason for disabling this referral programme?','Suspicious or abusive referral activity');if(!row.disabled_by_platform&&!reason)return;setBusy(row.restaurant_id);const{error:rpcError}=await supabase.rpc('platform_set_referral_program_disabled',{p_restaurant_id:row.restaurant_id,p_disabled:!row.disabled_by_platform,p_reason:reason});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
async function review(flag:FraudFlag,status:'confirmed'|'dismissed'){setBusy(flag.id);const note=window.prompt(`Optional note for ${status} decision:`,'');const{error:rpcError}=await supabase.rpc('platform_review_referral_fraud_flag',{p_flag_id:flag.id,p_status:status,p_note:note||null});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
if(loading)return <section className="admin-page"><p>Loading referral intelligence…</p></section>;const s=dash?.summary||{restaurant_adoption:0,total_programmes:0,referrals:0,qualified:0,rewarded:0,conversion_rate:0,referred_revenue_pence:0,reward_cost_pence:0,open_fraud_flags:0}
return <section className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Growth & trust</span><h1>Referrals</h1><p>Platform-wide referral adoption, economics and fraud monitoring.</p></div><button type="button" className="admin-button" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="admin-alert admin-alert-danger">{error}</div>}
<div className="admin-stat-grid"><article><span>Restaurants live</span><strong>{s.restaurant_adoption}</strong><small>{s.total_programmes} configured</small></article><article><span>Referrals</span><strong>{s.referrals}</strong><small>{s.qualified} qualified</small></article><article><span>Conversion</span><strong>{Number(s.conversion_rate).toFixed(1)}%</strong><small>{s.rewarded} rewarded</small></article><article><span>Referred revenue</span><strong>{formatMoney(s.referred_revenue_pence)}</strong><small>Completed referred orders</small></article><article><span>Reward cost</span><strong>{formatMoney(s.reward_cost_pence)}</strong><small>Issued / redeemed value</small></article><article><span>Open risk flags</span><strong>{s.open_fraud_flags}</strong><small>Needs review</small></article></div>
<div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Adoption</span><h2>Restaurant programmes</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Status</th><th>Referrals</th><th>Qualified</th><th>Rewarded</th><th>Revenue</th><th>Control</th></tr></thead><tbody>{dash?.restaurants.map(row=><tr key={row.restaurant_id}><td><strong>{row.restaurant_name}</strong></td><td>{row.disabled_by_platform?'Platform disabled':row.enabled?'Enabled':'Paused'}</td><td>{row.referrals}</td><td>{row.qualified}</td><td>{row.rewarded}</td><td>{formatMoney(row.revenue_pence)}</td><td>{canDisable?<button type="button" className="admin-button admin-button-small" disabled={busy===row.restaurant_id} onClick={()=>void toggle(row)}>{row.disabled_by_platform?'Re-enable':'Disable'}</button>:<small>View only</small>}</td></tr>)}</tbody></table></div></div>
<div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Fraud monitoring</span><h2>Suspicious referral activity</h2></div><small>No raw card data is stored or exposed.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Signal</th><th>Severity</th><th>Status</th><th>Detected</th><th>Review</th></tr></thead><tbody>{dash?.fraud_flags.length?dash.fraud_flags.map(flag=><tr key={flag.id}><td>{flag.restaurant_name}</td><td><strong>{text(flag.flag_type)}</strong></td><td>{text(flag.severity)}</td><td>{text(flag.status)}</td><td>{date.format(new Date(flag.created_at))}</td><td>{flag.status==='open'&&canReview?<div className="admin-inline-actions"><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'confirmed')}>Confirm</button><button type="button" className="admin-button admin-button-small admin-button-secondary" disabled={busy===flag.id} onClick={()=>void review(flag,'dismissed')}>Dismiss</button></div>:<small>{flag.status==='open'?'View only':'Reviewed'}</small>}</td></tr>):<tr><td colSpan={6}>No suspicious referral activity.</td></tr>}</tbody></table></div></div></section>}
