import { FormEvent,useCallback,useEffect,useState } from 'react'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { formatDate,hasAdminPermission } from '../types'

type Schedule={id:string;name:string;report_type:string;cadence:string;delivery_hour:number;delivery_weekday:number|null;delivery_monthday:number|null;recipients:string[];is_active:boolean;last_run_at:string|null;next_run_at:string|null;created_by_name:string}
type Run={id:string;report_type:string;status:string;period_from:string;period_to:string;recipients:string[];row_count:number|null;file_name:string|null;error_message:string|null;requested_by_name:string;created_at:string;completed_at:string|null}
type Snapshot={schedules:Schedule[];runs:Run[]}
const reports=['financial_summary','order_operations','restaurant_performance','support_sla','risk_signals']
const today=()=>new Date().toISOString().slice(0,10)

export default function ScheduledReports(){
 const {admin}=useAdmin(),canManage=hasAdminPermission(admin,'finance:manage')
 const [data,setData]=useState<Snapshot>({schedules:[],runs:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [form,setForm]=useState({name:'Monthly finance pack',report_type:'financial_summary',cadence:'monthly',delivery_hour:'8',delivery_weekday:'1',delivery_monthday:'1',recipients:'',reason:''})
 const [manual,setManual]=useState({report_type:'financial_summary',from:today().slice(0,8)+'01',to:today(),recipients:''})
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:r,error:e}=await supabase.rpc('get_platform_report_schedules');if(e)setError(e.message);else setData(r as Snapshot);setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 async function createSchedule(e:FormEvent){e.preventDefault();setSaving(true);setError('');setSuccess('');const recipients=form.recipients.split(',').map(x=>x.trim()).filter(Boolean);const {error:e1}=await supabase.rpc('upsert_platform_report_schedule',{p_id:null,p_name:form.name,p_report_type:form.report_type,p_cadence:form.cadence,p_delivery_hour:Number(form.delivery_hour),p_delivery_weekday:form.cadence==='weekly'?Number(form.delivery_weekday):null,p_delivery_monthday:form.cadence==='monthly'?Number(form.delivery_monthday):null,p_recipients:recipients,p_filters:{},p_is_active:true,p_reason:form.reason});setSaving(false);if(e1)return setError(e1.message);setSuccess('Report schedule created.');setForm({...form,reason:''});await load()}
 async function runNow(e:FormEvent){e.preventDefault();setSaving(true);setError('');setSuccess('');const recipients=manual.recipients.split(',').map(x=>x.trim()).filter(Boolean);const {data:id,error:e1}=await supabase.rpc('queue_platform_report_run',{p_schedule_id:null,p_report_type:manual.report_type,p_period_from:manual.from,p_period_to:manual.to,p_recipients:recipients});if(e1){setSaving(false);return setError(e1.message)}const {data:result,error:e2}=await supabase.functions.invoke('process-admin-report',{body:{run_id:id}});setSaving(false);if(e2||result?.error)return setError(result?.error||e2?.message||'Report delivery failed.');setSuccess(`Report emailed successfully with ${result.row_count??0} rows.`);await load()}
 async function runSchedule(id:string){setSaving(true);setError('');const {data:runId,error:e1}=await supabase.rpc('queue_platform_report_run',{p_schedule_id:id,p_report_type:null,p_period_from:new Date(Date.now()-29*86400000).toISOString().slice(0,10),p_period_to:today(),p_recipients:null});if(!e1){const {data:r,error:e2}=await supabase.functions.invoke('process-admin-report',{body:{run_id:runId}});if(e2||r?.error)setError(r?.error||e2?.message);else setSuccess('Scheduled report delivered.')}else setError(e1.message);setSaving(false);await load()}
 return <div className="admin-page"><header className="page-heading"><div><span className="admin-kicker">Automated reporting</span><h1>Scheduled reports</h1><p>Email operational and financial CSV reports automatically, or generate one immediately.</p></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></header>
 {error&&<div className="admin-alert error">{error}</div>}{success&&<div className="admin-alert success">{success}</div>}
 <section className="financial-metrics"><article><small>Active schedules</small><strong>{data.schedules.filter(x=>x.is_active).length}</strong></article><article><small>Completed runs</small><strong>{data.runs.filter(x=>x.status==='completed').length}</strong></article><article><small>Failed runs</small><strong>{data.runs.filter(x=>x.status==='failed').length}</strong></article><article><small>Queued</small><strong>{data.runs.filter(x=>x.status==='queued').length}</strong></article></section>
 {canManage&&<div className="configuration-two-column"><form className="admin-panel configuration-panel" onSubmit={createSchedule}><div className="panel-heading"><div><h2>Create schedule</h2><p>Times use Europe/London.</p></div></div><div className="configuration-panel-body"><label>Name<input required minLength={3} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Report<select value={form.report_type} onChange={e=>setForm({...form,report_type:e.target.value})}>{reports.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label><label>Cadence<select value={form.cadence} onChange={e=>setForm({...form,cadence:e.target.value})}><option>daily</option><option>weekly</option><option>monthly</option></select></label><label>Delivery hour<input type="number" min="0" max="23" value={form.delivery_hour} onChange={e=>setForm({...form,delivery_hour:e.target.value})}/></label>{form.cadence==='weekly'&&<label>Weekday (1–7)<input type="number" min="1" max="7" value={form.delivery_weekday} onChange={e=>setForm({...form,delivery_weekday:e.target.value})}/></label>}{form.cadence==='monthly'&&<label>Day of month<input type="number" min="1" max="28" value={form.delivery_monthday} onChange={e=>setForm({...form,delivery_monthday:e.target.value})}/></label>}<label>Recipients<input type="text" required value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})} placeholder="finance@ordered.food, ops@ordered.food"/></label><label>Reason<textarea required minLength={5} rows={2} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className="admin-primary-button" disabled={saving}>Create schedule</button></div></form>
 <form className="admin-panel configuration-panel" onSubmit={runNow}><div className="panel-heading"><div><h2>Run now</h2><p>Generate and email a CSV immediately.</p></div></div><div className="configuration-panel-body"><label>Report<select value={manual.report_type} onChange={e=>setManual({...manual,report_type:e.target.value})}>{reports.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label><label>From<input type="date" value={manual.from} max={manual.to} onChange={e=>setManual({...manual,from:e.target.value})}/></label><label>To<input type="date" value={manual.to} min={manual.from} max={today()} onChange={e=>setManual({...manual,to:e.target.value})}/></label><label>Recipients<input required value={manual.recipients} onChange={e=>setManual({...manual,recipients:e.target.value})} placeholder="reports@ordered.food"/></label><button className="admin-primary-button" disabled={saving}>Generate & email</button></div></form></div>}
 <section className="admin-panel financial-table"><div className="panel-heading"><div><h2>Schedules</h2><p>{loading?'Loading…':`${data.schedules.length} configured`}</p></div></div><div className="financial-table-scroll"><table><thead><tr><th>Name</th><th>Report</th><th>Cadence</th><th>Recipients</th><th>Next run</th><th>Status</th><th/></tr></thead><tbody>{data.schedules.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{human(s.report_type)}</td><td>{human(s.cadence)} · {String(s.delivery_hour).padStart(2,'0')}:00</td><td>{s.recipients.join(', ')}</td><td>{formatDate(s.next_run_at)}</td><td><span className="payout-badge">{s.is_active?'active':'paused'}</span></td><td>{canManage&&<button className="secondary-button" disabled={saving} onClick={()=>void runSchedule(s.id)}>Run now</button>}</td></tr>)}</tbody></table></div></section>
 <section className="admin-panel financial-table"><div className="panel-heading"><div><h2>Delivery history</h2><p>Latest 100 report runs.</p></div></div><div className="financial-table-scroll"><table><thead><tr><th>Report</th><th>Period</th><th>Recipients</th><th>Rows</th><th>Status</th><th>Requested</th></tr></thead><tbody>{data.runs.map(r=><tr key={r.id}><td><strong>{human(r.report_type)}</strong>{r.error_message&&<small className="negative">{r.error_message}</small>}</td><td>{r.period_from} – {r.period_to}</td><td>{r.recipients.join(', ')}</td><td>{r.row_count??'—'}</td><td><span className={`payment-badge ${r.status}`}>{r.status}</span></td><td>{r.requested_by_name}<br/><small>{formatDate(r.created_at)}</small></td></tr>)}</tbody></table></div></section>
 </div>
}
function human(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}