import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAdmin } from '../components/AdminLayout'
import { supabase } from '../lib/supabase'
import { formatDate, hasAdminPermission } from '../types'

type CaseRow={id:string;case_number:number;subject:string;status:string;priority:string;category:string;customer_email:string|null;restaurant_name:string|null;order_number:number|null;assigned_to:string|null;assigned_to_name:string|null;updated_at:string;created_at:string}
type Activity={id:string;activity_type:string;body:string|null;metadata:Record<string,unknown>;actor_name:string;created_at:string}
type CaseDetail={case:CaseRow&{description:string;customer_phone:string|null;restaurant_id:string|null;order_id:string|null;resolved_at:string|null};activities:Activity[];admins:{user_id:string;display_name:string}[]}
type Snapshot={cases:CaseRow[];summary:{open:number;urgent:number;unassigned:number;resolved_today:number};pagination:{page:number;total:number;total_pages:number}}
const statuses=['open','in_progress','waiting_customer','waiting_restaurant','escalated','resolved','closed']

export default function Support(){
 const {admin}=useAdmin(),canManage=hasAdminPermission(admin,'support:manage')
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[page,setPage]=useState(1)
 const [data,setData]=useState<Snapshot|null>(null),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<CaseDetail|null>(null)
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[showNew,setShowNew]=useState(false)
 const [note,setNote]=useState(''),[newCase,setNewCase]=useState({subject:'',description:'',priority:'normal',category:'general',order_reference:'',customer_email:''})
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:r,error:e}=await supabase.rpc('get_platform_support_cases',{p_status:status||null,p_priority:priority||null,p_search:search.trim()||null,p_page:page,p_page_size:40});if(e)setError(e.message);else{const next=r as Snapshot;setData(next);setSelected(current=>next.cases.some(c=>c.id===current)?current:next.cases[0]?.id??null)}setLoading(false)},[page,priority,search,status])
 const loadDetail=useCallback(async(id:string)=>{const {data:r,error:e}=await supabase.rpc('get_platform_support_case',{p_case_id:id});if(e)setError(e.message);else setDetail(r as CaseDetail)},[])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?300:0);return()=>clearTimeout(timer)},[load,search])
 useEffect(()=>{if(selected)void loadDetail(selected);else setDetail(null)},[loadDetail,selected])
 async function mutate(action:string,value?:string){if(!detail)return;setSaving(true);setError('');setSuccess('');const {error:e}=await supabase.rpc('manage_platform_support_case',{p_case_id:detail.case.id,p_action:action,p_value:value||null});setSaving(false);if(e){setError(e.message);return}setSuccess('Case updated.');setNote('');await load();await loadDetail(detail.case.id)}
 async function createCase(event:FormEvent){event.preventDefault();setSaving(true);setError('');const {data:r,error:e}=await supabase.rpc('create_platform_support_case',{p_subject:newCase.subject,p_description:newCase.description,p_priority:newCase.priority,p_category:newCase.category,p_order_reference:newCase.order_reference.trim()||null,p_customer_email:newCase.customer_email.trim()||null});setSaving(false);if(e){setError(e.message);return}const created=r as {id:string};setShowNew(false);setNewCase({subject:'',description:'',priority:'normal',category:'general',order_reference:'',customer_email:''});await load();setSelected(created.id);setSuccess('Support case created.')}
 return <div className="admin-page support-page"><header className="page-heading"><div><span className="admin-kicker">Customer operations</span><h1>Support & disputes</h1><p>Own, investigate and resolve customer and restaurant issues from one auditable workspace.</p></div>{canManage&&<button className="admin-primary-button" onClick={()=>setShowNew(!showNew)}>{showNew?'Cancel':'＋ New case'}</button>}</header>
 {error&&<div className="admin-alert error" role="alert">{error}</div>}{success&&<div className="admin-alert success" role="status">{success}</div>}
 {showNew&&<form className="support-new" onSubmit={createCase}><h2>Create support case</h2><div><label>Subject<input required minLength={3} maxLength={160} value={newCase.subject} onChange={e=>setNewCase({...newCase,subject:e.target.value})}/></label><label>Priority<select value={newCase.priority} onChange={e=>setNewCase({...newCase,priority:e.target.value})}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label><label>Category<select value={newCase.category} onChange={e=>setNewCase({...newCase,category:e.target.value})}><option value="general">General</option><option value="order">Order</option><option value="payment">Payment</option><option value="refund">Refund</option><option value="delivery">Delivery</option><option value="restaurant">Restaurant</option><option value="account">Account</option><option value="dispute">Dispute</option></select></label><label>Order number or ID<input value={newCase.order_reference} onChange={e=>setNewCase({...newCase,order_reference:e.target.value})}/></label><label>Customer email<input type="email" value={newCase.customer_email} onChange={e=>setNewCase({...newCase,customer_email:e.target.value})}/></label></div><label>Description<textarea required minLength={3} maxLength={4000} rows={4} value={newCase.description} onChange={e=>setNewCase({...newCase,description:e.target.value})}/></label><button className="admin-primary-button" disabled={saving}>{saving?'Creating…':'Create case'}</button></form>}
 <section className="support-metrics"><article><small>Open</small><strong>{data?.summary.open??0}</strong></article><article><small>Urgent</small><strong>{data?.summary.urgent??0}</strong></article><article><small>Unassigned</small><strong>{data?.summary.unassigned??0}</strong></article><article><small>Resolved today</small><strong>{data?.summary.resolved_today??0}</strong></article></section>
 <section className="support-toolbar"><input type="search" placeholder="Case, order, customer, restaurant…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select><select value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="">All priorities</option><option>urgent</option><option>high</option><option>normal</option><option>low</option></select></section>
 <div className="support-workspace"><section className="support-list"><div className="list-heading"><strong>{loading?'Loading…':`${data?.pagination.total??0} cases`}</strong></div>{!loading&&!data?.cases.length&&<div className="panel-empty"><strong>No cases found</strong><span>Try changing the filters or create a case.</span></div>}{data?.cases.map(c=><button key={c.id} className={selected===c.id?'active':''} onClick={()=>{setSelected(c.id);setSuccess('')}}><span><strong>CASE-{c.case_number} · {c.subject}</strong><small>{c.order_number?`Order #${c.order_number} · `:''}{c.restaurant_name||c.customer_email||'Unlinked case'}</small></span><span><small className={`case-priority ${c.priority}`}>{c.priority}</small><small className={`case-status ${c.status}`}>{c.status.replaceAll('_',' ')}</small></span><time>{formatDate(c.updated_at)}</time></button>)}{(data?.pagination.total_pages??1)>1&&<div className="order-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹ Previous</button><span>Page {page} of {data?.pagination.total_pages}</span><button disabled={page>=(data?.pagination.total_pages??1)} onClick={()=>setPage(page+1)}>Next ›</button></div>}</section>
 <section className="support-detail">{!detail?<div className="panel-empty">Select a case to inspect it.</div>:<><header><div><span className="admin-kicker">CASE-{detail.case.case_number}</span><h2>{detail.case.subject}</h2><p>{detail.case.description}</p></div><span className={`case-status ${detail.case.status}`}>{detail.case.status.replaceAll('_',' ')}</span></header><div className="support-facts"><article><small>Priority</small><strong>{detail.case.priority}</strong></article><article><small>Category</small><strong>{detail.case.category}</strong></article><article><small>Owner</small><strong>{detail.case.assigned_to_name||'Unassigned'}</strong></article></div>{(detail.case.order_number||detail.case.restaurant_name||detail.case.customer_email)&&<div className="support-links">{detail.case.order_number&&<Link to={`/orders?search=${detail.case.order_number}`}>Order #{detail.case.order_number}</Link>}{detail.case.order_number&&<Link to={`/payments?search=${detail.case.order_number}`}>Payment & refunds</Link>}{detail.case.restaurant_name&&<span>{detail.case.restaurant_name}</span>}{detail.case.customer_email&&<a href={`mailto:${detail.case.customer_email}`}>{detail.case.customer_email}</a>}{detail.case.customer_phone&&<a href={`tel:${detail.case.customer_phone}`}>{detail.case.customer_phone}</a>}</div>}
 {canManage&&<div className="support-actions"><label>Status<select value={detail.case.status} disabled={saving} onChange={e=>void mutate('status',e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Owner<select value={detail.case.assigned_to||''} disabled={saving} onChange={e=>void mutate('assign',e.target.value||'unassigned')}><option value="">Unassigned</option>{detail.admins.map(a=><option value={a.user_id} key={a.user_id}>{a.display_name}</option>)}</select></label><label>Priority<select value={detail.case.priority} disabled={saving} onChange={e=>void mutate('priority',e.target.value)}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label></div>}
 <section className="case-timeline"><h3>Case activity</h3>{detail.activities.map(a=><article key={a.id}><span className="timeline-dot"/><div><strong>{a.activity_type.replaceAll('_',' ')}</strong>{a.body&&<p>{a.body}</p>}<small>{a.actor_name}</small></div><time>{formatDate(a.created_at)}</time></article>)}</section>{canManage&&<form className="support-note" onSubmit={e=>{e.preventDefault();void mutate('note',note)}}><label>Internal note<textarea required minLength={2} maxLength={4000} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add investigation details or contact history…"/></label><button className="admin-primary-button" disabled={saving}>{saving?'Saving…':'Add note'}</button></form>}</>}</section></div></div>
}
