import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatMoney, hasAdminPermission } from '../types'
import { useAdmin } from '../components/AdminLayout'

type Summary={restaurants_using_vip:number;total_vip_customers:number;restaurant_adoption_percent:number;vip_revenue_90d_pence:number;average_customer_value_pence:number;open_fraud_flags:number;benefit_events_90d:number;vip_discount_cost_90d_pence?:number;roi_percent?:number}
type RestaurantRow={restaurant_id:string;restaurant_name:string;is_enabled:boolean;disabled_by_platform:boolean;vip_customers:number;vip_revenue_90d_pence:number;avg_spend_pence:number;upgrades_30d:number;downgrades_30d:number;open_fraud_flags:number;vip_discount_cost_90d_pence?:number;roi_percent?:number}
type TierDistribution={tier_name:string;customers:number;revenue_pence:number}
type FraudFlag={id:string;restaurant_id:string;restaurant_name:string;customer_user_id:string|null;flag_type:string;severity:string;status:string;details:Record<string,unknown>;created_at:string;reviewed_at:string|null;review_note:string|null}
type Dashboard={summary:Summary;restaurants:RestaurantRow[];tier_distribution:TierDistribution[];fraud_flags:FraudFlag[]}
const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase());const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'})
export default function Vip(){const{admin}=useAdmin();const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const canManage=hasAdminPermission(admin,'restaurants:manage')
 async function load(){setLoading(true);setError('');const{data,error:rpcError}=await supabase.rpc('get_platform_vip_dashboard');if(rpcError)setError(rpcError.message);else setDash(data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
 async function toggleProgramme(row:RestaurantRow){const disabling=!row.disabled_by_platform;const reason=disabling?window.prompt('Reason for disabling this VIP programme?','Suspected VIP programme abuse'):null;if(disabling&&!reason)return;setBusy(row.restaurant_id);const{error:rpcError}=await supabase.rpc('platform_set_vip_program_disabled',{p_restaurant_id:row.restaurant_id,p_disabled:disabling,p_reason:reason});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
 async function review(flag:FraudFlag,status:'reviewed'|'dismissed'|'actioned'){const note=window.prompt(`Optional note for ${status} decision:`,'');setBusy(flag.id);const{error:rpcError}=await supabase.rpc('platform_review_vip_fraud_flag',{p_flag_id:flag.id,p_status:status,p_note:note||''});if(rpcError)setError(rpcError.message);else await load();setBusy('')}
 if(loading)return <section className="admin-page"><p>Loading VIP intelligence…</p></section>;const s=dash?.summary||{restaurants_using_vip:0,total_vip_customers:0,restaurant_adoption_percent:0,vip_revenue_90d_pence:0,average_customer_value_pence:0,open_fraud_flags:0,benefit_events_90d:0};
 return <section className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Retention & membership</span><h1>VIP programmes</h1><p>Platform adoption, tier economics, customer value, engagement and abuse monitoring.</p></div><button type="button" className="admin-button" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="admin-alert admin-alert-danger">{error}</div>}
 <div className="admin-stat-grid"><article><span>Restaurants using VIP</span><strong>{s.restaurants_using_vip}</strong><small>{Number(s.restaurant_adoption_percent).toFixed(1)}% adoption</small></article><article><span>VIP customers</span><strong>{s.total_vip_customers}</strong><small>Current tier members</small></article><article><span>VIP revenue · 90d</span><strong>{formatMoney(s.vip_revenue_90d_pence)}</strong><small>Orders placed with a VIP tier</small></article><article><span>Average customer value</span><strong>{formatMoney(s.average_customer_value_pence)}</strong><small>90 day VIP customer value</small></article><article><span>Benefit events · 90d</span><strong>{s.benefit_events_90d}</strong><small>Discounts, bonuses and rewards</small></article><article><span>VIP benefit cost · 90d</span><strong>{formatMoney(s.vip_discount_cost_90d_pence||0)}</strong><small>Automatic checkout discounts</small></article><article><span>VIP ROI</span><strong>{Number(s.roi_percent||0).toFixed(1)}%</strong><small>Revenue versus automatic discount cost</small></article><article><span>Open fraud flags</span><strong>{s.open_fraud_flags}</strong><small>Needs review</small></article></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Restaurant comparison</span><h2>VIP programme performance</h2></div><small>Sorted by 90 day VIP revenue.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Status</th><th>VIP customers</th><th>Revenue</th><th>Avg spend</th><th>Upgrades</th><th>Downgrades</th><th>ROI</th><th>Fraud</th><th>Control</th></tr></thead><tbody>{dash?.restaurants.length?dash.restaurants.map(row=><tr key={row.restaurant_id}><td><strong>{row.restaurant_name}</strong></td><td>{row.disabled_by_platform?'Platform disabled':row.is_enabled?'Enabled':'Restaurant paused'}</td><td>{row.vip_customers}</td><td>{formatMoney(row.vip_revenue_90d_pence)}</td><td>{formatMoney(row.avg_spend_pence)}</td><td>{row.upgrades_30d}</td><td>{row.downgrades_30d}</td><td>{Number(row.roi_percent||0).toFixed(1)}%</td><td>{row.open_fraud_flags}</td><td>{canManage?<button type="button" className="admin-button admin-button-small" disabled={busy===row.restaurant_id} onClick={()=>void toggleProgramme(row)}>{row.disabled_by_platform?'Re-enable':'Disable'}</button>:<small>View only</small>}</td></tr>):<tr><td colSpan={10}>No restaurants have configured VIP yet.</td></tr>}</tbody></table></div></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Tier distribution</span><h2>Membership mix</h2></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Tier name</th><th>Customers</th><th>Revenue · 90d</th></tr></thead><tbody>{dash?.tier_distribution.length?dash.tier_distribution.map((row,index)=><tr key={`${row.tier_name}-${index}`}><td><strong>{row.tier_name}</strong></td><td>{row.customers}</td><td>{formatMoney(row.revenue_pence)}</td></tr>):<tr><td colSpan={3}>No VIP tier distribution data yet.</td></tr>}</tbody></table></div></div>
 <div className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">Fraud monitoring</span><h2>VIP risk signals</h2></div><small>Tier changes remain server-controlled; these signals highlight abnormal activity.</small></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Restaurant</th><th>Signal</th><th>Severity</th><th>Status</th><th>Detected</th><th>Review</th></tr></thead><tbody>{dash?.fraud_flags.length?dash.fraud_flags.map(flag=><tr key={flag.id}><td>{flag.restaurant_name}</td><td><strong>{text(flag.flag_type)}</strong></td><td>{text(flag.severity)}</td><td>{text(flag.status)}</td><td>{date.format(new Date(flag.created_at))}</td><td>{flag.status==='open'&&canManage?<div className="admin-inline-actions"><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'reviewed')}>Review</button><button type="button" className="admin-button admin-button-small admin-button-secondary" disabled={busy===flag.id} onClick={()=>void review(flag,'dismissed')}>Dismiss</button><button type="button" className="admin-button admin-button-small" disabled={busy===flag.id} onClick={()=>void review(flag,'actioned')}>Actioned</button></div>:<small>{flag.status==='open'?'View only':'Reviewed'}</small>}</td></tr>):<tr><td colSpan={6}>No VIP fraud signals.</td></tr>}</tbody></table></div></div></section>
}
