import { useEffect, type ReactNode } from 'react'
import { Navigate, Route, Routes } from 'react-router-dom'
import Login from './auth/Login'
import Register from './auth/Register'
import ForgotPassword from './auth/ForgotPassword'
import ResetPassword from './auth/ResetPassword'
import ProtectedRoute from './components/ProtectedRoute'
import Home from './home/Home'
import Restaurants from './discovery/Restaurants'
import Dashboard from './dashboard/Dashboard'
import Onboarding from './onboarding/Onboarding'
import MenuBuilder from './menu/MenuBuilder'
import ModifierGroups from './menu/ModifierGroups'
import OpeningHours from './opening-hours/OpeningHours'
import Branding from './branding/Branding'
import RestaurantSettings from './settings/RestaurantSettings'
import RestaurantDetails from './settings/RestaurantDetails'
import DeliveryAreas from './settings/DeliveryAreas'
import DeliveryMap from './settings/DeliveryMap'
import Payments from './payments/Payments'
import Finance from './finance/Finance'
import Subscription from './subscription/Subscription'
import { SubscriptionAccessProvider, SubscriptionFeatureRoute, type SubscriptionFeature } from './subscription/SubscriptionAccess'
import Team from './team/Team'
import Marketing from './marketing/Marketing'
import MarketingWorkspaceNav from './marketing/MarketingWorkspaceNav'
import Milestones from './marketing/Milestones'
import VipProgramme from './marketing/VipProgramme'
import Challenges from './marketing/Challenges'
import MarketingCRM from './marketing/MarketingCRM'
import MarketingCustomer from './marketing/MarketingCustomer'
import Segments from './marketing/Segments'
import Campaigns from './marketing/Campaigns'
import Automations from './marketing/Automations'
import MarketingReports from './marketing/MarketingReports'
import MarketingTemplates from './marketing/MarketingTemplates'
import MarketingSettings from './marketing/MarketingSettings'
import AIInsights from './insights/AIInsights'
import GiftCards from './gift-cards/GiftCards'
import BuyGiftCard from './gift-cards/BuyGiftCard'
import GiftCardSuccess from './gift-cards/GiftCardSuccess'
import StorefrontGiftCardButton from './gift-cards/StorefrontGiftCardButton'
import LoyaltySettings from './loyalty/LoyaltySettings'
import RewardsManagement from './loyalty/RewardsManagement'
import StampPrograms from './loyalty/StampPrograms'
import StampOperations from './loyalty/StampOperations'
import StampAnalytics from './loyalty/StampAnalytics'
import ReferralProgram from './loyalty/ReferralProgram'
import Storefront from './storefront/Storefront'
import Checkout from './checkout/Checkout'
import OrderStatus from './order/OrderStatus'
import Orders from './orders/Orders'
import KitchenDisplay from './kds/KitchenDisplay'
import PrinterManagement from './printers/PrinterManagement'
import PrintHistory from './printers/PrintHistory'
import CustomerLogin from './customer/CustomerLogin'
import CustomerRegister from './customer/CustomerRegister'
import CustomerForgotPassword from './customer/CustomerForgotPassword'
import CustomerResetPassword from './customer/CustomerResetPassword'
import CustomerAccountHome from './customer/CustomerAccountHome'
import CustomerProfile from './customer/CustomerProfile'
import CustomerOrders from './customer/CustomerOrders'
import CustomerAddresses from './customer/CustomerAddresses'
import CustomerFavourites from './customer/CustomerFavourites'
import CustomerWallet from './customer/CustomerWallet'
import CustomerLoyalty from './customer/CustomerLoyalty'
import CustomerRewards from './customer/CustomerRewards'
import CustomerStamps from './customer/CustomerStamps'
import CustomerNotifications from './customer/CustomerNotifications'
import CustomerReferrals from './customer/CustomerReferrals'
import CustomerMilestones from './customer/CustomerMilestones'
import CustomerVip from './customer/CustomerVip'
import CustomerChallenges from './customer/CustomerChallenges'
import CustomerMarketingPreferences from './customer/CustomerMarketingPreferences'
import MarketingUnsubscribe from './customer/MarketingUnsubscribe'
import ReferralLanding from './customer/ReferralLanding'
import StampClaim from './customer/StampClaim'
import { claimPendingReferralAttribution } from './customer/referralAttribution'
import { supabase } from './lib/supabase'
import { PlatformConfigurationProvider, PlatformStatusBoundary, usePlatformConfiguration } from './lib/platformConfiguration'
import './checkout/CheckoutAccount.css'
import './checkout/CheckoutAddresses.css'

export default function App(){return <PlatformConfigurationProvider><PlatformStatusBoundary><SubscriptionAccessProvider><ApplicationRoutes/></SubscriptionAccessProvider></PlatformStatusBoundary></PlatformConfigurationProvider>}
function MarketingOverview(){return <><MarketingWorkspaceNav/><Marketing/></>}
const Feature=({name,children}:{name:SubscriptionFeature;children:ReactNode})=><SubscriptionFeatureRoute feature={name}>{children}</SubscriptionFeatureRoute>
function ApplicationRoutes(){const{configuration}=usePlatformConfiguration();useEffect(()=>{void claimPendingReferralAttribution();const{data}=supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'||event==='USER_UPDATED')void claimPendingReferralAttribution()});return()=>data.subscription.unsubscribe()},[]);return <Routes>
<Route path="/" element={<Home/>}/><Route path="/restaurants" element={<Restaurants/>}/><Route path="/ref/:code" element={<ReferralLanding/>}/><Route path="/marketing/unsubscribe" element={<MarketingUnsubscribe/>}/><Route path="/r/:slug" element={<><Storefront/><StorefrontGiftCardButton/></>}/><Route path="/r/:slug/checkout" element={<Checkout/>}/><Route path="/r/:slug/gift-card" element={<BuyGiftCard/>}/><Route path="/r/:slug/gift-card/success" element={<GiftCardSuccess/>}/><Route path="/order/success" element={<OrderStatus/>}/>
<Route path="/account/login" element={<CustomerLogin/>}/><Route path="/account/register" element={<CustomerRegister/>}/><Route path="/account/forgot-password" element={<CustomerForgotPassword/>}/><Route path="/account/reset-password" element={<CustomerResetPassword/>}/><Route path="/account" element={<CustomerAccountHome/>}/><Route path="/account/profile" element={<CustomerProfile/>}/><Route path="/account/orders" element={<CustomerOrders/>}/><Route path="/account/addresses" element={<CustomerAddresses/>}/><Route path="/account/wallet" element={<CustomerWallet/>}/><Route path="/account/loyalty" element={<CustomerLoyalty/>}/><Route path="/account/referrals" element={<CustomerReferrals/>}/><Route path="/account/milestones" element={<CustomerMilestones/>}/><Route path="/account/vip" element={<CustomerVip/>}/><Route path="/account/challenges" element={<CustomerChallenges/>}/><Route path="/account/stamps" element={<CustomerStamps/>}/><Route path="/account/stamps/claim" element={<StampClaim/>}/><Route path="/account/notifications" element={<CustomerNotifications/>}/><Route path="/account/marketing-preferences" element={<CustomerMarketingPreferences/>}/><Route path="/account/rewards/:restaurantId" element={<CustomerRewards/>}/><Route path="/account/favourites" element={configuration.feature_flags.customer_favourites?<CustomerFavourites/>:<Navigate to="/account" replace/>}/>
<Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/team" element={<Team/>}/>
<Route path="/dashboard" element={<ProtectedRoute><Dashboard/></ProtectedRoute>}/><Route path="/orders" element={<ProtectedRoute requiredPermission="orders:view"><Orders/></ProtectedRoute>}/><Route path="/kds" element={<ProtectedRoute requiredPermission="kds:view"><KitchenDisplay/></ProtectedRoute>}/><Route path="/printers" element={<ProtectedRoute requiredPermission="printers:view"><PrinterManagement/></ProtectedRoute>}/><Route path="/print-history" element={<ProtectedRoute requiredPermission="orders:view"><PrintHistory/></ProtectedRoute>}/><Route path="/onboarding" element={<ProtectedRoute allowApplication><Onboarding/></ProtectedRoute>}/><Route path="/menu" element={<ProtectedRoute requiredPermission="menu:view"><MenuBuilder/></ProtectedRoute>}/><Route path="/menu/modifiers" element={<ProtectedRoute requiredPermission="menu:manage"><ModifierGroups/></ProtectedRoute>}/><Route path="/opening-hours" element={<ProtectedRoute requiredPermission="settings:manage"><OpeningHours/></ProtectedRoute>}/><Route path="/branding" element={<ProtectedRoute requiredPermission="settings:manage"><Branding/></ProtectedRoute>}/><Route path="/settings" element={<ProtectedRoute requiredPermission="settings:manage"><RestaurantSettings/></ProtectedRoute>}/><Route path="/restaurant-details" element={<ProtectedRoute requiredPermission="settings:manage"><RestaurantDetails/></ProtectedRoute>}/><Route path="/delivery-areas" element={<ProtectedRoute requiredPermission="settings:manage"><DeliveryAreas/></ProtectedRoute>}/><Route path="/delivery-map" element={<ProtectedRoute requiredPermission="settings:manage"><DeliveryMap/></ProtectedRoute>}/><Route path="/payments" element={<ProtectedRoute allowPaymentSetup requiredPermission="billing:manage"><Payments/></ProtectedRoute>}/><Route path="/finance" element={<ProtectedRoute requiredPermission="billing:manage"><Finance/></ProtectedRoute>}/><Route path="/subscription" element={<ProtectedRoute allowPaymentSetup requiredPermission="billing:manage"><Subscription/></ProtectedRoute>}/>
<Route path="/insights/*" element={<ProtectedRoute requiredPermission="analytics:view"><Feature name="ai_insights"><AIInsights/></Feature></ProtectedRoute>}/><Route path="/marketing" element={<ProtectedRoute requiredPermission="marketing:view"><Feature name="marketing"><MarketingOverview/></Feature></ProtectedRoute>}/><Route path="/marketing/crm" element={<ProtectedRoute requiredPermission="customers:view"><Feature name="crm"><MarketingCRM/></Feature></ProtectedRoute>}/><Route path="/marketing/customers" element={<ProtectedRoute requiredPermission="customers:view"><Feature name="crm"><MarketingCRM/></Feature></ProtectedRoute>}/><Route path="/marketing/crm/:customerId" element={<ProtectedRoute requiredPermission="customers:view"><Feature name="crm"><MarketingCustomer/></Feature></ProtectedRoute>}/><Route path="/marketing/segments" element={<ProtectedRoute requiredPermission="marketing:view"><Feature name="marketing"><Segments/></Feature></ProtectedRoute>}/><Route path="/marketing/campaigns" element={<ProtectedRoute requiredPermission="marketing:view"><Feature name="marketing"><Campaigns/></Feature></ProtectedRoute>}/><Route path="/marketing/templates" element={<ProtectedRoute requiredPermission="marketing:view"><Feature name="marketing"><MarketingTemplates/></Feature></ProtectedRoute>}/><Route path="/marketing/automations" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="marketing_automation"><Automations/></Feature></ProtectedRoute>}/><Route path="/marketing/reports" element={<ProtectedRoute requiredPermission="analytics:view"><Feature name="advanced_analytics"><MarketingReports/></Feature></ProtectedRoute>}/><Route path="/marketing/analytics" element={<ProtectedRoute requiredPermission="analytics:view"><Feature name="advanced_analytics"><MarketingReports/></Feature></ProtectedRoute>}/><Route path="/marketing/settings" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="marketing"><MarketingSettings/></Feature></ProtectedRoute>}/><Route path="/marketing/milestones" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="birthday_rewards"><Milestones/></Feature></ProtectedRoute>}/><Route path="/marketing/vip" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="vip"><VipProgramme/></Feature></ProtectedRoute>}/><Route path="/marketing/challenges" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="challenges"><Challenges/></Feature></ProtectedRoute>}/><Route path="/gift-cards" element={<ProtectedRoute requiredPermission="marketing:manage"><GiftCards/></ProtectedRoute>}/><Route path="/loyalty" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="loyalty"><LoyaltySettings/></Feature></ProtectedRoute>}/><Route path="/loyalty/rewards" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="loyalty"><RewardsManagement/></Feature></ProtectedRoute>}/><Route path="/loyalty/referrals" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="referrals"><ReferralProgram/></Feature></ProtectedRoute>}/><Route path="/loyalty/stamps" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="stamp_cards"><StampPrograms/></Feature></ProtectedRoute>}/><Route path="/loyalty/stamps/operations" element={<ProtectedRoute requiredPermission="marketing:manage"><Feature name="stamp_cards"><StampOperations/></Feature></ProtectedRoute>}/><Route path="/loyalty/stamps/analytics" element={<ProtectedRoute requiredPermission="analytics:view"><Feature name="stamp_cards"><StampAnalytics/></Feature></ProtectedRoute>}/><Route path="*" element={<Navigate to="/" replace/>}/>
</Routes>}
