import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './Challenges.css'

type Condition = { id?:string; condition_type:string; target_value:number; menu_item_id?:string|null; category_id?:string|null; config?:Record<string,unknown>; sort_order?:number }
type Reward = { id?:string; reward_type:string; reward_value:number; menu_item_id?:string|null; stamp_program_id?:string|null; validity_days?:number|null; minimum_spend_pence?:number; config?:Record<string,unknown>; sort_order?:number }
type Challenge = { id:string; name:string; description:string; icon:string; colour:string; banner_image_url:string|null; starts_at:string; ends_at:string|null; is_active:boolean; priority:number; visibility:string; target_audience:string; target_config:Record<string,unknown>; condition_match:string; repeatable:boolean; repeat_period:string; max_completions:number|null; platform_disabled_at:string|null; platform_disabled_reason:string|null; conditions:Condition[]; rewards:Reward[]; participants:number; completions:number; revenue_generated_pence:number; reward_cost_pence:number }
type Achievement = { id:string; restaurant_id:string|null; name:string; description:string; icon:string; colour:string; achievement_type:string; target_value:number; is_system_default:boolean; is_active:boolean }
type Dashboard = { summary:{active_challenges:number;participants:number;completions:number;completion_percent:number;revenue_generated_pence:number;reward_cost_pence:number;average_spend_pence:number;repeat_visits:number}; challenges:Challenge[]; achievements:Achievement[]; leaderboard_settings:{is_enabled:boolean;metric:string;max_entries:number}; fraud_flags:Array<{id:string;flag_type:string;severity:string;status:string;created_at:string}> }
type MenuItem={id:string;name:string;category_id:string}
type Category={id:string;name:string}
type StampProgram={id:string;name:string;is_active:boolean}
type VipTier={id:string;name:string}
type LeaderboardRow={customer_user_id:string;display_name:string;score:number}
type FormState={id:string|null;name:string;description:string;icon:string;colour:string;banner:string;startsAt:string;endsAt:string;active:boolean;priority:string;visibility:string;audience:string;tierId:string;conditionMatch:string;repeatable:boolean;repeatPeriod:string;maxCompletions:string;conditions:Condition[];rewards:Reward[]}
const conditionLabels:Record<string,string>={order_count:'Order X times',total_spend:'Spend £X',single_order_spend:'Spend £X in one order',consecutive_weeks:'Visit consecutive weeks',consecutive_months:'Visit consecutive months',breakfast_orders:'Order breakfast X times',lunch_orders:'Order lunch X times',dinner_orders:'Order dinner X times',weekend_orders:'Order weekends',weekday_orders:'Order weekdays',distinct_menu_items:'Try X different menu items',distinct_categories:'Try X categories',featured_item:'Buy a featured item',seasonal:'Seasonal challenge',holiday:'Holiday challenge',vip_only:'VIP-only condition',referral_count:'Referral challenge',stamp_count:'Stamp challenge',points_balance:'Points balance',points_earned:'Points earned',custom:'Custom metric'}
const rewardLabels:Record<string,string>={loyalty_points:'Loyalty points',bonus_stamps:'Bonus stamps',wallet_credit:'Wallet credit',store_credit:'Store credit',fixed_voucher:'Fixed voucher',percentage_voucher:'Percentage voucher',free_delivery:'Free delivery',free_item:'Free item',vip_bonus:'VIP bonus',referral_bonus:'Referral bonus'}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
const localDate=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):''
const initial=():FormState=>({id:null,name:'',description:'',icon:'★',colour:'#9B111E',banner:'',startsAt:localDate(new Date().toISOString()),endsAt:'',active:true,priority:'0',visibility:'public',audience:'all',tierId:'',conditionMatch:'all',repeatable:false,repeatPeriod:'campaign',maxCompletions:'',conditions:[{condition_type:'order_count',target_value:3}],rewards:[{reward_type:'loyalty_points',reward_value:100,validity_days:30,minimum_spend_pence:0}]})
const valueNeedsMoney=(type:string)=>['total_spend','single_order_spend'].includes(type)
const rewardNeedsMoney=(type:string)=>['wallet_credit','store_credit','fixed_voucher'].includes(type)
const displayReward=(reward:Reward)=>reward.reward_type==='percentage_voucher'?`${reward.reward_value/100}%`:rewardNeedsMoney(reward.reward_type)?money.format(reward.reward_value/100):reward.reward_type==='free_delivery'||reward.reward_type==='free_item'?rewardLabels[reward.reward_type]:`${reward.reward_value} ${rewardLabels[reward.reward_type].toLowerCase()}`

export default function Challenges(){
 const[data,setData]=useState<Dashboard|null>(null),[form,setForm]=useState<FormState>(initial()),[menuItems,setMenuItems]=useState<MenuItem[]>([]),[categories,setCategories]=useState<Category[]>([]),[stampPrograms,setStampPrograms]=useState<StampProgram[]>([]),[vipTiers,setVipTiers]=useState<VipTier[]>([]),[leaderboard,setLeaderboard]=useState<LeaderboardRow[]>([]),[showBuilder,setShowBuilder]=useState(false),[saving,setSaving]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setError('');const [dash,items,cats,stamps,vip,board]=await Promise.all([supabase.rpc('get_restaurant_challenge_dashboard'),supabase.from('menu_items').select('id,name,category_id').order('name'),supabase.from('menu_categories').select('id,name').order('name'),supabase.rpc('get_restaurant_stamp_programs'),supabase.rpc('get_restaurant_vip_dashboard'),supabase.rpc('get_restaurant_challenge_leaderboard')]);if(dash.error)setError(dash.error.message);else setData(dash.data as Dashboard);if(!items.error)setMenuItems((items.data||[]) as MenuItem[]);if(!cats.error)setCategories((cats.data||[]) as Category[]);if(!stamps.error){const payload=stamps.data as {programs?:StampProgram[]}|null;setStampPrograms(payload?.programs||[])}if(!vip.error){const raw=vip.data as {tiers?:VipTier[]};setVipTiers(raw?.tiers||[])}if(!board.error)setLeaderboard((board.data||[]) as LeaderboardRow[])},[])
 useEffect(()=>{void load()},[load])
 const roi=useMemo(()=>{const revenue=data?.summary.revenue_generated_pence||0,cost=data?.summary.reward_cost_pence||0;return cost?((revenue-cost)/cost)*100:revenue?100:0},[data])
 function patch<K extends keyof FormState>(key:K,value:FormState[K]){setForm(v=>({...v,[key]:value}))}
 function patchCondition(index:number,key:keyof Condition,value:unknown){setForm(v=>({...v,conditions:v.conditions.map((c,i)=>i===index?({...c,[key]:value}):c)}))}
 function patchReward(index:number,key:keyof Reward,value:unknown){setForm(v=>({...v,rewards:v.rewards.map((r,i)=>i===index?({...r,[key]:value}):r)}))}
 function editChallenge(challenge:Challenge){setForm({id:challenge.id,name:challenge.name,description:challenge.description,icon:challenge.icon,colour:challenge.colour,banner:challenge.banner_image_url||'',startsAt:localDate(challenge.starts_at),endsAt:localDate(challenge.ends_at),active:challenge.is_active,priority:String(challenge.priority),visibility:challenge.visibility,audience:challenge.target_audience,tierId:String(challenge.target_config?.tier_id||''),conditionMatch:challenge.condition_match,repeatable:challenge.repeatable,repeatPeriod:challenge.repeat_period,maxCompletions:challenge.max_completions?String(challenge.max_completions):'',conditions:challenge.conditions,rewards:challenge.rewards});setShowBuilder(true);window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setNotice('');const conditions=form.conditions.map((c,i)=>({...c,target_value:valueNeedsMoney(c.condition_type)?Math.round(Number(c.target_value)*100):Number(c.target_value),sort_order:i,config:c.condition_type==='custom'?{metric_key:String(c.config?.metric_key||'custom_metric')}:c.config||{}}));const rewards=form.rewards.map((r,i)=>({...r,reward_value:r.reward_type==='percentage_voucher'?Math.round(Number(r.reward_value)*100):rewardNeedsMoney(r.reward_type)?Math.round(Number(r.reward_value)*100):Number(r.reward_value),validity_days:r.validity_days?Number(r.validity_days):null,minimum_spend_pence:Number(r.minimum_spend_pence||0),sort_order:i}));const{error:saveError}=await supabase.rpc('save_restaurant_challenge',{p_challenge_id:form.id,p_name:form.name,p_description:form.description,p_icon:form.icon,p_colour:form.colour,p_banner_image_url:form.banner||null,p_starts_at:new Date(form.startsAt).toISOString(),p_ends_at:form.endsAt?new Date(form.endsAt).toISOString():null,p_is_active:form.active,p_priority:Number(form.priority||0),p_visibility:form.visibility,p_target_audience:form.audience,p_target_config:form.audience==='tier'?{tier_id:form.tierId}:{},p_condition_match:form.conditionMatch,p_repeatable:form.repeatable,p_repeat_period:form.repeatable?form.repeatPeriod:'campaign',p_max_completions:form.maxCompletions?Number(form.maxCompletions):null,p_conditions:conditions,p_rewards:rewards});if(saveError)setError(saveError.message);else{setNotice(form.id?'Challenge updated.':'Challenge created and eligible customers will be notified.');setForm(initial());setShowBuilder(false);await load()}setSaving(false)}
 async function clone(id:string){setBusy(id);const{error:e}=await supabase.rpc('clone_restaurant_challenge',{p_challenge_id:id,p_name:null});if(e)setError(e.message);else{setNotice('Challenge cloned as an inactive copy.');await load()}setBusy('')}
 async function remove(id:string){if(!window.confirm('Delete this challenge? Challenges with customer history will be safely deactivated instead.'))return;setBusy(id);const{error:e}=await supabase.rpc('delete_restaurant_challenge',{p_challenge_id:id});if(e)setError(e.message);else await load();setBusy('')}
 async function saveLeaderboard(enabled:boolean,metric:string,maxEntries:number){const{error:e}=await supabase.rpc('save_restaurant_leaderboard_settings',{p_enabled:enabled,p_metric:metric,p_max_entries:maxEntries});if(e)setError(e.message);else await load()}
 async function createAchievement(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const{error:e2}=await supabase.rpc('save_restaurant_achievement',{p_achievement_id:null,p_name:String(fd.get('name')||''),p_description:String(fd.get('description')||''),p_icon:String(fd.get('icon')||'★'),p_colour:String(fd.get('colour')||'#171615'),p_achievement_type:String(fd.get('type')||'orders'),p_target_value:Number(fd.get('target')||1),p_config:{},p_is_active:true});if(e2)setError(e2.message);else{e.currentTarget.reset();setNotice('Custom achievement created.');await load()}}
 if(!data)return <main className="challenge-shell"><p>{error||'Loading challenges…'}</p></main>
 return <main className="challenge-shell">
  <header className="challenge-header"><div><Link to="/dashboard" className="brand">ordered.food</Link><p>Marketing · Challenges</p></div><div><Link to="/marketing">Marketing</Link><button className="primary-button" onClick={()=>{setForm(initial());setShowBuilder(v=>!v)}}>{showBuilder?'Close builder':'New challenge'}</button></div></header>
  <section className="challenge-hero"><div><span className="eyebrow">Phase 5.7</span><h1>Challenges & gamification</h1><p>Build missions that reward behaviour across orders, spend, menu discovery, referrals, stamps, points and VIP membership.</p></div></section>
  {error&&<p className="challenge-alert error" role="alert">{error}</p>}{notice&&<p className="challenge-alert success">{notice}</p>}
  <section className="challenge-metrics"><article><span>Active</span><strong>{data.summary.active_challenges}</strong></article><article><span>Participants</span><strong>{data.summary.participants}</strong></article><article><span>Completion</span><strong>{data.summary.completion_percent}%</strong></article><article><span>Revenue</span><strong>{money.format(data.summary.revenue_generated_pence/100)}</strong></article><article><span>Reward cost</span><strong>{money.format(data.summary.reward_cost_pence/100)}</strong></article><article><span>ROI</span><strong>{roi.toFixed(0)}%</strong></article></section>
  {showBuilder&&<section className="challenge-panel"><div className="panel-heading"><div><span className="eyebrow">Builder</span><h2>{form.id?'Edit challenge':'Create challenge'}</h2></div></div><form className="challenge-form" onSubmit={save}>
   <label><span>Name</span><input required value={form.name} onChange={e=>patch('name',e.target.value)} placeholder="Weekend Explorer"/></label><label><span>Icon</span><input value={form.icon} onChange={e=>patch('icon',e.target.value)} maxLength={8}/></label><label><span>Colour</span><input type="color" value={form.colour} onChange={e=>patch('colour',e.target.value)}/></label><label className="wide"><span>Description</span><textarea value={form.description} onChange={e=>patch('description',e.target.value)} placeholder="Complete the mission to unlock rewards."/></label><label className="wide"><span>Banner image URL</span><input type="url" value={form.banner} onChange={e=>patch('banner',e.target.value)} placeholder="https://…"/></label>
   <label><span>Starts</span><input required type="datetime-local" value={form.startsAt} onChange={e=>patch('startsAt',e.target.value)}/></label><label><span>Ends</span><input type="datetime-local" value={form.endsAt} onChange={e=>patch('endsAt',e.target.value)}/></label><label><span>Priority</span><input type="number" value={form.priority} onChange={e=>patch('priority',e.target.value)}/></label><label><span>Visibility</span><select value={form.visibility} onChange={e=>patch('visibility',e.target.value)}><option value="public">Public</option><option value="members">Members</option><option value="hidden">Hidden</option></select></label>
   <label><span>Target audience</span><select value={form.audience} onChange={e=>patch('audience',e.target.value)}><option value="all">All customers</option><option value="vip">VIP customers</option><option value="new">New customers</option><option value="returning">Returning customers</option><option value="birthday">Birthday customers</option><option value="referral">Referral customers</option><option value="tier">Specific VIP tier</option><option value="custom">Custom metric audience</option></select></label>{form.audience==='tier'&&<label><span>VIP tier</span><select required value={form.tierId} onChange={e=>patch('tierId',e.target.value)}><option value="">Choose tier</option>{vipTiers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
   <label><span>Conditions must</span><select value={form.conditionMatch} onChange={e=>patch('conditionMatch',e.target.value)}><option value="all">All match</option><option value="any">Any match</option></select></label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>patch('active',e.target.checked)}/> Active</label><label className="check"><input type="checkbox" checked={form.repeatable} onChange={e=>patch('repeatable',e.target.checked)}/> Repeatable</label>{form.repeatable&&<><label><span>Repeat period</span><select value={form.repeatPeriod} onChange={e=>patch('repeatPeriod',e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label><span>Maximum completions</span><input type="number" min="1" value={form.maxCompletions} onChange={e=>patch('maxCompletions',e.target.value)} placeholder="Unlimited"/></label></>}
   <div className="wide builder-list"><div className="builder-title"><div><h3>Conditions</h3><p>Add as many rules as this mission needs.</p></div><button type="button" onClick={()=>patch('conditions',[...form.conditions,{condition_type:'order_count',target_value:1}])}>+ Condition</button></div>{form.conditions.map((condition,index)=><article key={index}><select value={condition.condition_type} onChange={e=>patchCondition(index,'condition_type',e.target.value)}>{Object.entries(conditionLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>{condition.condition_type==='featured_item'?<select value={condition.menu_item_id||''} onChange={e=>patchCondition(index,'menu_item_id',e.target.value)}><option value="">Choose item</option>{menuItems.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>:condition.condition_type==='distinct_categories'?<select value={condition.category_id||''} onChange={e=>patchCondition(index,'category_id',e.target.value)}><option value="">Any categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:condition.condition_type==='custom'?<input placeholder="Metric key" value={String(condition.config?.metric_key||'')} onChange={e=>patchCondition(index,'config',{metric_key:e.target.value})}/>:<label><span>{valueNeedsMoney(condition.condition_type)?'Target (£)':'Target'}</span><input type="number" min="0.01" step={valueNeedsMoney(condition.condition_type)?'0.01':'1'} value={condition.target_value} onChange={e=>patchCondition(index,'target_value',Number(e.target.value))}/></label>}<button type="button" disabled={form.conditions.length===1} onClick={()=>patch('conditions',form.conditions.filter((_,i)=>i!==index))}>Remove</button></article>)}</div>
   <div className="wide builder-list"><div className="builder-title"><div><h3>Rewards</h3><p>Multiple rewards are issued server-side and audited.</p></div><button type="button" onClick={()=>patch('rewards',[...form.rewards,{reward_type:'loyalty_points',reward_value:100,validity_days:30}])}>+ Reward</button></div>{form.rewards.map((reward,index)=><article key={index}><select value={reward.reward_type} onChange={e=>patchReward(index,'reward_type',e.target.value)}>{Object.entries(rewardLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>{reward.reward_type==='free_item'?<select value={reward.menu_item_id||''} onChange={e=>patchReward(index,'menu_item_id',e.target.value)}><option value="">Choose free item</option>{menuItems.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>:reward.reward_type==='bonus_stamps'?<select value={reward.stamp_program_id||''} onChange={e=>patchReward(index,'stamp_program_id',e.target.value)}><option value="">Choose stamp programme</option>{stampPrograms.filter(s=>s.is_active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>:reward.reward_type==='free_delivery'?<span className="reward-note">Free delivery voucher</span>:<label><span>{rewardNeedsMoney(reward.reward_type)?'Value (£)':reward.reward_type==='percentage_voucher'?'Percent':'Value'}</span><input type="number" min="0" step={rewardNeedsMoney(reward.reward_type)?'0.01':'1'} value={reward.reward_value} onChange={e=>patchReward(index,'reward_value',Number(e.target.value))}/></label>}<label><span>Valid days</span><input type="number" min="1" value={reward.validity_days||''} onChange={e=>patchReward(index,'validity_days',Number(e.target.value)||null)} placeholder="No expiry"/></label><button type="button" disabled={form.rewards.length===1} onClick={()=>patch('rewards',form.rewards.filter((_,i)=>i!==index))}>Remove</button></article>)}</div>
   <div className="wide form-actions"><button type="button" onClick={()=>{setForm(initial());setShowBuilder(false)}}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving…':form.id?'Save changes':'Create challenge'}</button></div>
  </form></section>}
  <section className="challenge-panel"><div className="panel-heading"><div><span className="eyebrow">Campaigns</span><h2>Your challenges</h2></div></div>{data.challenges.length===0?<div className="empty"><h3>No challenges yet</h3><p>Create your first mission to start gamifying repeat visits.</p></div>:<div className="challenge-list">{data.challenges.map(c=><article key={c.id} className={c.platform_disabled_at?'disabled':''}><div className="challenge-badge" style={{background:c.colour}}>{c.icon}</div><div className="challenge-copy"><div><span>{c.is_active?'Active':'Inactive'}{c.platform_disabled_at?' · Platform disabled':''}</span><h3>{c.name}</h3></div><p>{c.description}</p><small>{c.conditions.map(x=>conditionLabels[x.condition_type]).join(' + ')}</small><div className="reward-pills">{c.rewards.map((r,i)=><span key={i}>{displayReward(r)}</span>)}</div></div><div className="challenge-stats"><span><strong>{c.participants}</strong> participants</span><span><strong>{c.completions}</strong> completions</span><span><strong>{money.format(c.revenue_generated_pence/100)}</strong> revenue</span><span><strong>{money.format(c.reward_cost_pence/100)}</strong> cost</span></div><div className="row-actions"><button onClick={()=>editChallenge(c)}>Edit</button><button disabled={busy===c.id} onClick={()=>void clone(c.id)}>Clone</button><button disabled={busy===c.id} onClick={()=>void remove(c.id)}>Delete</button></div></article>)}</div>}</section>
  <section className="challenge-two"><section className="challenge-panel"><div className="panel-heading"><div><span className="eyebrow">Achievements</span><h2>Badge library</h2></div></div><div className="achievement-grid">{data.achievements.map(a=><article key={a.id}><span style={{background:a.colour}}>{a.icon}</span><div><strong>{a.name}</strong><small>{a.description}</small></div><em>{a.is_system_default?'Built in':'Custom'}</em></article>)}</div><form className="achievement-form" onSubmit={createAchievement}><h3>Create custom achievement</h3><input required name="name" placeholder="Achievement name"/><input name="description" placeholder="Description"/><input name="icon" placeholder="★"/><input name="colour" type="color" defaultValue="#171615"/><select name="type"><option value="orders">Orders</option><option value="spend">Spend</option><option value="stamps">Stamps</option><option value="referrals">Referrals</option><option value="distinct_items">Distinct items</option><option value="custom">Custom metric</option></select><input required name="target" type="number" min="1" defaultValue="5"/><button>Create</button></form></section>
   <section className="challenge-panel"><div className="panel-heading"><div><span className="eyebrow">Leaderboard</span><h2>Friendly competition</h2></div></div><div className="leaderboard-settings"><label className="check"><input type="checkbox" checked={data.leaderboard_settings.is_enabled} onChange={e=>void saveLeaderboard(e.target.checked,data.leaderboard_settings.metric,data.leaderboard_settings.max_entries)}/> Enable leaderboard</label><label><span>Metric</span><select value={data.leaderboard_settings.metric} onChange={e=>void saveLeaderboard(data.leaderboard_settings.is_enabled,e.target.value,data.leaderboard_settings.max_entries)}><option value="points">Most points</option><option value="challenges">Challenges completed</option><option value="referrals">Most referrals</option><option value="stamps">Most stamps</option><option value="orders">Most orders</option></select></label></div>{!data.leaderboard_settings.is_enabled?<p className="muted">Leaderboard is optional and off by default.</p>:leaderboard.length===0?<p className="muted">No eligible leaderboard entries yet.</p>:<ol className="leaderboard">{leaderboard.map(row=><li key={row.customer_user_id}><span>{row.display_name}</span><strong>{row.score}</strong></li>)}</ol>}</section></section>
 </main>
}
