import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import MarketingWorkspaceNav from './MarketingWorkspaceNav'
import './MarketingWorkspace.css'

type Customer={customer_user_id:string;first_name?:string;last_name?:string;email?:string;phone?:string;lifetime_spend_pence:number;total_orders:number;average_order_value_pence:number;last_order_date:string;loyalty_points:number;vip_tier_name?:string;store_credit_pence:number;marketing_email_allowed:boolean}
type Segment={key:string;name:string}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
export default function MarketingCRM(){
 const[restaurantId,setRestaurantId]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[total,setTotal]=useState(0),[segments,setSegments]=useState<Segment[]>([]),[segment,setSegment]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{void loadWorkspace()},[])
 useEffect(()=>{if(restaurantId)void loadCustomers()},[restaurantId,segment])
 async function loadWorkspace(){setLoading(true);const{data,error}=await supabase.rpc('get_restaurant_marketing_workspace');if(error){setError(error.message);setLoading(false);return}setRestaurantId(data.restaurant_id);setSegments([{key:'all',name:'All customers'},...(data.segments?.built_in||[])]);setLoading(false)}
 async function loadCustomers(){setLoading(true);setError('');const{data,error}=await supabase.rpc('get_restaurant_crm_customers',{p_restaurant_id:restaurantId,p_segment_key:segment,p_custom_segment_id:null,p_search:search||null,p_limit:250,p_offset:0});if(error)setError(error.message);else{setCustomers(data?.customers||[]);setTotal(data?.total||0)}setLoading(false)}
 const stats=useMemo(()=>({spend:customers.reduce((s,c)=>s+(c.lifetime_spend_pence||0),0),orders:customers.reduce((s,c)=>s+(c.total_orders||0),0),vip:customers.filter(c=>c.vip_tier_name).length}),[customers])
 return <main className="mcrm-page"><MarketingWorkspaceNav/><div className="mcrm-wrap"><header className="mcrm-head"><div><span className="eyebrow">Restaurant CRM</span><h1>Customers</h1><p>Live customer value, loyalty and engagement data derived from orders, rewards, wallet, stamps, referrals, VIP and challenges.</p></div><div className="mcrm-actions"><Link className="mcrm-button secondary" to="/marketing/segments">Manage segments</Link><Link className="mcrm-button" to="/marketing/campaigns">Create campaign</Link></div></header>{error&&<div className="mcrm-alert error">{error}</div>}<section className="mcrm-grid"><article className="mcrm-card mcrm-stat"><span>Customers</span><strong>{total}</strong></article><article className="mcrm-card mcrm-stat"><span>Visible spend</span><strong>{money.format(stats.spend/100)}</strong></article><article className="mcrm-card mcrm-stat"><span>Orders</span><strong>{stats.orders}</strong></article><article className="mcrm-card mcrm-stat"><span>VIP members</span><strong>{stats.vip}</strong></article></section><section className="mcrm-card"><div className="mcrm-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void loadCustomers()}} placeholder="Search name, email or phone"/><select value={segment} onChange={e=>setSegment(e.target.value)}>{segments.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select><button className="mcrm-button" onClick={()=>void loadCustomers()}>Search</button></div>{loading?<div className="mcrm-empty">Loading customers…</div>:customers.length===0?<div className="mcrm-empty">No customers match this segment.</div>:<div className="mcrm-table-wrap"><table className="mcrm-table"><thead><tr><th>Customer</th><th>Orders</th><th>Lifetime spend</th><th>AOV</th><th>Loyalty</th><th>VIP</th><th>Last order</th><th>Marketing</th></tr></thead><tbody>{customers.map(c=><tr key={c.customer_user_id}><td><Link to={`/marketing/crm/${c.customer_user_id}`}>{[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email||'Customer'}</Link><div className="mcrm-muted">{c.email}</div>{c.phone&&<div className="mcrm-muted">{c.phone}</div>}</td><td>{c.total_orders}</td><td>{money.format((c.lifetime_spend_pence||0)/100)}</td><td>{money.format((c.average_order_value_pence||0)/100)}</td><td>{c.loyalty_points||0} pts<br/><small>{money.format((c.store_credit_pence||0)/100)} credit</small></td><td>{c.vip_tier_name||'—'}</td><td>{c.last_order_date?new Date(c.last_order_date).toLocaleDateString('en-GB'):'—'}</td><td><span className={`mcrm-pill ${c.marketing_email_allowed?'good':'warn'}`}>{c.marketing_email_allowed?'Email allowed':'Email off'}</span></td></tr>)}</tbody></table></div>}</section></div></main>
}
