import { FormEvent,useEffect,useState } from 'react'
import { supabase } from '../lib/supabase'
import MarketingWorkspaceNav from './MarketingWorkspaceNav'
import './MarketingWorkspace.css'

type Template={id:string;name:string;subject?:string;preview_text?:string;html_content?:string;text_content?:string;cta_label?:string;cta_url?:string;image_url?:string}
const blank={id:'',name:'',subject:'',preview_text:'',html_content:'',text_content:'',cta_label:'',cta_url:'',image_url:''}
export default function MarketingTemplates(){const[templates,setTemplates]=useState<Template[]>([]),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){const{data,error}=await supabase.rpc('get_restaurant_marketing_workspace');if(error)setError(error.message);else setTemplates(data.templates||[])}
 function edit(t:Template){setForm({id:t.id,name:t.name,subject:t.subject||'',preview_text:t.preview_text||'',html_content:t.html_content||'',text_content:t.text_content||'',cta_label:t.cta_label||'',cta_url:t.cta_url||'',image_url:t.image_url||''})}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setNotice('');const payload={...form,id:form.id||null,html_content:form.html_content||`<p>${form.text_content.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</p>`,branding:{platform:'ordered.food'}};const{error}=await supabase.rpc('save_restaurant_marketing_template',{p_template:payload});if(error)setError(error.message);else{setNotice('Template saved.');setForm(blank);await load()}setSaving(false)}
 return <main className="mcrm-page"><MarketingWorkspaceNav/><div className="mcrm-wrap"><header className="mcrm-head"><div><span className="eyebrow">Reusable content</span><h1>Templates</h1><p>Create reusable email and in-app content for campaigns and lifecycle automation.</p></div></header>{error&&<div className="mcrm-alert error">{error}</div>}{notice&&<div className="mcrm-alert success">{notice}</div>}<section className="mcrm-card"><h2>{form.id?'Edit template':'New template'}</h2><form className="mcrm-form" onSubmit={save}><label>Name<input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label>Subject<input value={form.subject} onChange={e=>setForm(v=>({...v,subject:e.target.value}))}/></label><label className="wide">Preview text<input value={form.preview_text} onChange={e=>setForm(v=>({...v,preview_text:e.target.value}))}/></label><label className="wide">Plain-text message<textarea rows={5} value={form.text_content} onChange={e=>setForm(v=>({...v,text_content:e.target.value}))}/></label><label className="wide">HTML message<textarea rows={7} value={form.html_content} onChange={e=>setForm(v=>({...v,html_content:e.target.value}))} placeholder="Optional. Leave blank to generate HTML from the plain-text message."/></label><label>CTA label<input value={form.cta_label} onChange={e=>setForm(v=>({...v,cta_label:e.target.value}))}/></label><label>CTA URL<input value={form.cta_url} onChange={e=>setForm(v=>({...v,cta_url:e.target.value}))}/></label><label className="wide">Image URL<input value={form.image_url} onChange={e=>setForm(v=>({...v,image_url:e.target.value}))}/></label><div className="wide mcrm-actions"><button className="mcrm-button" disabled={saving}>{saving?'Saving…':'Save template'}</button>{form.id&&<button type="button" className="mcrm-button secondary" onClick={()=>setForm(blank)}>Cancel edit</button>}</div></form></section><section className="mcrm-card"><h2>Saved templates</h2>{templates.length?<div className="mcrm-table-wrap"><table className="mcrm-table"><thead><tr><th>Name</th><th>Subject</th><th>CTA</th><th></th></tr></thead><tbody>{templates.map(t=><tr key={t.id}><td><strong>{t.name}</strong></td><td>{t.subject||'—'}</td><td>{t.cta_label||'—'}</td><td><button className="mcrm-button secondary" onClick={()=>edit(t)}>Edit</button></td></tr>)}</tbody></table></div>:<div className="mcrm-empty">No templates yet.</div>}</section></div></main>}
