import { FormEvent,useEffect,useState } from 'react'
import { supabase } from '../lib/supabase'
import MarketingWorkspaceNav from './MarketingWorkspaceNav'
import './MarketingWorkspace.css'

type Settings={timezone:string;quiet_hours_start:string;quiet_hours_end:string;high_spender_pence:number;low_spender_pence:number;referral_champion_threshold:number;max_email_sends_per_day:number;max_notification_sends_per_day:number;max_sends_per_customer_per_day:number;rate_limit_per_minute:number;attribution_window_days:number}
const defaults:Settings={timezone:'Europe/London',quiet_hours_start:'21:00',quiet_hours_end:'08:00',high_spender_pence:10000,low_spender_pence:3000,referral_champion_threshold:3,max_email_sends_per_day:5000,max_notification_sends_per_day:10000,max_sends_per_customer_per_day:3,rate_limit_per_minute:250,attribution_window_days:7}
export default function MarketingSettings(){const[form,setForm]=useState(defaults),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){const{data,error}=await supabase.rpc('get_restaurant_marketing_workspace');if(error)setError(error.message);else if(data.settings)setForm({...defaults,...data.settings,quiet_hours_start:String(data.settings.quiet_hours_start||'21:00').slice(0,5),quiet_hours_end:String(data.settings.quiet_hours_end||'08:00').slice(0,5)})}
 function set<K extends keyof Settings>(key:K,value:Settings[K]){setForm(v=>({...v,[key]:value}))}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setNotice('');const{error}=await supabase.rpc('update_restaurant_marketing_settings',{p_settings:form});if(error)setError(error.message);else setNotice('Marketing settings saved. Scheduling, segmentation and send limits now use these values.');setSaving(false)}
 return <main className="mcrm-page"><MarketingWorkspaceNav/><div className="mcrm-wrap"><header className="mcrm-head"><div><span className="eyebrow">Controls & compliance</span><h1>Marketing settings</h1><p>Set local-time quiet hours, CRM thresholds, attribution and restaurant-level send limits.</p></div></header>{error&&<div className="mcrm-alert error">{error}</div>}{notice&&<div className="mcrm-alert success">{notice}</div>}<section className="mcrm-card"><form className="mcrm-form" onSubmit={save}><label>Timezone<input required value={form.timezone} onChange={e=>set('timezone',e.target.value)} placeholder="Europe/London"/></label><label>Attribution window (days)<input type="number" min="1" max="90" value={form.attribution_window_days} onChange={e=>set('attribution_window_days',Number(e.target.value))}/></label><label>Quiet hours start<input type="time" value={form.quiet_hours_start} onChange={e=>set('quiet_hours_start',e.target.value)}/></label><label>Quiet hours end<input type="time" value={form.quiet_hours_end} onChange={e=>set('quiet_hours_end',e.target.value)}/></label><label>High spender threshold (£)<input type="number" min="0" step="1" value={form.high_spender_pence/100} onChange={e=>set('high_spender_pence',Math.round(Number(e.target.value)*100))}/></label><label>Low spender threshold (£)<input type="number" min="0" step="1" value={form.low_spender_pence/100} onChange={e=>set('low_spender_pence',Math.round(Number(e.target.value)*100))}/></label><label>Referral champion threshold<input type="number" min="1" value={form.referral_champion_threshold} onChange={e=>set('referral_champion_threshold',Number(e.target.value))}/></label><label>Email sends / day<input type="number" min="1" value={form.max_email_sends_per_day} onChange={e=>set('max_email_sends_per_day',Number(e.target.value))}/></label><label>In-app sends / day<input type="number" min="1" value={form.max_notification_sends_per_day} onChange={e=>set('max_notification_sends_per_day',Number(e.target.value))}/></label><label>Sends / customer / day<input type="number" min="1" max="100" value={form.max_sends_per_customer_per_day} onChange={e=>set('max_sends_per_customer_per_day',Number(e.target.value))}/></label><label>Rate limit / minute<input type="number" min="1" value={form.rate_limit_per_minute} onChange={e=>set('rate_limit_per_minute',Number(e.target.value))}/></label><div className="wide"><button className="mcrm-button" disabled={saving}>{saving?'Saving…':'Save settings'}</button></div></form></section></div></main>}
