import { FormEvent, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './Milestones.css'

type RewardType='voucher'|'percentage_discount'|'fixed_discount'|'free_item'|'free_delivery'|'loyalty_points'|'wallet_credit'
type Birthday={id?:string;is_enabled?:boolean;disabled_by_platform?:boolean;platform_disable_reason?:string|null;reward_type?:RewardType;reward_value?:number;reward_menu_item_id?:string|null;validity_days?:number;minimum_spend_pence?:number;fulfilment_methods?:string[];campaign_message?:string}
type Program={id:string;name:string;milestone_type:'order_count'|'lifetime_spend';threshold_value:number;is_enabled:boolean;is_system_default:boolean;disabled_by_platform:boolean;platform_disable_reason:string|null;reward_type:RewardType;reward_value:number;reward_menu_item_id:string|null;validity_days:number;minimum_spend_pence:number;fulfilment_methods:string[];campaign_message:string}
type Settings={sells_alcohol:boolean;birthday_program:Birthday;milestones:Program[];menu_items:{id:string;name:string}[]}
type Summary={birthdays_this_month:number;rewards_issued:number;rewards_redeemed:number;birthday_redemption_rate:number;milestone_completion:number;repeat_visits_generated:number;revenue_generated_pence:number;campaign_cost_pence:number}
type Dashboard={summary:Summary;recent_customers:Array<{issuance_id:string;source_type:string;program_name:string|null;status:string;issued_at:string|null;redeemed_at:string|null;revenue_generated_pence:number}>}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())
const rewardOptions:[RewardType,string][]=[['voucher','Voucher'],['percentage_discount','Percentage discount'],['fixed_discount','Fixed discount'],['free_item','Free item'],['free_delivery','Free delivery'],['loyalty_points','Loyalty points'],['wallet_credit','Wallet credit']]
const valueInput=(type:RewardType,value:number|undefined)=>type==='percentage_discount'?String((value||0)/100):type==='fixed_discount'||type==='wallet_credit'||type==='voucher'?String((value||0)/100):String(value||0)
const valueParam=(type:RewardType,value:string)=>type==='percentage_discount'?Math.round(Number(value||0)*100):type==='fixed_discount'||type==='wallet_credit'||type==='voucher'?Math.round(Number(value||0)*100):type==='loyalty_points'?Math.round(Number(value||0)):0
export default function Milestones(){const[settings,setSettings]=useState<Settings|null>(null);const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');const[saving,setSaving]=useState('');const[birthday,setBirthday]=useState({enabled:false,type:'voucher' as RewardType,value:'5',menuItem:'',validity:'14',minimum:'0',delivery:true,collection:true,message:'Happy Birthday! Enjoy a reward from us.'});
async function load(){setLoading(true);setError('');const[s,d]=await Promise.all([supabase.rpc('get_restaurant_birthday_milestone_settings'),supabase.rpc('get_restaurant_milestone_dashboard')]);if(s.error)setError(s.error.message);else{const next=s.data as Settings;setSettings(next);const b=next.birthday_program||{};setBirthday({enabled:Boolean(b.is_enabled),type:b.reward_type||'voucher',value:valueInput(b.reward_type||'voucher',b.reward_value),menuItem:b.reward_menu_item_id||'',validity:String(b.validity_days||14),minimum:String((b.minimum_spend_pence||0)/100),delivery:(b.fulfilment_methods||['delivery','collection']).includes('delivery'),collection:(b.fulfilment_methods||['delivery','collection']).includes('collection'),message:b.campaign_message||'Happy Birthday! Enjoy a reward from us.'})}if(d.error)setError(d.error.message);else setDash(d.data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
async function saveBirthday(e:FormEvent){e.preventDefault();if(!birthday.delivery&&!birthday.collection){setError('Choose delivery, collection or both.');return}setSaving('birthday');setError('');setMessage('');const{error:rpcError}=await supabase.rpc('save_restaurant_birthday_program',{p_is_enabled:birthday.enabled,p_reward_type:birthday.type,p_reward_value:valueParam(birthday.type,birthday.value),p_reward_menu_item_id:birthday.menuItem||null,p_validity_days:Math.max(1,Number(birthday.validity)||14),p_minimum_spend_pence:Math.max(0,Math.round(Number(birthday.minimum||0)*100)),p_fulfilment_methods:[birthday.delivery&&'delivery',birthday.collection&&'collection'].filter(Boolean),p_campaign_message:birthday.message});if(rpcError)setError(rpcError.message);else{setMessage('Birthday programme saved.');await load()}setSaving('')}
async function saveAlcohol(value:boolean){setSaving('alcohol');const{error:rpcError}=await supabase.rpc('save_restaurant_alcohol_setting',{p_sells_alcohol:value});if(rpcError)setError(rpcError.message);else await load();setSaving('')}
async function toggleMilestone(p:Program){setSaving(p.id);const{error:rpcError}=await supabase.rpc('save_restaurant_milestone_program',{p_program_id:p.id,p_name:p.name,p_milestone_type:p.milestone_type,p_threshold_value:p.threshold_value,p_is_enabled:!p.is_enabled,p_reward_type:p.reward_type,p_reward_value:p.reward_value,p_reward_menu_item_id:p.reward_menu_item_id,p_validity_days:p.validity_days,p_minimum_spend_pence:p.minimum_spend_pence,p_fulfilment_methods:p.fulfilment_methods,p_campaign_message:p.campaign_message});if(rpcError)setError(rpcError.message);else await load();setSaving('')}
async function addCustom(){const name=window.prompt('Milestone name','VIP 75th order');if(!name)return;const type=(window.prompt('Type: order_count or lifetime_spend','order_count')||'') as Program['milestone_type'];if(!['order_count','lifetime_spend'].includes(type))return;const threshold=Number(window.prompt(type==='order_count'?'Order count':'Lifetime spend in £',type==='order_count'?'75':'750'));if(!threshold)return;setSaving('new');const{error:rpcError}=await supabase.rpc('save_restaurant_milestone_program',{p_program_id:null,p_name:name,p_milestone_type:type,p_threshold_value:type==='lifetime_spend'?Math.round(threshold*100):Math.round(threshold),p_is_enabled:false,p_reward_type:'voucher',p_reward_value:500,p_reward_menu_item_id:null,p_validity_days:30,p_minimum_spend_pence:0,p_fulfilment_methods:['delivery','collection'],p_campaign_message:'You reached a new milestone. Your reward is ready!'});if(rpcError)setError(rpcError.message);else await load();setSaving('')}
if(loading)return <main className="restaurant-milestones">Loading milestone campaigns…</main>;const s=dash?.summary||{birthdays_this_month:0,rewards_issued:0,rewards_redeemed:0,birthday_redemption_rate:0,milestone_completion:0,repeat_visits_generated:0,revenue_generated_pence:0,campaign_cost_pence:0};
return <main className="restaurant-milestones"><header><div><span>Marketing automation</span><h1>Birthdays & milestones</h1><p>Turn important customer moments into automatic, audited rewards.</p></div><nav><Link to="/marketing">Marketing</Link><button type="button" onClick={()=>void load()}>Refresh</button></nav></header>{error&&<div className="campaign-alert campaign-alert--error">{error}</div>}{message&&<div className="campaign-alert campaign-alert--success">{message}</div>}
<section className="campaign-metrics"><article><span>Birthdays this month</span><strong>{s.birthdays_this_month}</strong></article><article><span>Rewards issued</span><strong>{s.rewards_issued}</strong></article><article><span>Birthday redemption</span><strong>{Number(s.birthday_redemption_rate).toFixed(1)}%</strong></article><article><span>Repeat visits</span><strong>{s.repeat_visits_generated}</strong></article><article><span>Revenue generated</span><strong>{money.format(s.revenue_generated_pence/100)}</strong></article><article><span>Campaign cost</span><strong>{money.format(s.campaign_cost_pence/100)}</strong></article></section>
<section className="campaign-grid"><form className="campaign-card" onSubmit={saveBirthday}><div className="campaign-card-heading"><div><span>Birthday programme</span><h2>Automatic birthday reward</h2></div><label className="campaign-toggle"><input type="checkbox" checked={birthday.enabled} disabled={Boolean(settings?.birthday_program.disabled_by_platform)} onChange={e=>setBirthday({...birthday,enabled:e.target.checked})}/>{birthday.enabled?'Enabled':'Disabled'}</label></div>{settings?.birthday_program.disabled_by_platform&&<p className="campaign-lock">Disabled by ordered.food: {settings.birthday_program.platform_disable_reason||'Contact support.'}</p>}<div className="campaign-form-grid"><RewardFields type={birthday.type} value={birthday.value} menuItem={birthday.menuItem} menuItems={settings?.menu_items||[]} onType={v=>setBirthday({...birthday,type:v})} onValue={v=>setBirthday({...birthday,value:v})} onMenu={v=>setBirthday({...birthday,menuItem:v})}/><label>Valid for days<input type="number" min="1" max="365" value={birthday.validity} onChange={e=>setBirthday({...birthday,validity:e.target.value})}/></label><label>Minimum spend (£)<input type="number" min="0" step=".01" value={birthday.minimum} onChange={e=>setBirthday({...birthday,minimum:e.target.value})}/></label><fieldset><legend>Fulfilment</legend><label><input type="checkbox" checked={birthday.delivery} onChange={e=>setBirthday({...birthday,delivery:e.target.checked})}/> Delivery</label><label><input type="checkbox" checked={birthday.collection} onChange={e=>setBirthday({...birthday,collection:e.target.checked})}/> Collection</label></fieldset><label className="wide">Campaign message<textarea rows={3} maxLength={500} value={birthday.message} onChange={e=>setBirthday({...birthday,message:e.target.value})}/></label></div><button className="campaign-primary" disabled={saving==='birthday'||Boolean(settings?.birthday_program.disabled_by_platform)}>{saving==='birthday'?'Saving…':'Save birthday programme'}</button></form>
<aside className="campaign-card"><div className="campaign-card-heading"><div><span>Age assurance</span><h2>Alcohol orders</h2></div></div><p>If enabled, checkout requires a signed-in customer with a verified-on-file date of birth showing they are 18+.</p><label className="campaign-toggle campaign-toggle--large"><input type="checkbox" checked={Boolean(settings?.sells_alcohol)} disabled={saving==='alcohol'} onChange={e=>void saveAlcohol(e.target.checked)}/> Restaurant sells alcohol</label><small>Date of birth is private. Restaurant dashboards never expose the customer's DOB.</small></aside></section>
<section className="campaign-card campaign-programmes"><div className="campaign-card-heading"><div><span>Customer milestones</span><h2>Reward configuration</h2></div><button className="campaign-secondary" type="button" onClick={()=>void addCustom()} disabled={saving==='new'}>+ Custom milestone</button></div><div className="campaign-table"><table><thead><tr><th>Milestone</th><th>Trigger</th><th>Reward</th><th>Status</th><th>Action</th></tr></thead><tbody>{settings?.milestones.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.is_system_default?'Built-in':'Custom'}</small></td><td>{p.milestone_type==='order_count'?`${p.threshold_value} orders`:money.format(p.threshold_value/100)}</td><td>{text(p.reward_type)}{p.reward_value?` · ${p.reward_type==='percentage_discount'?`${p.reward_value/100}%`:p.reward_type==='loyalty_points'?p.reward_value:money.format(p.reward_value/100)}`:''}</td><td>{p.disabled_by_platform?'Platform disabled':p.is_enabled?'Enabled':'Paused'}</td><td><button className="campaign-secondary" type="button" disabled={saving===p.id||p.disabled_by_platform} onClick={()=>void toggleMilestone(p)}>{p.is_enabled?'Pause':'Enable'}</button></td></tr>)}</tbody></table></div></section>
<section className="campaign-card campaign-programmes"><div className="campaign-card-heading"><div><span>Campaign performance</span><h2>Customers reaching milestones</h2></div><small>{s.milestone_completion} milestone completions · {s.rewards_redeemed} redemptions</small></div><div className="campaign-table"><table><thead><tr><th>Type</th><th>Milestone</th><th>Status</th><th>Issued</th><th>Revenue generated</th></tr></thead><tbody>{dash?.recent_customers.length?dash.recent_customers.map(row=><tr key={row.issuance_id}><td>{text(row.source_type)}</td><td>{row.program_name||'Birthday reward'}</td><td>{text(row.status)}</td><td>{row.issued_at?new Date(row.issued_at).toLocaleDateString('en-GB'):'Pending'}</td><td>{money.format(row.revenue_generated_pence/100)}</td></tr>):<tr><td colSpan={5}>No rewards issued yet.</td></tr>}</tbody></table></div></section></main>}
function RewardFields({type,value,menuItem,menuItems,onType,onValue,onMenu}:{type:RewardType;value:string;menuItem:string;menuItems:{id:string;name:string}[];onType:(v:RewardType)=>void;onValue:(v:string)=>void;onMenu:(v:string)=>void}){return <fieldset><legend>Reward</legend><label>Type<select value={type} onChange={e=>onType(e.target.value as RewardType)}>{rewardOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{!['free_item','free_delivery'].includes(type)&&<label>{type==='percentage_discount'?'Percentage (%)':type==='loyalty_points'?'Points':'Value (£)'}<input type="number" min="0.01" step={type==='loyalty_points'?'1':'.01'} value={value} onChange={e=>onValue(e.target.value)}/></label>}{type==='free_item'&&<label>Free item<select value={menuItem} onChange={e=>onMenu(e.target.value)} required><option value="">Choose item</option>{menuItems.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}</fieldset>}
