import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './VipProgramme.css'

type Rule={id?:string;metric_type:string;custom_metric_key?:string|null;threshold_value:number}
type Benefit={id?:string;benefit_type:string;value?:number|null;menu_item_id?:string|null;reward_catalogue_id?:string|null;metadata?:Record<string,unknown>;menu_item_name?:string|null;reward_name?:string|null}
type Tier={id:string;name:string;colour:string;icon:string;description:string|null;priority:number;qualification_match:'all'|'any';is_active:boolean;rules:Rule[];benefits:Benefit[]}
type Dashboard={program:{is_enabled?:boolean;qualification_window?:'lifetime'|'rolling';rolling_days?:number;allow_downgrades?:boolean;disabled_by_platform?:boolean;platform_disable_reason?:string|null};tiers:Tier[];menu_items:Array<{id:string;name:string}>;catalogue_rewards:Array<{id:string;name:string;reward_type:string}>;stamp_programs:Array<{id:string;name:string;is_active:boolean}>;summary:{vip_customers:number;revenue_90d_pence:number;average_spend_pence:number;upgrades_30d:number;downgrades_30d:number;upgrade_rate:number;downgrade_rate:number;reward_events_90d:number;open_fraud_flags:number};tier_analytics:Array<{tier_id:string;tier_name:string;colour:string;customers:number;revenue_pence:number;orders:number;average_spend_pence:number;visit_frequency_90d:number;retention_percent:number;reward_usage:number}>;top_customers:Array<{customer_user_id:string;customer_name:string;customer_email:string;tier_name:string;tier_colour:string;lifetime_value_pence:number;orders_completed:number}>}
type TierDraft={id:string|null;name:string;colour:string;icon:string;description:string;priority:string;qualification_match:'all'|'any';is_active:boolean;rules:Rule[];benefits:Benefit[]}

const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
const metricLabels:Record<string,string>={lifetime_spend:'Lifetime spend',orders_completed:'Completed orders',loyalty_points:'Loyalty points earned',stamp_cards_completed:'Stamp cards completed',referral_count:'Qualified referrals',custom_metric:'Custom restaurant metric'}
const benefitLabels:Record<string,string>={bonus_loyalty_points:'Bonus loyalty points per order',bonus_stamps:'Bonus stamps per order',percentage_discount:'Percentage discount',fixed_discount:'Fixed discount',free_delivery:'Free delivery',free_menu_item:'Free menu item',birthday_bonus_multiplier:'Birthday bonus multiplier',referral_multiplier:'Referral multiplier',exclusive_reward:'Exclusive reward',early_access_promotions:'Early access promotions',priority_customer_support:'Priority customer support'}
const numericBenefits=new Set(['bonus_loyalty_points','bonus_stamps','percentage_discount','fixed_discount','birthday_bonus_multiplier','referral_multiplier'])
const blankTier=():TierDraft=>({id:null,name:'',colour:'#7c3aed',icon:'star',description:'',priority:'10',qualification_match:'all',is_active:true,rules:[{metric_type:'lifetime_spend',threshold_value:10000}],benefits:[]})
const toDraft=(t:Tier):TierDraft=>({id:t.id,name:t.name,colour:t.colour,icon:t.icon,description:t.description||'',priority:String(t.priority),qualification_match:t.qualification_match,is_active:t.is_active,rules:t.rules.map(r=>({...r})),benefits:t.benefits.map(b=>({...b,value:b.benefit_type==='percentage_discount'||b.benefit_type==='fixed_discount'?Number(b.value||0)/100:['birthday_bonus_multiplier','referral_multiplier'].includes(b.benefit_type)?Number(b.value||10000)/10000:b.value??null,metadata:{...(b.metadata||{})}}))})
function benefitValueLabel(b:Benefit){if(b.benefit_type==='percentage_discount')return `${Number(b.value||0)/100}%`;if(b.benefit_type==='fixed_discount')return money.format(Number(b.value||0)/100);if(['birthday_bonus_multiplier','referral_multiplier'].includes(b.benefit_type))return `${Number(b.value||10000)/10000}×`;if(b.benefit_type==='free_menu_item')return b.menu_item_name||'Menu item';if(b.benefit_type==='exclusive_reward')return b.reward_name||'Reward';if(numericBenefits.has(b.benefit_type))return String(b.value||0);return 'Included'}

export default function VipProgramme(){
 const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[saving,setSaving]=useState(false);const[draft,setDraft]=useState<TierDraft|null>(null);const[metricCustomer,setMetricCustomer]=useState('');const[metricKey,setMetricKey]=useState('visits_score');const[metricValue,setMetricValue]=useState('0')
 const load=useCallback(async()=>{setError('');const{data:result,error:rpcError}=await supabase.rpc('get_restaurant_vip_dashboard');if(rpcError)setError(rpcError.message);else setData(result as Dashboard);setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const summary=data?.summary||{vip_customers:0,revenue_90d_pence:0,average_spend_pence:0,upgrades_30d:0,downgrades_30d:0,upgrade_rate:0,downgrade_rate:0,reward_events_90d:0,open_fraud_flags:0}
 const activeProgram=Boolean(data?.program?.is_enabled)&&!data?.program?.disabled_by_platform
 const tierNames=useMemo(()=>new Set((data?.tiers||[]).map(t=>t.name.toLowerCase())),[data])
 async function saveProgram(next?:boolean){if(!data)return;setSaving(true);setError('');const{error:rpcError}=await supabase.rpc('save_restaurant_vip_program',{p_is_enabled:next??Boolean(data.program.is_enabled),p_qualification_window:data.program.qualification_window||'lifetime',p_rolling_days:Number(data.program.rolling_days||365),p_allow_downgrades:Boolean(data.program.allow_downgrades)});if(rpcError)setError(rpcError.message);else{setNotice('VIP programme settings saved.');await load()}setSaving(false)}
 function patchProgram(values:Partial<Dashboard['program']>){setData(current=>current?{...current,program:{...current.program,...values}}:current)}
 function patchRule(index:number,patch:Partial<Rule>){setDraft(current=>current?{...current,rules:current.rules.map((r,i)=>i===index?{...r,...patch}:r)}:current)}
 function patchBenefit(index:number,patch:Partial<Benefit>){setDraft(current=>current?{...current,benefits:current.benefits.map((b,i)=>i===index?{...b,...patch}:b)}:current)}
 async function saveTier(event:FormEvent){event.preventDefault();if(!draft)return;setError('');setNotice('');if(!draft.id&&tierNames.has(draft.name.trim().toLowerCase())){setError('A tier with this name already exists.');return}setSaving(true);const rules=draft.rules.map(r=>({...r,threshold_value:Number(r.threshold_value||0),custom_metric_key:r.metric_type==='custom_metric'?(r.custom_metric_key||'').trim().toLowerCase():null}));const benefits=draft.benefits.map(b=>{let value=b.value??null;if(b.benefit_type==='percentage_discount')value=Math.round(Number(value||0)*100);if(b.benefit_type==='fixed_discount')value=Math.round(Number(value||0)*100);if(['birthday_bonus_multiplier','referral_multiplier'].includes(b.benefit_type))value=Math.round(Number(value||1)*10000);return{benefit_type:b.benefit_type,value,menu_item_id:b.menu_item_id||null,reward_catalogue_id:b.reward_catalogue_id||null,metadata:b.metadata||{},is_active:true}});const{error:rpcError}=await supabase.rpc('save_restaurant_vip_tier',{p_tier_id:draft.id,p_name:draft.name.trim(),p_colour:draft.colour,p_icon:draft.icon.trim()||'star',p_description:draft.description.trim()||null,p_priority:Number(draft.priority),p_qualification_match:draft.qualification_match,p_is_active:draft.is_active,p_rules:rules,p_benefits:benefits});if(rpcError)setError(rpcError.message);else{setNotice(draft.id?'Tier updated.':'Tier created.');setDraft(null);await load()}setSaving(false)}
 async function archiveTier(t:Tier){if(!window.confirm(`Archive ${t.name}? Existing history is retained and customers will be recalculated.`))return;setSaving(true);const{error:rpcError}=await supabase.rpc('archive_restaurant_vip_tier',{p_tier_id:t.id});if(rpcError)setError(rpcError.message);else{await supabase.rpc('recalculate_restaurant_vip_memberships',{p_limit:1000});setNotice('Tier archived and memberships recalculated.');await load()}setSaving(false)}
 async function recalculate(){setSaving(true);const{data:result,error:rpcError}=await supabase.rpc('recalculate_restaurant_vip_memberships',{p_limit:1000});if(rpcError)setError(rpcError.message);else{const r=result as {processed:number;changed:number};setNotice(`Recalculated ${r.processed} customers; ${r.changed} tier changes.`);await load()}setSaving(false)}
 async function saveCustomMetric(event:FormEvent){event.preventDefault();if(!metricCustomer)return;setSaving(true);const{error:rpcError}=await supabase.rpc('set_customer_vip_custom_metric',{p_customer_user_id:metricCustomer,p_metric_key:metricKey.trim().toLowerCase(),p_metric_value:Number(metricValue),p_note:'Restaurant VIP dashboard update'});if(rpcError)setError(rpcError.message);else{setNotice('Custom customer metric saved and tier recalculated.');await load()}setSaving(false)}
 if(loading)return <main className="vip-admin-shell"><p>Loading VIP programme…</p></main>
 return <main className="vip-admin-shell">
  <header className="vip-admin-header"><div><Link className="brand" to="/dashboard">ordered.food</Link><p>Marketing → VIP Programme</p></div><div><Link className="vip-secondary" to="/marketing">Marketing</Link><button className="vip-secondary" type="button" onClick={()=>void recalculate()} disabled={saving}>Recalculate memberships</button></div></header>
  <section className="vip-admin-hero"><div><span>Retention engine</span><h1>VIP Programme</h1><p>Create unlimited tiers, combine qualification rules, and automatically unlock checkout, loyalty, stamp, birthday, referral and exclusive benefits.</p></div><label className="vip-switch"><input type="checkbox" checked={Boolean(data?.program?.is_enabled)} disabled={Boolean(data?.program?.disabled_by_platform)||saving} onChange={e=>void saveProgram(e.target.checked)}/><span>{activeProgram?'Live':'Paused'}</span></label></section>
  {data?.program?.disabled_by_platform&&<div className="vip-alert vip-alert-error">Platform admin has disabled this programme. {data.program.platform_disable_reason||''}</div>}{error&&<div className="vip-alert vip-alert-error">{error}</div>}{notice&&<div className="vip-alert vip-alert-success">{notice}</div>}
  <section className="vip-metrics"><article><span>VIP customers</span><strong>{summary.vip_customers}</strong></article><article><span>VIP revenue · 90d</span><strong>{money.format(summary.revenue_90d_pence/100)}</strong></article><article><span>Average spend</span><strong>{money.format(summary.average_spend_pence/100)}</strong></article><article><span>Upgrade rate · 30d</span><strong>{Number(summary.upgrade_rate).toFixed(1)}%</strong></article><article><span>Downgrade rate · 30d</span><strong>{Number(summary.downgrade_rate).toFixed(1)}%</strong></article><article><span>Reward usage · 90d</span><strong>{summary.reward_events_90d}</strong></article></section>
  <section className="vip-panel"><div className="vip-panel-head"><div><span>Qualification policy</span><h2>How membership is measured</h2></div><button className="vip-primary" type="button" disabled={saving} onClick={()=>void saveProgram()}>Save policy</button></div><div className="vip-policy-grid"><label>Qualification window<select value={data?.program?.qualification_window||'lifetime'} onChange={e=>patchProgram({qualification_window:e.target.value as 'lifetime'|'rolling'})}><option value="lifetime">Lifetime</option><option value="rolling">Rolling period</option></select></label>{data?.program?.qualification_window==='rolling'&&<label>Rolling days<input type="number" min="30" max="3650" value={data.program.rolling_days||365} onChange={e=>patchProgram({rolling_days:Number(e.target.value)})}/></label>}<label className="vip-check"><input type="checkbox" checked={Boolean(data?.program?.allow_downgrades)} disabled={data?.program?.qualification_window!=='rolling'} onChange={e=>patchProgram({allow_downgrades:e.target.checked})}/> Allow automatic downgrades when rolling requirements are no longer met</label></div></section>
  <section className="vip-panel"><div className="vip-panel-head"><div><span>Tier builder</span><h2>Tiers & benefits</h2></div><button className="vip-primary" type="button" onClick={()=>setDraft(blankTier())}>New tier</button></div>{(data?.tiers||[]).length===0?<div className="vip-empty">No tiers yet. Create your first level to start qualifying customers.</div>:<div className="vip-tier-list">{data?.tiers.map(t=><article key={t.id} style={{borderColor:t.colour}}><div className="vip-tier-title"><span className="vip-badge" style={{background:t.colour}}>{t.icon} {t.name}</span><small>Priority {t.priority} · {t.is_active?'Active':'Inactive'}</small></div><p>{t.description||'No description'}</p><div className="vip-chip-row">{t.rules.map(r=><span key={r.id||`${r.metric_type}-${r.threshold_value}`}>{metricLabels[r.metric_type]||r.metric_type}: {r.metric_type==='lifetime_spend'?money.format(Number(r.threshold_value)/100):r.threshold_value}</span>)}</div><div className="vip-chip-row vip-chip-row-benefits">{t.benefits.map(b=><span key={b.id||b.benefit_type}>{benefitLabels[b.benefit_type]||b.benefit_type}: {benefitValueLabel(b)}</span>)}</div><div className="vip-row-actions"><button type="button" className="vip-secondary" onClick={()=>setDraft(toDraft(t))}>Edit</button><button type="button" className="vip-danger" onClick={()=>void archiveTier(t)} disabled={saving}>Archive</button></div></article>)}</div>}</section>
  {draft&&<section className="vip-panel vip-builder"><div className="vip-panel-head"><div><span>{draft.id?'Edit tier':'New tier'}</span><h2>{draft.id?draft.name:'Configure tier'}</h2></div><button className="vip-secondary" type="button" onClick={()=>setDraft(null)}>Close</button></div><form onSubmit={saveTier}>
   <div className="vip-form-grid"><label>Tier name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Colour<input type="color" value={draft.colour} onChange={e=>setDraft({...draft,colour:e.target.value})}/></label><label>Icon<input value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})} placeholder="star"/></label><label>Priority<input required type="number" min="0" value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}/></label><label className="vip-wide">Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Rules must<select value={draft.qualification_match} onChange={e=>setDraft({...draft,qualification_match:e.target.value as 'all'|'any'})}><option value="all">All match</option><option value="any">Any match</option></select></label><label className="vip-check"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Active</label></div>
   <div className="vip-builder-section"><div><h3>Qualification rules</h3><button type="button" className="vip-secondary" onClick={()=>setDraft({...draft,rules:[...draft.rules,{metric_type:'orders_completed',threshold_value:1}]})}>Add rule</button></div>{draft.rules.map((r,i)=><div className="vip-rule-row" key={i}><select value={r.metric_type} onChange={e=>patchRule(i,{metric_type:e.target.value,custom_metric_key:e.target.value==='custom_metric'?'visits_score':null})}>{Object.entries(metricLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{r.metric_type==='custom_metric'&&<input value={r.custom_metric_key||''} onChange={e=>patchRule(i,{custom_metric_key:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')})} placeholder="metric_key"/>}<input type="number" min="0" value={r.metric_type==='lifetime_spend'?Number(r.threshold_value)/100:r.threshold_value} onChange={e=>patchRule(i,{threshold_value:r.metric_type==='lifetime_spend'?Math.round(Number(e.target.value)*100):Number(e.target.value)})}/><button type="button" className="vip-danger" onClick={()=>setDraft({...draft,rules:draft.rules.filter((_,idx)=>idx!==i)})}>Remove</button></div>)}</div>
   <div className="vip-builder-section"><div><h3>Benefits</h3><button type="button" className="vip-secondary" onClick={()=>setDraft({...draft,benefits:[...draft.benefits,{benefit_type:'percentage_discount',value:10,metadata:{}}]})}>Add benefit</button></div>{draft.benefits.map((b,i)=><div className="vip-benefit-row" key={i}><select value={b.benefit_type} onChange={e=>patchBenefit(i,{benefit_type:e.target.value,value:numericBenefits.has(e.target.value)?(e.target.value.includes('multiplier')?1.5:1):null,menu_item_id:null,reward_catalogue_id:null,metadata:{}})}>{Object.entries(benefitLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{numericBenefits.has(b.benefit_type)&&<input type="number" min="0" step={b.benefit_type.includes('multiplier')?'0.1':'0.01'} value={b.value??0} onChange={e=>patchBenefit(i,{value:Number(e.target.value)})}/>} {b.benefit_type==='free_menu_item'&&<select value={b.menu_item_id||''} onChange={e=>patchBenefit(i,{menu_item_id:e.target.value})}><option value="">Choose menu item</option>{data?.menu_items.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>}{b.benefit_type==='exclusive_reward'&&<select value={b.reward_catalogue_id||''} onChange={e=>patchBenefit(i,{reward_catalogue_id:e.target.value})}><option value="">Choose reward</option>{data?.catalogue_rewards.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>}{b.benefit_type==='bonus_stamps'&&<select value={String((b.metadata||{}).program_id||'')} onChange={e=>patchBenefit(i,{metadata:{...(b.metadata||{}),program_id:e.target.value}})}><option value="">Choose stamp programme</option>{data?.stamp_programs.filter(s=>s.is_active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<button type="button" className="vip-danger" onClick={()=>setDraft({...draft,benefits:draft.benefits.filter((_,idx)=>idx!==i)})}>Remove</button></div>)}</div>
   <button className="vip-primary" disabled={saving}>{saving?'Saving…':'Save tier'}</button>
  </form></section>}
  <section className="vip-panel"><div className="vip-panel-head"><div><span>Performance</span><h2>Tier analytics</h2></div></div><div className="vip-table-wrap"><table><thead><tr><th>Tier</th><th>Customers</th><th>Revenue</th><th>Orders</th><th>Avg spend</th><th>Visit frequency</th><th>Retention</th><th>Reward usage</th></tr></thead><tbody>{data?.tier_analytics.map(row=><tr key={row.tier_id}><td><span className="vip-dot" style={{background:row.colour}}/> {row.tier_name}</td><td>{row.customers}</td><td>{money.format(row.revenue_pence/100)}</td><td>{row.orders}</td><td>{money.format(row.average_spend_pence/100)}</td><td>{row.visit_frequency_90d}</td><td>{Number(row.retention_percent).toFixed(1)}%</td><td>{row.reward_usage}</td></tr>)}</tbody></table></div></section>
  <section className="vip-panel"><div className="vip-panel-head"><div><span>Lifetime value</span><h2>Top VIP customers</h2></div></div><div className="vip-table-wrap"><table><thead><tr><th>Customer</th><th>Tier</th><th>Lifetime value</th><th>Orders</th><th>Custom metric</th></tr></thead><tbody>{data?.top_customers.map(c=><tr key={c.customer_user_id}><td><strong>{c.customer_name}</strong><small>{c.customer_email}</small></td><td>{c.tier_name}</td><td>{money.format(c.lifetime_value_pence/100)}</td><td>{c.orders_completed}</td><td><button type="button" className="vip-secondary" onClick={()=>setMetricCustomer(c.customer_user_id)}>Update</button></td></tr>)}</tbody></table></div>{metricCustomer&&<form className="vip-metric-form" onSubmit={saveCustomMetric}><label>Metric key<input required pattern="[a-z0-9_]+" value={metricKey} onChange={e=>setMetricKey(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))}/></label><label>Value<input required type="number" min="0" value={metricValue} onChange={e=>setMetricValue(e.target.value)}/></label><button className="vip-primary" disabled={saving}>Save metric</button><button className="vip-secondary" type="button" onClick={()=>setMetricCustomer('')}>Cancel</button></form>}</section>
 </main>
}