import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './AIInsights.css'

type Forecast={metric:string;horizon:'weekly'|'monthly';period_start:string;period_end:string;predicted_value:number;lower_bound:number;upper_bound:number;confidence:number;explanation:string;evidence:Record<string,unknown>}
type Insight={id:string;customer_user_id:string|null;category:string;insight_type:string;severity:'info'|'opportunity'|'warning'|'critical';title:string;summary:string;explanation:string;confidence:number;evidence:Record<string,unknown>;suggested_action:Record<string,unknown>;status:string;seen_at:string|null;generated_at:string}
type Report={id:string;report_type:string;period_start:string;period_end:string;restaurant_health_score:number;growth_score:number;customer_health_score:number;marketing_score:number;operations_score:number;summary:string;sections:Record<string,unknown>;generated_at:string}
type CustomerScore={customer_user_id:string;customer_name:string;lifetime_value_pence:number;predicted_future_value_pence:number;churn_risk:number;engagement_score:number;loyalty_score:number;vip_potential:number;referral_potential:number;campaign_responsiveness:number;return_probability:number;evidence:Record<string,unknown>;computed_at:string}
type Dashboard={last_run:{status:string;provider:string;model:string;methodology_version:string;completed_at:string|null}|null;latest_report:Report|null;weekly_revenue_forecast:Forecast|null;monthly_revenue_forecast:Forecast|null;customers:{scored:number;likely_to_return:number;high_churn_risk:number;high_vip_potential:number;high_referral_potential:number};insights:Insight[];unseen_insights:number;methodology:{provider:string;model:string;version:string;explainable:boolean;protected_attributes_used:boolean}}
type MenuItem={menu_item_id:string;item_name:string;units:number;orders:number;revenue_pence:number}
type MenuData={period_days:number;best_selling:MenuItem[];worst_selling:MenuItem[];most_profitable_proxy:MenuItem[];profitability_note:string;frequently_purchased_together:Array<{a_id:string;b_id:string;a_name:string;b_name:string;n:number}>;peak_ordering_times:Array<{day_of_week:number;hour_of_day:number;orders:number;revenue_pence:number}>;category_performance:Array<{id:string;name:string;revenue_pence:number;units:number}>;bundle_opportunities:Array<{title:string;menu_item_ids:string[];pair_orders:number}>}

const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0})
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
const tabs=[['/insights','Insights'],['/insights/forecasting','Forecasting'],['/insights/recommendations','Recommendations'],['/insights/growth','Growth opportunities'],['/insights/reports','AI reports'],['/insights/customers','Customer intelligence'],['/insights/menu','Menu intelligence']] as const

export default function AIInsights(){
 const location=useLocation()
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[forecasts,setForecasts]=useState<Forecast[]>([]),[insights,setInsights]=useState<Insight[]>([]),[reports,setReports]=useState<Report[]>([]),[customers,setCustomers]=useState<CustomerScore[]>([]),[menu,setMenu]=useState<MenuData|null>(null)
 const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [d,f,i,r,c,m]=await Promise.all([supabase.rpc('get_restaurant_ai_dashboard'),supabase.rpc('get_restaurant_ai_forecasts'),supabase.rpc('get_restaurant_ai_recommendations',{p_category:null,p_limit:100}),supabase.rpc('get_restaurant_ai_reports',{p_limit:24}),supabase.rpc('get_restaurant_ai_customer_intelligence',{p_limit:100,p_min_churn:0}),supabase.rpc('get_restaurant_ai_menu_intelligence',{p_days:90})]);const first=[d.error,f.error,i.error,r.error,c.error,m.error].find(Boolean);if(first)setError(first?.message||'Unable to load intelligence.');else{setDashboard(d.data as Dashboard);setForecasts((f.data||[]) as Forecast[]);setInsights((i.data||[]) as Insight[]);setReports((r.data||[]) as Report[]);setCustomers((c.data||[]) as CustomerScore[]);setMenu(m.data as MenuData)}setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 async function refresh(){setRefreshing(true);setError('');const {error:e}=await supabase.rpc('refresh_restaurant_ai_intelligence');if(e)setError(e.message);else await load();setRefreshing(false)}
 async function mark(id:string,dismiss=false){const {error:e}=await supabase.rpc('mark_restaurant_ai_insight_seen',{p_insight_id:id,p_dismiss:dismiss});if(e)setError(e.message);else await load()}
 const section=location.pathname.split('/')[2]||'overview'
 const activeInsights=useMemo(()=>insights.filter(x=>x.status!=='dismissed'),[insights])
 return <main className="ai-shell">
  <header className="ai-header"><div><Link className="brand" to="/dashboard">ordered.food</Link><span className="eyebrow">AI restaurant intelligence</span><h1>Turn restaurant data into decisions.</h1><p>Explainable forecasts, customer signals, menu intelligence and growth recommendations built from your existing ordered.food data.</p></div><button className="primary-button" type="button" disabled={refreshing} onClick={()=>void refresh()}>{refreshing?'Generating…':'Generate fresh insights'}</button></header>
  <nav className="ai-tabs" aria-label="AI intelligence">{tabs.map(([to,label])=><NavLink key={to} to={to} end={to==='/insights'}>{label}{to==='/insights'&&Number(dashboard?.unseen_insights||0)>0?<b>{dashboard?.unseen_insights}</b>:null}</NavLink>)}</nav>
  {error&&<p className="orders-error" role="alert">{error}</p>}
  {loading?<section className="ai-panel"><p>Loading intelligence…</p></section>:section==='forecasting'?<Forecasting forecasts={forecasts}/>:section==='reports'?<Reports reports={reports}/>:section==='customers'?<Customers customers={customers}/>:section==='menu'?<Menu menu={menu}/>:section==='recommendations'?<Recommendations insights={activeInsights} mark={mark}/>:section==='growth'?<Growth insights={activeInsights}/>:<Overview dashboard={dashboard} insights={activeInsights} forecasts={forecasts}/>}
  <footer className="ai-method"><strong>Traceable by design.</strong> Provider: {dashboard?.methodology?.provider||'internal'} · Model: {dashboard?.methodology?.model||'ordered-intelligence-v1'} · Methodology {dashboard?.methodology?.version||'5.9.1'}. Recommendations are decision support, not automatic actions.</footer>
 </main>
}

function Overview({dashboard,insights,forecasts}:{dashboard:Dashboard|null;insights:Insight[];forecasts:Forecast[]}){const report=dashboard?.latest_report;return <>
 <section className="ai-score-hero"><div><span>Restaurant health score</span><strong>{fmt(report?.restaurant_health_score)}<small>/100</small></strong><p>{report?.summary||'Generate intelligence to establish your baseline.'}</p></div><div className="ai-score-grid"><Score label="Growth" value={report?.growth_score}/><Score label="Customer health" value={report?.customer_health_score}/><Score label="Marketing" value={report?.marketing_score}/><Score label="Operations" value={report?.operations_score}/></div></section>
 <section className="ai-metrics"><Metric label="Weekly revenue forecast" value={forecastMoney(dashboard?.weekly_revenue_forecast)} detail={confidence(dashboard?.weekly_revenue_forecast?.confidence)}/><Metric label="Monthly revenue forecast" value={forecastMoney(dashboard?.monthly_revenue_forecast)} detail={confidence(dashboard?.monthly_revenue_forecast?.confidence)}/><Metric label="Customers likely to return" value={String(dashboard?.customers?.likely_to_return||0)} detail={`${dashboard?.customers?.scored||0} customers scored`}/><Metric label="High churn risk" value={String(dashboard?.customers?.high_churn_risk||0)} detail="Needs attention"/></section>
 <div className="ai-two-col"><section className="ai-panel"><Heading title="Priority recommendations" text="Highest-value signals from customer, marketing, menu and operations data."/><div className="ai-insight-list">{insights.slice(0,8).map(i=><InsightCard key={i.id} insight={i}/>)||null}{insights.length===0&&<Empty text="No active recommendations yet."/>}</div></section><section className="ai-panel"><Heading title="Forecast signals" text="Forward-looking demand and revenue indicators."/><div className="ai-forecast-list">{forecasts.slice(0,8).map(f=><ForecastRow key={`${f.metric}-${f.horizon}`} forecast={f}/>)}</div></section></div>
 </>}
function Forecasting({forecasts}:{forecasts:Forecast[]}){return <section className="ai-panel"><Heading title="Forecasting" text="Weekly and monthly forecasts include uncertainty ranges and the evidence used."/><div className="ai-forecast-grid">{forecasts.map(f=><article className="ai-forecast-card" key={`${f.metric}-${f.horizon}`}><span>{labelMetric(f.metric)} · {f.horizon}</span><strong>{f.metric.includes('pence')?money.format(Number(f.predicted_value)/100):Math.round(Number(f.predicted_value)).toLocaleString()}</strong><p>Range {f.metric.includes('pence')?`${money.format(Number(f.lower_bound)/100)}–${money.format(Number(f.upper_bound)/100)}`:`${Math.round(Number(f.lower_bound))}–${Math.round(Number(f.upper_bound))}`} · {confidence(f.confidence)}</p><small>{f.explanation}</small></article>)}</div></section>}
function Recommendations({insights,mark}:{insights:Insight[];mark:(id:string,dismiss?:boolean)=>Promise<void>}){return <section className="ai-panel"><Heading title="Recommendations" text="Every recommendation includes confidence, evidence and a suggested next action. Nothing is executed automatically."/><div className="ai-insight-list">{insights.map(i=><div key={i.id} className="ai-recommendation"><InsightCard insight={i}/><div className="ai-rec-actions">{typeof i.suggested_action?.target==='string'&&<Link className="secondary-button button-link" to={String(i.suggested_action.target)}>Open action</Link>}<button type="button" onClick={()=>void mark(i.id)}>Mark seen</button><button type="button" onClick={()=>void mark(i.id,true)}>Dismiss</button></div></div>)}</div></section>}
function Growth({insights}:{insights:Insight[]}){const growth=insights.filter(i=>['growth','revenue','marketing','vip','referral','challenge','birthday','loyalty'].includes(i.category));return <section className="ai-panel"><Heading title="Growth opportunities" text="Retention, campaign, loyalty and customer-development opportunities ranked from current signals."/><div className="ai-insight-list">{growth.map(i=><InsightCard key={i.id} insight={i}/>)}{growth.length===0&&<Empty text="No growth opportunities are currently above the recommendation threshold."/>}</div></section>}
function Reports({reports}:{reports:Report[]}){return <section className="ai-panel"><Heading title="AI reports" text="Daily, weekly and monthly summaries keep health and growth scoring traceable over time."/><div className="ai-report-list">{reports.map(r=><article key={r.id}><div><span>{r.report_type} report</span><strong>{new Date(r.generated_at).toLocaleString('en-GB')}</strong></div><div className="ai-report-scores"><b>{fmt(r.restaurant_health_score)} health</b><span>{fmt(r.growth_score)} growth</span><span>{fmt(r.customer_health_score)} customer</span><span>{fmt(r.marketing_score)} marketing</span></div><p>{r.summary}</p></article>)}</div></section>}
function Customers({customers}:{customers:CustomerScore[]}){return <section className="ai-panel"><Heading title="Customer intelligence" text="Lifetime value, predicted future value, churn, engagement, loyalty, VIP, referral and campaign-response signals."/><div className="ai-table-wrap"><table className="ai-table"><thead><tr><th>Customer</th><th>LTV</th><th>Future value</th><th>Churn</th><th>Return</th><th>Engagement</th><th>Loyalty</th><th>VIP</th><th>Referral</th><th>Campaign</th></tr></thead><tbody>{customers.map(c=><tr key={c.customer_user_id}><td><strong>{c.customer_name}</strong></td><td>{money.format(c.lifetime_value_pence/100)}</td><td>{money.format(c.predicted_future_value_pence/100)}</td><td>{fmt(c.churn_risk)}</td><td>{fmt(c.return_probability)}</td><td>{fmt(c.engagement_score)}</td><td>{fmt(c.loyalty_score)}</td><td>{fmt(c.vip_potential)}</td><td>{fmt(c.referral_potential)}</td><td>{fmt(c.campaign_responsiveness)}</td></tr>)}</tbody></table></div></section>}
function Menu({menu}:{menu:MenuData|null}){if(!menu)return <section className="ai-panel"><Empty text="No menu intelligence available yet."/></section>;return <div className="ai-menu-grid"><section className="ai-panel"><Heading title="Best sellers" text="Ranked by units sold."/><MenuRows items={menu.best_selling}/></section><section className="ai-panel"><Heading title="Revenue contribution" text="A profitability proxy until item cost data is available."/><MenuRows items={menu.most_profitable_proxy}/><p className="ai-note">{menu.profitability_note}</p></section><section className="ai-panel"><Heading title="Bundle & cross-sell opportunities" text="Items frequently purchased together."/><div className="ai-simple-list">{menu.bundle_opportunities.map((x,i)=><article key={i}><strong>{x.title}</strong><span>{x.pair_orders} shared orders</span></article>)}</div></section><section className="ai-panel"><Heading title="Peak ordering times" text="Historical paid-order demand by day and hour."/><div className="ai-simple-list">{menu.peak_ordering_times.slice(0,8).map((x,i)=><article key={i}><strong>{days[x.day_of_week]||x.day_of_week} {String(x.hour_of_day).padStart(2,'0')}:00</strong><span>{x.orders} orders · {money.format(x.revenue_pence/100)}</span></article>)}</div></section><section className="ai-panel"><Heading title="Category performance" text="Revenue and unit volume by category."/><div className="ai-simple-list">{menu.category_performance.map(x=><article key={x.id}><strong>{x.name}</strong><span>{money.format(x.revenue_pence/100)} · {x.units} units</span></article>)}</div></section><section className="ai-panel"><Heading title="Underperformers" text="Review presentation, bundling, price and placement before removing items."/><MenuRows items={menu.worst_selling}/></section></div>}
function Score({label,value}:{label:string;value:number|undefined}){return <article><span>{label}</span><strong>{fmt(value)}</strong></article>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Heading({title,text}:{title:string;text:string}){return <div className="ai-panel-heading"><div><span className="eyebrow">ordered intelligence</span><h2>{title}</h2><p>{text}</p></div></div>}
function InsightCard({insight}:{insight:Insight}){return <article className={`ai-insight ai-insight--${insight.severity}`}><div><span>{insight.category} · {Math.round(Number(insight.confidence)*100)}% confidence</span><h3>{insight.title}</h3><p>{insight.summary}</p><details><summary>Why am I seeing this?</summary><p>{insight.explanation}</p><pre>{JSON.stringify(insight.evidence,null,2)}</pre></details></div></article>}
function ForecastRow({forecast}:{forecast:Forecast}){return <article><div><strong>{labelMetric(forecast.metric)}</strong><span>{forecast.horizon}</span></div><b>{forecast.metric.includes('pence')?money.format(Number(forecast.predicted_value)/100):Math.round(Number(forecast.predicted_value)).toLocaleString()}</b><small>{confidence(forecast.confidence)}</small></article>}
function MenuRows({items}:{items:MenuItem[]}){return <div className="ai-simple-list">{items.map(x=><article key={x.menu_item_id}><strong>{x.item_name}</strong><span>{x.units} units · {money.format(x.revenue_pence/100)}</span></article>)}</div>}
function Empty({text}:{text:string}){return <div className="ai-empty">{text}</div>}
function fmt(v:number|undefined){return Number(v||0).toFixed(0)}
function forecastMoney(f:Forecast|null|undefined){return f?money.format(Number(f.predicted_value)/100):'—'}
function confidence(v:number|undefined){return `${Math.round(Number(v||0)*100)}% confidence`}
function labelMetric(v:string){return v.replaceAll('_',' ').replace('pence','').trim().replace(/^./,c=>c.toUpperCase())}
