import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './CustomerRewards.css'

type Reward={id:string;name:string;description:string|null;reward_type:string;points_cost:number;fixed_value_pence:number|null;percentage_basis_points:number|null;minimum_order_pence:number;ends_at:string|null;stock_remaining:number|null;can_afford:boolean}
type Voucher={id:string;code:string;status:string;expires_at:string|null;reward_name:string;reward_type:string}
type Store={points_balance:number;rewards:Reward[];vouchers:Voucher[]}
const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'})
function benefit(r:Reward){if(r.reward_type==='fixed_discount'||r.reward_type==='wallet_credit')return `£${((r.fixed_value_pence||0)/100).toFixed(2)}`;if(r.reward_type==='percentage_discount')return `${((r.percentage_basis_points||0)/100).toFixed(0)}% off`;if(r.reward_type==='free_delivery')return 'Free delivery';return 'Free item'}
export default function CustomerRewards(){const{restaurantId}=useParams(),navigate=useNavigate();const[store,setStore]=useState<Store|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');async function load(){const{data:session}=await supabase.auth.getSession();if(!session.session?.user){navigate('/account/login',{replace:true});return}if(!restaurantId){setError('Restaurant is missing.');setLoading(false);return}const{data,error}=await supabase.rpc('get_customer_reward_store',{p_restaurant_id:restaurantId});if(error)setError(error.message);else setStore(data as Store);setLoading(false)}useEffect(()=>{void load()},[restaurantId]);async function redeem(id:string){setBusy(id);setError('');const{error}=await supabase.rpc('redeem_loyalty_reward',{p_reward_id:id});if(error)setError(error.message);else await load();setBusy('')}if(loading)return <main className="customer-rewards-state">Loading rewards…</main>;return <main className="customer-rewards-page"><header><Link to="/account/loyalty">← Loyalty</Link><strong>Rewards</strong><Link to="/restaurants">Find food</Link></header><section className="customer-rewards-hero"><span>Your points</span><h1>{store?.points_balance||0}</h1><p>Redeem points for vouchers you can use with this restaurant.</p></section>{error&&<p className="customer-rewards-error">{error}</p>}<section><div className="customer-rewards-heading"><div><span>Available</span><h2>Reward store</h2></div></div>{store?.rewards.length?<div className="customer-reward-grid">{store.rewards.map(r=><article key={r.id}><div><span>{benefit(r)}</span><h3>{r.name}</h3><p>{r.description||'Redeem this reward with your loyalty points.'}</p>{r.minimum_order_pence>0&&<small>Minimum order £{(r.minimum_order_pence/100).toFixed(2)}</small>}{r.ends_at&&<small>Ends {date.format(new Date(r.ends_at))}</small>}</div><button disabled={!r.can_afford||busy===r.id} onClick={()=>void redeem(r.id)}>{busy===r.id?'Redeeming…':r.can_afford?`${r.points_cost} points`:`Need ${r.points_cost-store!.points_balance} more`}</button></article>)}</div>:<div className="customer-rewards-empty">No rewards are currently available.</div>}</section><section><div className="customer-rewards-heading"><div><span>Wallet</span><h2>Your vouchers</h2></div></div>{store?.vouchers.length?<div className="customer-vouchers">{store.vouchers.map(v=><article key={v.id}><div><strong>{v.reward_name}</strong><span>{v.code}</span><small>{v.expires_at?`Expires ${date.format(new Date(v.expires_at))}`:'No expiry date'}</small></div><span>{v.status}</span></article>)}</div>:<div className="customer-rewards-empty">Redeemed vouchers will appear here.</div>}</section></main>}
