import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import CustomerNotificationBell from './CustomerNotificationBell'
import './CustomerVip.css'

type Benefit={id:string;benefit_type:string;value:number|null;menu_item_name?:string|null;reward_name?:string|null;metadata?:Record<string,unknown>}
type Requirement={metric_type:string;custom_metric_key?:string|null;threshold_value:number;current_value:number;remaining:number;progress_percent:number}
type Tier={id:string;name:string;colour:string;icon:string;description:string|null;priority:number;requirements?:Requirement[];qualification_match?:'all'|'any'}
type History={id:string;change_type:string;from_tier_name:string|null;to_tier_name:string|null;reason:string;created_at:string}
type Membership={membership_id:string;restaurant_id:string;restaurant_name:string;restaurant_slug:string;current_tier:Tier|null;benefits:Benefit[];metrics:{lifetime_spend_pence?:number;orders_completed?:number;loyalty_points?:number;stamp_cards_completed?:number;referral_count?:number;custom_metrics?:Record<string,number>};next_tier:Tier|null;history:History[];tier_changed_at:string|null;evaluated_at:string}
type Reward={issuance_id:string;restaurant_id:string;restaurant_name:string;status:string;reward_type:string;reward_value:number;issued_at:string|null;redeemed_at:string|null;expires_at:string|null;metadata:Record<string,unknown>}
type Dashboard={memberships:Membership[];reward_history:Reward[]}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'})
const labels:Record<string,string>={lifetime_spend:'Lifetime spend',orders_completed:'Orders completed',loyalty_points:'Loyalty points earned',stamp_cards_completed:'Stamp cards completed',referral_count:'Qualified referrals',custom_metric:'Restaurant activity',bonus_loyalty_points:'Bonus loyalty points on every order',bonus_stamps:'Bonus stamps on every order',percentage_discount:'Automatic order discount',fixed_discount:'Automatic order discount',free_delivery:'Free delivery',free_menu_item:'Free menu item',birthday_bonus_multiplier:'Bigger birthday rewards',referral_multiplier:'Bigger referral rewards',exclusive_reward:'Exclusive reward',early_access_promotions:'Early access to promotions',priority_customer_support:'Priority customer support'}
function benefitText(b:Benefit){if(b.benefit_type==='percentage_discount')return `${Number(b.value||0)/100}% off automatically`;if(b.benefit_type==='fixed_discount')return `${money.format(Number(b.value||0)/100)} off automatically`;if(b.benefit_type==='bonus_loyalty_points')return `+${b.value||0} loyalty points per completed order`;if(b.benefit_type==='bonus_stamps')return `+${b.value||0} stamps per completed order`;if(b.benefit_type==='birthday_bonus_multiplier'||b.benefit_type==='referral_multiplier')return `${Number(b.value||10000)/10000}× ${b.benefit_type==='birthday_bonus_multiplier'?'birthday':'referral'} reward`;if(b.benefit_type==='free_menu_item')return `Free ${b.menu_item_name||'menu item'}`;if(b.benefit_type==='exclusive_reward')return b.reward_name||'Exclusive reward';return labels[b.benefit_type]||b.benefit_type.replaceAll('_',' ')}
function requirementValue(r:Requirement,value:number){if(r.metric_type==='lifetime_spend')return money.format(value/100);return String(value)}

export default function CustomerVip(){const navigate=useNavigate();const[params,setParams]=useSearchParams();const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const celebrate=params.get('celebrate')
 useEffect(()=>{let active=true;async function load(){const{data:session}=await supabase.auth.getSession();if(!session.session){navigate('/account/login',{replace:true,state:{from:'/account/vip'}});return}const{data:result,error:rpcError}=await supabase.rpc('get_customer_vip_dashboard');if(!active)return;if(rpcError)setError(rpcError.message);else setData(result as Dashboard);setLoading(false)}void load();return()=>{active=false}},[navigate])
 const celebration=useMemo(()=>{if(!celebrate||!data)return null;for(const m of data.memberships){const h=m.history.find(item=>item.id===celebrate);if(h)return{membership:m,history:h}}return null},[celebrate,data])
 if(loading)return <main className="customer-vip-state">Loading your VIP memberships…</main>
 return <main className="customer-vip-page"><header className="customer-vip-header"><Link to="/account">← Account</Link><strong>ordered.food VIP</strong><CustomerNotificationBell/></header><section className="customer-vip-hero"><span>Your status</span><h1>VIP memberships</h1><p>See every tier, benefit, unlocked reward and the exact progress towards your next level.</p></section>{error&&<div className="customer-vip-error">{error}</div>}
 {(data?.memberships||[]).length===0?<section className="customer-vip-empty"><div>✦</div><h2>No VIP tier yet</h2><p>Restaurants you order from can automatically qualify you as you spend, collect points, complete stamp cards and refer friends.</p><Link to="/restaurants">Browse restaurants</Link></section>:<div className="customer-vip-list">{data?.memberships.map(m=><section className="customer-vip-card" key={m.membership_id}><div className="customer-vip-card-head"><div><Link to={`/r/${m.restaurant_slug}`}>{m.restaurant_name}</Link><h2>{m.current_tier?.name||'Building VIP status'}</h2><p>{m.current_tier?.description||'Keep ordering to reach your first VIP tier.'}</p></div>{m.current_tier&&<div className="customer-vip-badge" style={{background:m.current_tier.colour}}><span>{m.current_tier.icon}</span><strong>{m.current_tier.name}</strong></div>}</div>
  <div className="customer-vip-stats"><article><span>Lifetime spend</span><strong>{money.format(Number(m.metrics.lifetime_spend_pence||0)/100)}</strong></article><article><span>Orders</span><strong>{m.metrics.orders_completed||0}</strong></article><article><span>Points earned</span><strong>{m.metrics.loyalty_points||0}</strong></article><article><span>Stamp cards</span><strong>{m.metrics.stamp_cards_completed||0}</strong></article><article><span>Referrals</span><strong>{m.metrics.referral_count||0}</strong></article></div>
  <div className="customer-vip-columns"><div><h3>Benefits unlocked</h3>{m.benefits.length?<ul className="customer-vip-benefits">{m.benefits.map(b=><li key={b.id}><span>✓</span><div><strong>{labels[b.benefit_type]||'VIP benefit'}</strong><small>{benefitText(b)}</small></div></li>)}</ul>:<p className="customer-vip-muted">No benefits configured on this tier.</p>}</div><div><h3>{m.next_tier?`Next: ${m.next_tier.name}`:'Top tier reached'}</h3>{m.next_tier?<><p className="customer-vip-muted">{m.next_tier.qualification_match==='any'?'Meet any one requirement':'Meet every requirement'} to level up automatically.</p><div className="customer-vip-progress-list">{(m.next_tier.requirements||[]).map((r,i)=><article key={`${r.metric_type}-${i}`}><div><span>{r.metric_type==='custom_metric'?(r.custom_metric_key||'Custom metric'):labels[r.metric_type]}</span><strong>{requirementValue(r,r.current_value)} / {requirementValue(r,r.threshold_value)}</strong></div><div className="customer-vip-progress"><i style={{width:`${Math.max(0,Math.min(100,Number(r.progress_percent||0)))}%`,background:m.next_tier?.colour}}/></div><small>{r.remaining>0?`${requirementValue(r,r.remaining)} remaining`:'Requirement met'}</small></article>)}</div></>:<div className="customer-vip-top">✦ You have reached the highest active tier.</div>}</div></div>
  <details className="customer-vip-history"><summary>Tier history</summary>{m.history.length?<ol>{m.history.map(h=><li key={h.id}><span>{date.format(new Date(h.created_at))}</span><strong>{h.change_type==='initial'?`Joined ${h.to_tier_name||'VIP'}`:h.change_type==='upgrade'?`Upgraded to ${h.to_tier_name}`:h.change_type==='downgrade'?`Moved to ${h.to_tier_name||'no tier'}`:'Tier removed'}</strong><small>{h.reason.replaceAll('_',' ')}</small></li>)}</ol>:<p>No tier changes yet.</p>}</details>
 </section>)}</div>}
 <section className="customer-vip-rewards"><div><span>Unlocked</span><h2>VIP reward summary</h2></div>{data?.reward_history.length?<div className="customer-vip-reward-grid">{data.reward_history.map(r=><article key={r.issuance_id}><strong>{r.restaurant_name}</strong><span>{r.reward_type.replaceAll('_',' ')}</span><small>{r.status}{r.expires_at?` · expires ${date.format(new Date(r.expires_at))}`:''}</small>{r.status==='available'&&<Link to={`/account/rewards/${r.restaurant_id}`}>View reward</Link>}</article>)}</div>:<p className="customer-vip-muted">Exclusive tier rewards will appear here when unlocked.</p>}</section>
 {celebration&&<div className="customer-vip-celebration" role="dialog" aria-modal="true"><div><button aria-label="Close celebration" type="button" onClick={()=>{params.delete('celebrate');setParams(params,{replace:true})}}>×</button><div className="customer-vip-celebration-badge" style={{background:celebration.membership.current_tier?.colour||'#6d28d9'}}>✦</div><span>Congratulations</span><h2>{celebration.history.to_tier_name||'VIP'} unlocked!</h2><p>You have reached a new VIP tier at {celebration.membership.restaurant_name}. Your new benefits are active automatically.</p><ul>{celebration.membership.benefits.slice(0,5).map(b=><li key={b.id}>{benefitText(b)}</li>)}</ul><button type="button" onClick={()=>{params.delete('celebrate');setParams(params,{replace:true})}}>See my VIP status</button></div></div>}
 </main>}
