import { useEffect,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './CustomerLoyalty.css'

type Account={restaurant_id:string;restaurant_name:string;restaurant_slug:string;available_points:number;pending_points:number;lifetime_earned:number;lifetime_redeemed:number;last_earned_at:string|null}
type Tx={id:string;restaurant_name:string;points_delta:number;entry_type:string;note:string|null;created_at:string}
type Summary={total_available_points:number;total_pending_points:number;accounts:Account[];transactions:Tx[]}
const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'})
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())
export default function CustomerLoyalty(){const navigate=useNavigate(),[summary,setSummary]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;void(async()=>{const{data:session}=await supabase.auth.getSession();if(!session.session?.user){navigate('/account/login',{replace:true,state:{from:'/account/loyalty'}});return}const{data,error}=await supabase.rpc('get_customer_loyalty_summary');if(!active)return;if(error)setError(error.message);else setSummary(data as Summary);setLoading(false)})();return()=>{active=false}},[navigate]);if(loading)return <main className="customer-loyalty-state">Loading loyalty points…</main>;const s=summary??{total_available_points:0,total_pending_points:0,accounts:[],transactions:[]};return <main className="customer-loyalty-page"><header><Link to="/account">← Back to account</Link><strong>Loyalty</strong><Link to="/restaurants">Find food</Link></header><section className="customer-loyalty-hero"><span>Available points</span><h1>{s.total_available_points.toLocaleString()}</h1><p>{s.total_pending_points.toLocaleString()} points pending from completed orders.</p></section>{error&&<p className="customer-loyalty-error">{error}</p>}<section className="customer-loyalty-section"><div><span>Restaurants</span><h2>Your loyalty balances</h2></div>{s.accounts.length?<div className="customer-loyalty-list">{s.accounts.map(a=><article key={a.restaurant_id}><div><h3>{a.restaurant_name}</h3><small>{a.last_earned_at?`Last earned ${date.format(new Date(a.last_earned_at))}`:'No released points yet'}</small></div><div><strong>{a.available_points.toLocaleString()} pts</strong><span>{a.pending_points.toLocaleString()} pending</span><Link to={`/r/${a.restaurant_slug}`}>Order</Link></div></article>)}</div>:<div className="customer-loyalty-empty">Your loyalty balances will appear after eligible orders.</div>}</section><section className="customer-loyalty-section"><div><span>Activity</span><h2>Points history</h2></div>{s.transactions.length?<div className="customer-loyalty-transactions">{s.transactions.map(t=><article key={t.id}><div><strong>{t.restaurant_name}</strong><span>{t.note||label(t.entry_type)}</span><small>{date.format(new Date(t.created_at))}</small></div><strong className={t.points_delta>=0?'positive':'negative'}>{t.points_delta>=0?'+':''}{t.points_delta.toLocaleString()} pts</strong></article>)}</div>:<div className="customer-loyalty-empty">No loyalty activity yet.</div>}</section></main>}
