import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './CustomerMilestones.css'

type Upcoming={program_id:string;restaurant_id:string;restaurant_name:string;name:string;milestone_type:'order_count'|'lifetime_spend';threshold_value:number;current_value:number;progress_percent:number}
type Reward={issuance_id:string;source_type?:'birthday'|'milestone';restaurant_name:string;program_name?:string;status:string;issued_at:string|null;redeemed_at:string|null;expires_at:string|null;reward_type:string;reward_value:number}
type Dashboard={date_of_birth:string|null;can_change_date_of_birth:boolean;order_count:number;lifetime_spend_pence:number;upcoming:Upcoming[];completed:Reward[];birthday_rewards:Reward[];reward_history:Reward[]}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'})
const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())
function rewardLabel(r:Reward){if(r.reward_type==='percentage_discount')return `${(r.reward_value/100).toFixed(0)}% discount`;if(r.reward_type==='loyalty_points')return `${r.reward_value} loyalty points`;if(r.reward_type==='free_delivery')return 'Free delivery';if(r.reward_type==='free_item')return 'Free item';return money.format(r.reward_value/100)}
export default function CustomerMilestones(){const navigate=useNavigate();const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
async function load(){setLoading(true);setError('');const{data:{session}}=await supabase.auth.getSession();if(!session){navigate('/account/login',{replace:true,state:{from:'/account/milestones'}});return}const{data,error:rpcError}=await supabase.rpc('get_customer_milestone_dashboard');if(rpcError)setError(rpcError.message);else setDash(data as Dashboard);setLoading(false)}useEffect(()=>{void load()},[])
const next=useMemo(()=>dash?.upcoming?.[0]||null,[dash]);if(loading)return <main className="milestone-page"><section className="milestone-card">Loading your rewards…</section></main>;
return <main className="milestone-page"><header><div><Link to="/account">← My account</Link><span>Rewards journey</span><h1>Milestones</h1><p>Track birthday rewards, loyalty moments and the next reward you are working towards.</p></div><Link className="milestone-button" to="/account/notifications">Notifications</Link></header>{error&&<div className="milestone-error">{error}</div>}
<section className="milestone-stats"><article><span>Completed orders</span><strong>{dash?.order_count||0}</strong></article><article><span>Lifetime spend</span><strong>{money.format((dash?.lifetime_spend_pence||0)/100)}</strong></article><article><span>Earned rewards</span><strong>{dash?.reward_history?.length||0}</strong></article><article><span>Birthday</span><strong>{dash?.date_of_birth?date.format(new Date(`${dash.date_of_birth}T12:00:00`)):'Not set'}</strong><small>{dash?.date_of_birth?(dash.can_change_date_of_birth?'One change available':'Contact support to change'):<Link to="/account/profile">Add in profile</Link>}</small></article></section>
{next&&<section className="milestone-card milestone-next"><div><span>Next reward</span><h2>{next.name}</h2><p>{next.restaurant_name} · {next.milestone_type==='order_count'?`${next.current_value} of ${next.threshold_value} orders`:`${money.format(next.current_value/100)} of ${money.format(next.threshold_value/100)}`}</p></div><div className="milestone-progress" aria-label={`${next.progress_percent}% complete`}><i style={{width:`${Math.min(100,next.progress_percent)}%`}}/><strong>{Number(next.progress_percent).toFixed(0)}%</strong></div></section>}
<section className="milestone-grid"><div className="milestone-card"><div className="milestone-heading"><div><span>Coming up</span><h2>Upcoming milestones</h2></div><strong>{dash?.upcoming?.length||0}</strong></div>{dash?.upcoming?.length?dash.upcoming.map(item=><article className="milestone-row" key={item.program_id}><div><strong>{item.name}</strong><small>{item.restaurant_name}</small></div><div><span>{item.milestone_type==='order_count'?`${item.current_value}/${item.threshold_value} orders`:`${money.format(item.current_value/100)} / ${money.format(item.threshold_value/100)}`}</span><progress max={100} value={Math.min(100,item.progress_percent)}/></div></article>):<p>No active milestones yet.</p>}</div>
<div className="milestone-card"><div className="milestone-heading"><div><span>Birthday perks</span><h2>Birthday rewards</h2></div><strong>{dash?.birthday_rewards?.length||0}</strong></div>{dash?.birthday_rewards?.length?dash.birthday_rewards.map(r=><RewardRow key={r.issuance_id} reward={r}/>):<p>Participating restaurants will place birthday rewards here automatically.</p>}</div></section>
<section className="milestone-card"><div className="milestone-heading"><div><span>History</span><h2>Reward history</h2></div></div>{dash?.reward_history?.length?<div className="milestone-history">{dash.reward_history.map(r=><RewardRow key={r.issuance_id} reward={r}/>)}</div>:<p>Your earned rewards will appear here.</p>}</section></main>}
function RewardRow({reward:r}:{reward:Reward}){return <article className="reward-row"><div><strong>{r.program_name||r.restaurant_name}</strong><small>{r.program_name?r.restaurant_name:text(r.source_type||'reward')}</small></div><div><strong>{rewardLabel(r)}</strong><small>{text(r.status)}{r.expires_at&&r.status==='available'?` · expires ${date.format(new Date(r.expires_at))}`:''}</small></div></article>}
