import { useCallback, useEffect, useMemo, useState, type CSSProperties } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import CustomerNotificationBell from './CustomerNotificationBell'
import './CustomerChallenges.css'

type Reward={reward_type:string;reward_value:number;status?:string;issued_at?:string;expires_at?:string}
type Challenge={challenge_id:string;restaurant_id:string;restaurant_name:string;restaurant_slug?:string;name:string;description:string;icon:string;colour:string;banner_image_url?:string|null;starts_at?:string;ends_at?:string|null;priority?:number;progress_id?:string;progress_percent?:number;estimated_completion_at?:string|null;completed_at?:string;cycle_key?:string;rewards:Reward[]}
type Achievement={id:string;achievement_id:string;restaurant_id:string;name:string;description:string;icon:string;colour:string;unlocked_at:string}
type Dashboard={active:Challenge[];upcoming:Challenge[];completed:Challenge[];achievements:Achievement[];preferences:Array<{restaurant_id:string;leaderboard_visibility:string;nickname:string|null}>}
type Leaderboard={restaurant_id:string;restaurant_name:string;metric:string;entries:Array<{rank:number;display_name:string;score:number;is_you:boolean}>;preference:{restaurant_id:string;leaderboard_visibility:string;nickname:string|null}}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
const dateTime=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'})
const rewardLabel=(r:Reward)=>{if(r.reward_type==='fixed_discount'||r.reward_type==='wallet_credit')return money.format(r.reward_value/100);if(r.reward_type==='percentage_discount')return `${r.reward_value/100}% off`;if(r.reward_type==='loyalty_points')return `${r.reward_value} points`;if(r.reward_type==='bonus_stamps')return `${r.reward_value} stamps`;if(r.reward_type==='free_delivery')return 'Free delivery';if(r.reward_type==='free_item')return 'Free item';if(r.reward_type==='vip_bonus')return 'VIP bonus';if(r.reward_type==='referral_bonus')return 'Referral bonus';return r.reward_type.replaceAll('_',' ')}
function remaining(end?:string|null){if(!end)return 'No expiry';const ms=new Date(end).getTime()-Date.now();if(ms<=0)return 'Ended';const hours=Math.ceil(ms/36e5);if(hours<48)return `${hours}h left`;return `${Math.ceil(hours/24)} days left`}
export default function CustomerChallenges(){
 const nav=useNavigate(),[data,setData]=useState<Dashboard|null>(null),[boards,setBoards]=useState<Leaderboard[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[celebrate,setCelebrate]=useState(false)
 const load=useCallback(async()=>{setError('');const{data:session}=await supabase.auth.getSession();if(!session.session){nav('/account/login',{replace:true,state:{from:'/account/challenges'}});return}const[dash,leaderboards]=await Promise.all([supabase.rpc('get_customer_challenges'),supabase.rpc('get_customer_challenge_leaderboards')]);if(dash.error)setError(dash.error.message);else{const next=dash.data as Dashboard;setData(next);const latest=next.completed?.[0]?.completed_at;if(latest&&Date.now()-new Date(latest).getTime()<120000)setCelebrate(true)}if(!leaderboards.error)setBoards((leaderboards.data||[]) as Leaderboard[]);setLoading(false)},[nav])
 useEffect(()=>{void load()},[load])
 const totalProgress=useMemo(()=>data?.active?.length?Math.round(data.active.reduce((sum,c)=>sum+Number(c.progress_percent||0),0)/data.active.length):0,[data])
 async function savePrivacy(board:Leaderboard,visibility:string,nickname:string|null){const{error:e}=await supabase.rpc('save_customer_gamification_preferences',{p_restaurant_id:board.restaurant_id,p_visibility:visibility,p_nickname:nickname});if(e)setError(e.message);else await load()}
 if(loading)return <main className="customer-challenges-state">Loading your challenges…</main>
 return <main className="customer-challenges-page">
  {celebrate&&<div className="challenge-celebration" role="status" onAnimationEnd={()=>setCelebrate(false)}><span>★</span><strong>Challenge complete!</strong><i>✦</i><b>●</b></div>}
  <header className="customer-challenges-header"><Link to="/account" className="brand">ordered.food</Link><div><CustomerNotificationBell/><Link to="/account">Account</Link></div></header>
  <section className="customer-challenges-hero"><div><span>Challenges</span><h1>Turn your favourites into rewards.</h1><p>Complete restaurant missions, unlock badges and climb optional privacy-friendly leaderboards.</p></div><div className="challenge-ring" style={{'--progress':`${totalProgress*3.6}deg`} as CSSProperties}><strong>{totalProgress}%</strong><small>average progress</small></div></section>
  {error&&<p className="customer-challenges-error" role="alert">{error}</p>}
  <section className="customer-challenge-section"><div className="section-heading"><div><span>In progress</span><h2>Active challenges</h2></div><strong>{data?.active?.length||0}</strong></div>{!data?.active?.length?<div className="empty"><h3>No active challenges</h3><p>Order from participating restaurants and new missions will appear here.</p><Link to="/restaurants">Find food</Link></div>:<div className="active-challenges">{data.active.map(c=><article key={c.progress_id||c.challenge_id} style={{'--challenge-colour':c.colour} as CSSProperties}>{c.banner_image_url&&<div className="challenge-banner" style={{backgroundImage:`url(${c.banner_image_url})`}}/>}<div className="challenge-card-head"><span className="challenge-icon">{c.icon}</span><div><small>{c.restaurant_name}</small><h3>{c.name}</h3></div><em>{remaining(c.ends_at)}</em></div><p>{c.description}</p><div className="progress-track"><i style={{width:`${Math.min(100,Number(c.progress_percent||0))}%`}}/></div><div className="progress-meta"><strong>{Math.round(Number(c.progress_percent||0))}% complete</strong>{c.estimated_completion_at&&<span>Estimated {dateTime.format(new Date(c.estimated_completion_at))}</span>}</div><div className="challenge-rewards"><small>Rewards</small>{c.rewards.map((r,i)=><span key={i}>{rewardLabel(r)}</span>)}</div>{c.restaurant_slug&&<Link to={`/r/${c.restaurant_slug}`}>Order now</Link>}</article>)}</div>}</section>
  <section className="customer-challenges-grid"><section className="customer-challenge-section"><div className="section-heading"><div><span>Coming soon</span><h2>Upcoming</h2></div></div>{!data?.upcoming?.length?<p className="muted">No scheduled challenges yet.</p>:<div className="compact-list">{data.upcoming.map(c=><article key={c.challenge_id}><span style={{background:c.colour}}>{c.icon}</span><div><strong>{c.name}</strong><small>{c.restaurant_name}</small></div><em>{c.starts_at?dateTime.format(new Date(c.starts_at)):''}</em></article>)}</div>}</section>
   <section className="customer-challenge-section"><div className="section-heading"><div><span>Trophy cabinet</span><h2>Achievements</h2></div><strong>{data?.achievements?.length||0}</strong></div>{!data?.achievements?.length?<p className="muted">Your first badge is waiting.</p>:<div className="badge-grid">{data.achievements.map(a=><article key={a.id}><span style={{background:a.colour}}>{a.icon}</span><strong>{a.name}</strong><small>{a.description}</small><time>{new Date(a.unlocked_at).toLocaleDateString('en-GB')}</time></article>)}</div>}</section></section>
  <section className="customer-challenge-section"><div className="section-heading"><div><span>History</span><h2>Completed challenges</h2></div><strong>{data?.completed?.length||0}</strong></div>{!data?.completed?.length?<p className="muted">Completed missions will stay here with their reward history.</p>:<div className="history-list">{data.completed.map(c=><article key={c.progress_id}><span style={{background:c.colour}}>{c.icon}</span><div><strong>{c.name}</strong><small>{c.restaurant_name} · {c.completed_at?dateTime.format(new Date(c.completed_at)):''}</small></div><div>{c.rewards.map((r,i)=><span key={i}>{rewardLabel(r)}{r.status?` · ${r.status}`:''}</span>)}</div></article>)}</div>}</section>
  {boards.length>0&&<section className="customer-challenge-section"><div className="section-heading"><div><span>Optional</span><h2>Leaderboards</h2></div></div><div className="board-grid">{boards.map(board=><article key={board.restaurant_id} className="board-card"><header><div><small>{board.restaurant_name}</small><h3>{board.metric.replaceAll('_',' ')}</h3></div><select aria-label={`Leaderboard privacy for ${board.restaurant_name}`} value={board.preference.leaderboard_visibility} onChange={e=>void savePrivacy(board,e.target.value,board.preference.nickname)}><option value="anonymous">Anonymous</option><option value="nickname">Nickname</option><option value="hidden">Opt out</option></select></header>{board.preference.leaderboard_visibility==='nickname'&&<form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void savePrivacy(board,'nickname',String(fd.get('nickname')||''))}}><input name="nickname" defaultValue={board.preference.nickname||''} minLength={2} maxLength={30} placeholder="Leaderboard nickname"/><button>Save</button></form>}<ol>{board.entries.map(entry=><li key={`${entry.rank}-${entry.display_name}`} className={entry.is_you?'you':''}><b>{entry.rank}</b><span>{entry.display_name}</span><strong>{entry.score}</strong></li>)}</ol></article>)}</div></section>}
 </main>
}
