import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import CustomerNotificationBell from './CustomerNotificationBell'
import './Referrals.css'

type Program = { program_id:string; restaurant_id:string; restaurant_name:string; restaurant_slug:string; code:string; referrer_reward:string; referee_reward:string; minimum_order_pence:number; qualifying_order_count:number; reward_delay_hours:number; ends_at:string|null; terms_text:string|null }
type Referral = { id:string; restaurant_name:string; friend_name:string; status:string; qualifying_order_count:number; qualifying_revenue_pence:number; registered_at:string|null; qualified_at:string|null; rewarded_at:string|null; created_at:string }
type Reward = { id:string; restaurant_name:string; recipient_role:string; reward_label:string; status:string; available_at:string; issued_at:string|null; created_at:string }
type Dashboard = { summary:{friends:number;qualified:number;rewarded:number;pending_rewards:number;available_rewards:number}; programs:Program[]; referrals:Referral[]; rewards:Reward[] }

const money = new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'})
const date = new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'})
const label = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase())

export default function CustomerReferrals(){
  const navigate=useNavigate(); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [copied,setCopied]=useState('')
  async function load(){setLoading(true);setError('');const{data:session}=await supabase.auth.getSession();if(!session.session){navigate('/account/login',{replace:true,state:{from:'/account/referrals'}});return}const{data,error:rpcError}=await supabase.rpc('get_customer_referral_dashboard');if(rpcError)setError(rpcError.message);else setDashboard(data as Dashboard);setLoading(false)}
  useEffect(()=>{void load()},[])
  async function share(program:Program){const url=`${window.location.origin}/ref/${encodeURIComponent(program.code)}`;await supabase.rpc('record_referral_share',{p_program_id:program.program_id});try{if(navigator.share)await navigator.share({title:`Try ${program.restaurant_name}`,text:`Use my ordered.food referral. You can earn ${program.referee_reward}.`,url});else{await navigator.clipboard.writeText(url);setCopied(program.program_id)}}catch{await navigator.clipboard.writeText(url);setCopied(program.program_id)}setTimeout(()=>setCopied(''),1800)}
  async function copy(program:Program){const url=`${window.location.origin}/ref/${encodeURIComponent(program.code)}`;await navigator.clipboard.writeText(url);await supabase.rpc('record_referral_share',{p_program_id:program.program_id});setCopied(program.program_id);setTimeout(()=>setCopied(''),1800)}
  if(loading)return <main className="referral-state">Loading referrals…</main>
  const summary=dashboard?.summary||{friends:0,qualified:0,rewarded:0,pending_rewards:0,available_rewards:0}
  return <main className="customer-referrals-page"><header className="customer-referrals-header"><Link to="/account">‹ Account</Link><div><span>Invite & earn</span><h1>Your referrals</h1><p>Share restaurant-specific links and track every reward.</p></div><CustomerNotificationBell/></header>{error&&<p className="referral-error" role="alert">{error}</p>}
  <section className="referral-metrics"><article><span>Friends joined</span><strong>{summary.friends}</strong></article><article><span>Qualified</span><strong>{summary.qualified}</strong></article><article><span>Rewards available</span><strong>{summary.available_rewards}</strong></article><article><span>Rewards pending</span><strong>{summary.pending_rewards}</strong></article></section>
  <section className="referral-section"><header><div><span>Your links</span><h2>Invite a friend</h2></div><small>Links appear after you complete an order with an active referral programme.</small></header><div className="referral-program-grid">{dashboard?.programs.length?dashboard.programs.map(program=><article className="referral-program-card" key={program.program_id}><div><span>{program.restaurant_name}</span><code>{program.code}</code></div><p>You get <strong>{program.referrer_reward}</strong>. Your friend gets <strong>{program.referee_reward}</strong>.</p><small>{program.qualifying_order_count} qualifying order{program.qualifying_order_count===1?'':'s'} · minimum {money.format(program.minimum_order_pence/100)}{program.reward_delay_hours?` · ${program.reward_delay_hours}h pending period`:''}</small><div className="referral-actions"><button type="button" className="primary" onClick={()=>void share(program)}>Share</button><button type="button" onClick={()=>void copy(program)}>{copied===program.program_id?'Copied':'Copy link'}</button><Link to={`/r/${program.restaurant_slug}`}>Restaurant</Link></div>{program.terms_text&&<details><summary>Programme terms</summary><p>{program.terms_text}</p></details>}</article>):<div className="referral-empty"><h3>No referral links yet</h3><p>Complete an order at a participating restaurant to unlock its referral link.</p><Link to="/restaurants">Find food</Link></div>}</div></section>
  <section className="referral-section"><header><div><span>Progress</span><h2>Friends you referred</h2></div></header><div className="referral-list">{dashboard?.referrals.length?dashboard.referrals.map(item=><article key={item.id}><div><strong>{item.friend_name}</strong><small>{item.restaurant_name} · joined {date.format(new Date(item.registered_at||item.created_at))}</small></div><div><span className={`status status-${item.status}`}>{label(item.status)}</span><small>{item.qualifying_order_count} qualifying order{item.qualifying_order_count===1?'':'s'} · {money.format(item.qualifying_revenue_pence/100)}</small></div></article>):<p>No friends have registered from your links yet.</p>}</div></section>
  <section className="referral-section"><header><div><span>Rewards</span><h2>Earned & pending</h2></div></header><div className="referral-list">{dashboard?.rewards.length?dashboard.rewards.map(reward=><article key={reward.id}><div><strong>{reward.reward_label}</strong><small>{reward.restaurant_name} · {reward.recipient_role==='referee'?'joining reward':'referrer reward'}</small></div><div><span className={`status status-${reward.status}`}>{label(reward.status)}</span><small>{reward.status==='pending'?`Available ${date.format(new Date(reward.available_at))}`:reward.issued_at?`Issued ${date.format(new Date(reward.issued_at))}`:''}</small></div></article>):<p>No referral rewards yet.</p>}</div></section></main>
}
