import { FormEvent, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './ReferralProgram.css'

type RewardType='store_credit'|'loyalty_points'|'fixed_value_voucher'|'percentage_voucher'|'free_delivery'
type Program={id?:string;is_enabled?:boolean;disabled_by_platform?:boolean;platform_disable_reason?:string|null;referrer_reward_type?:RewardType;referrer_reward_value?:number;referee_reward_type?:RewardType;referee_reward_value?:number;minimum_qualifying_order_pence?:number;qualifying_order_count?:number;reward_delay_hours?:number;starts_at?:string|null;ends_at?:string|null;maximum_referrals_per_customer?:number|null;campaign_referral_cap?:number|null;terms_text?:string|null}
type Summary={invited:number;registered:number;ordered:number;qualified:number;rewarded:number;rejected:number;conversion_rate:number;referred_revenue_pence:number;reward_cost_pence:number;loyalty_points_issued:number}
type Referral={id:string;status:string;qualifying_order_count:number;qualifying_revenue_pence:number;registered_at:string|null;qualified_at:string|null;rewarded_at:string|null;rejection_reason:string|null;created_at:string}
type Flag={id:string;flag_type:string;severity:string;status:string;created_at:string}
type Dashboard={program:Program;summary:Summary;referrals:Referral[];fraud_flags:Flag[]}
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});const date=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'});const text=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())
const rewardOptions:[RewardType,string][]=[['store_credit','Store credit'],['loyalty_points','Loyalty points'],['fixed_value_voucher','Fixed-value voucher'],['percentage_voucher','Percentage voucher'],['free_delivery','Free delivery']]
function inputValue(type:RewardType|undefined,value:number|undefined){if(type==='free_delivery')return '0';if(type==='percentage_voucher')return String((value||0)/100);return type==='loyalty_points'?String(value||0):String((value||0)/100)}
function rewardValue(type:RewardType,value:string){if(type==='free_delivery')return 0;if(type==='loyalty_points')return Math.max(1,Math.round(Number(value)||0));if(type==='percentage_voucher')return Math.max(1,Math.min(10000,Math.round((Number(value)||0)*100)));return Math.max(1,Math.round((Number(value)||0)*100))}
function localDate(value:string|null|undefined){return value?new Date(value).toISOString().slice(0,16):''}
export default function ReferralProgram(){const[dash,setDash]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[form,setForm]=useState({enabled:false,referrerType:'store_credit' as RewardType,referrerValue:'5',refereeType:'store_credit' as RewardType,refereeValue:'5',minimumOrder:'15',orderCount:'1',delayHours:'0',startsAt:'',endsAt:'',maxPerCustomer:'',campaignCap:'',terms:''})
async function load(){setLoading(true);const{data,error:rpcError}=await supabase.rpc('get_restaurant_referral_dashboard');if(rpcError)setError(rpcError.message);else{const d=data as Dashboard;setDash(d);const p=d.program||{};setForm({enabled:Boolean(p.is_enabled),referrerType:p.referrer_reward_type||'store_credit',referrerValue:inputValue(p.referrer_reward_type,p.referrer_reward_value),refereeType:p.referee_reward_type||'store_credit',refereeValue:inputValue(p.referee_reward_type,p.referee_reward_value),minimumOrder:String((p.minimum_qualifying_order_pence||0)/100),orderCount:String(p.qualifying_order_count||1),delayHours:String(p.reward_delay_hours||0),startsAt:localDate(p.starts_at),endsAt:localDate(p.ends_at),maxPerCustomer:p.maximum_referrals_per_customer?String(p.maximum_referrals_per_customer):'',campaignCap:p.campaign_referral_cap?String(p.campaign_referral_cap):'',terms:p.terms_text||''})}setLoading(false)}
useEffect(()=>{void load()},[])
async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');const{error:rpcError}=await supabase.rpc('save_restaurant_referral_program',{p_is_enabled:form.enabled,p_referrer_reward_type:form.referrerType,p_referrer_reward_value:rewardValue(form.referrerType,form.referrerValue),p_referee_reward_type:form.refereeType,p_referee_reward_value:rewardValue(form.refereeType,form.refereeValue),p_minimum_qualifying_order_pence:Math.max(0,Math.round((Number(form.minimumOrder)||0)*100)),p_qualifying_order_count:Math.max(1,Math.round(Number(form.orderCount)||1)),p_reward_delay_hours:Math.max(0,Math.round(Number(form.delayHours)||0)),p_starts_at:form.startsAt?new Date(form.startsAt).toISOString():null,p_ends_at:form.endsAt?new Date(form.endsAt).toISOString():null,p_maximum_referrals_per_customer:form.maxPerCustomer?Math.round(Number(form.maxPerCustomer)):null,p_campaign_referral_cap:form.campaignCap?Math.round(Number(form.campaignCap)):null,p_terms_text:form.terms||null});if(rpcError)setError(rpcError.message);else{setMessage('Referral programme saved.');await load()}setSaving(false)}
if(loading)return <main className="restaurant-referrals-page">Loading referrals…</main>;const s=dash?.summary||{invited:0,registered:0,ordered:0,qualified:0,rewarded:0,rejected:0,conversion_rate:0,referred_revenue_pence:0,reward_cost_pence:0,loyalty_points_issued:0}
return <main className="restaurant-referrals-page"><header className="restaurant-referrals-header"><div><span>Loyalty growth</span><h1>Referral programme</h1><p>Reward existing customers for bringing genuinely new customers to your restaurant.</p></div><nav><Link to="/loyalty">Loyalty</Link><Link to="/loyalty/rewards">Rewards</Link><button type="button" onClick={()=>void load()}>Refresh</button></nav></header>{dash?.program.disabled_by_platform&&<div className="referral-admin-lock"><strong>Programme disabled by ordered.food</strong><p>{dash.program.platform_disable_reason||'Contact platform support before re-enabling referrals.'}</p></div>}{error&&<p className="referral-form-error">{error}</p>}{message&&<p className="referral-form-success">{message}</p>}
<section className="restaurant-referral-metrics"><article><span>Link opens</span><strong>{s.invited}</strong></article><article><span>Registered</span><strong>{s.registered}</strong></article><article><span>Qualified</span><strong>{s.qualified}</strong></article><article><span>Conversion</span><strong>{Number(s.conversion_rate).toFixed(1)}%</strong></article><article><span>Referred revenue</span><strong>{money.format(s.referred_revenue_pence/100)}</strong></article><article><span>Reward cost</span><strong>{money.format(s.reward_cost_pence/100)}</strong></article></section>
<section className="restaurant-referral-grid"><form className="referral-settings-card" onSubmit={save}><header><div><span>Configuration</span><h2>Programme rules</h2></div><label className="toggle"><input type="checkbox" checked={form.enabled} disabled={Boolean(dash?.program.disabled_by_platform)} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>{form.enabled?'Enabled':'Disabled'}</span></label></header><div className="settings-grid"><RewardFields title="Referrer reward" type={form.referrerType} value={form.referrerValue} onType={v=>setForm({...form,referrerType:v})} onValue={v=>setForm({...form,referrerValue:v})}/><RewardFields title="Friend reward" type={form.refereeType} value={form.refereeValue} onType={v=>setForm({...form,refereeType:v})} onValue={v=>setForm({...form,refereeValue:v})}/><label>Minimum qualifying order (£)<input type="number" min="0" step="0.01" value={form.minimumOrder} onChange={e=>setForm({...form,minimumOrder:e.target.value})}/></label><label>Qualifying order count<input type="number" min="1" max="20" value={form.orderCount} onChange={e=>setForm({...form,orderCount:e.target.value})}/></label><label>Reward pending period (hours)<input type="number" min="0" max="2160" value={form.delayHours} onChange={e=>setForm({...form,delayHours:e.target.value})}/></label><label>Max referrals per customer<input type="number" min="1" placeholder="No limit" value={form.maxPerCustomer} onChange={e=>setForm({...form,maxPerCustomer:e.target.value})}/></label><label>Campaign referral cap<input type="number" min="1" placeholder="No limit" value={form.campaignCap} onChange={e=>setForm({...form,campaignCap:e.target.value})}/></label><label>Starts at<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends at<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><label className="wide">Customer-facing terms<textarea rows={4} value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})} placeholder="Explain eligibility, reward timing and exclusions."/></label></div><button className="save" disabled={saving||Boolean(dash?.program.disabled_by_platform)}>{saving?'Saving…':'Save referral programme'}</button></form>
<aside className="referral-risk-card"><header><span>Fraud monitoring</span><h2>Recent signals</h2></header>{dash?.fraud_flags.length?dash.fraud_flags.map(f=><article key={f.id}><div><strong>{text(f.flag_type)}</strong><small>{date.format(new Date(f.created_at))}</small></div><span className={`severity ${f.severity}`}>{text(f.severity)}</span></article>):<p>No suspicious referral signals detected.</p>}</aside></section>
<section className="referral-performance-card"><header><div><span>Latest activity</span><h2>Referral performance</h2></div><small>{s.rewarded} fully rewarded · {s.rejected} rejected</small></header><div className="referral-table-wrap"><table><thead><tr><th>Status</th><th>Registered</th><th>Qualifying orders</th><th>Revenue</th><th>Outcome</th></tr></thead><tbody>{dash?.referrals.length?dash.referrals.map(r=><tr key={r.id}><td><span className={`status status-${r.status}`}>{text(r.status)}</span></td><td>{date.format(new Date(r.registered_at||r.created_at))}</td><td>{r.qualifying_order_count}</td><td>{money.format(r.qualifying_revenue_pence/100)}</td><td>{r.rejection_reason?text(r.rejection_reason):r.rewarded_at?'Rewarded':r.qualified_at?'Qualified':'In progress'}</td></tr>):<tr><td colSpan={5}>No referrals yet.</td></tr>}</tbody></table></div></section></main>}
function RewardFields({title,type,value,onType,onValue}:{title:string;type:RewardType;value:string;onType:(v:RewardType)=>void;onValue:(v:string)=>void}){return <fieldset><legend>{title}</legend><label>Type<select value={type} onChange={e=>onType(e.target.value as RewardType)}>{rewardOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{type!=='free_delivery'&&<label>{type==='percentage_voucher'?'Percentage (%)':type==='loyalty_points'?'Points':'Value (£)'}<input type="number" min={type==='percentage_voucher'?'0.01':'1'} max={type==='percentage_voucher'?'100':undefined} step={type==='loyalty_points'?'1':'.01'} value={value} onChange={e=>onValue(e.target.value)}/></label>}</fieldset>}
