import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import '../subscription/Subscription.css'

type Member={id:string;user_id:string;email:string;role:'owner'|'manager'|'staff';status:'active'|'suspended';permissions:string[];custom_role_id:string|null;last_active_at:string|null;created_at:string}
type Invite={id:string;email:string;role:'manager'|'staff';custom_role_id:string|null;permissions:string[];expires_at:string;created_at:string}
type TeamRole={id:string;key:string;name:string;permissions:string[];is_system:boolean}
type Activity={id:number;actor_user_id:string|null;target_user_id:string|null;action:string;details:Record<string,unknown>;created_at:string}
type TeamPayload={members:Member[];invites:Invite[];roles:TeamRole[];activity:Activity[]}
const PERMISSIONS=['orders:view','orders:manage','menu:view','menu:manage','customers:view','marketing:view','marketing:manage','analytics:view','team:view','kds:view','settings:manage']
const date=(value:string)=>new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})

export default function Team(){
 const[searchParams]=useSearchParams(),navigate=useNavigate(),[team,setTeam]=useState<TeamPayload|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState<'manager'|'staff'>('staff'),[customRoleId,setCustomRoleId]=useState(''),[permissions,setPermissions]=useState<string[]>([]),[roleName,setRoleName]=useState(''),[rolePermissions,setRolePermissions]=useState<string[]>([])
 const inviteToken=searchParams.get('invite')
 const load=useCallback(async()=>{setLoading(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setLoading(false);return}const{data,error:loadError}=await supabase.rpc('get_restaurant_team');if(loadError){setError(loadError.message);setTeam(null)}else setTeam(data as TeamPayload);setLoading(false)},[])
 useEffect(()=>{void(async()=>{const{data:userData}=await supabase.auth.getUser();if(!userData.user){setLoading(false);return}if(inviteToken){setBusy('accept');const{error:acceptError}=await supabase.rpc('accept_restaurant_team_invite',{p_token:inviteToken});if(acceptError)setError(acceptError.message);else{setNotice('Invitation accepted. You now have access to the restaurant workspace.');navigate('/team',{replace:true})}setBusy('')}await load()})()},[inviteToken,load,navigate])
 async function invite(){if(!email.trim())return;setBusy('invite');setError('');setNotice('');const{data,error:invokeError}=await supabase.functions.invoke('restaurant-team-invite',{body:{email:email.trim(),role:inviteRole,custom_role_id:customRoleId||null,permissions}});if(invokeError||data?.error)setError(invokeError?.message||data?.error||'Unable to create invitation.');else{setNotice(data.emailed?`Invitation emailed to ${data.email}.`:`Invitation created. Email delivery failed; copy this link: ${data.invite_url}`);setEmail('');setPermissions([]);setCustomRoleId('');await load()}setBusy('')}
 async function memberAction(member:Member,action:'suspend'|'resume'|'remove'|'update',role?:'manager'|'staff'){setBusy(`${action}:${member.user_id}`);setError('');const{error:actionError}=await supabase.rpc('manage_restaurant_team_member',{p_user_id:member.user_id,p_action:action,p_role:role??null,p_permissions:null});if(actionError)setError(actionError.message);else{setNotice('Team member updated.');await load()}setBusy('')}
 async function revoke(id:string){setBusy(`revoke:${id}`);const{error:revokeError}=await supabase.rpc('revoke_restaurant_team_invite',{p_invite_id:id});if(revokeError)setError(revokeError.message);else await load();setBusy('')}
 async function createRole(){const key=roleName.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'');if(!key)return;setBusy('role');const{error:roleError}=await supabase.rpc('manage_restaurant_team_role',{p_action:'create',p_role_id:null,p_key:key,p_name:roleName.trim(),p_permissions:rolePermissions});if(roleError)setError(roleError.message);else{setRoleName('');setRolePermissions([]);setNotice('Custom role created.');await load()}setBusy('')}
 async function deleteRole(role:TeamRole){setBusy(`role:${role.id}`);const{error:roleError}=await supabase.rpc('manage_restaurant_team_role',{p_action:'delete',p_role_id:role.id,p_key:null,p_name:null,p_permissions:null});if(roleError)setError(roleError.message);else await load();setBusy('')}
 function toggle(value:string,list:string[],setter:(next:string[])=>void){setter(list.includes(value)?list.filter(item=>item!==value):[...list,value])}
 const activeCount=useMemo(()=>team?.members.filter(member=>member.status==='active').length??0,[team])
 if(loading)return <main className="subscription-page"><section className="subscription-panel">{busy==='accept'?'Accepting invitation…':'Loading team…'}</section></main>
 if(!team&&!inviteToken)return <main className="subscription-page"><section className="subscription-panel"><h1>Restaurant team</h1><p>You need to sign in with the email address that received the invitation, or use an existing restaurant owner account.</p><Link className="primary-button" to="/login">Sign in</Link></section></main>
 return <main className="subscription-page">
  <header className="subscription-header"><div><Link className="subscription-back" to="/dashboard">← Back to dashboard</Link><span className="subscription-kicker">Team management</span><h1>People, roles and permissions</h1><p>Invite staff, suspend access, assign operating roles and review team activity.</p></div><Link className="secondary-button" to="/subscription">Plan & billing</Link></header>
  {notice&&<div className="subscription-alert subscription-alert--success">{notice}</div>}{error&&<div className="subscription-alert subscription-alert--error" role="alert">{error}</div>}
  {team&&<><section className="subscription-panel"><span className="subscription-kicker">Team seats</span><h2>{activeCount} active member{activeCount===1?'':'s'}</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">Member</th><th align="left">Role</th><th align="left">Status</th><th align="right">Actions</th></tr></thead><tbody>{team.members.map(member=><tr key={member.id}><td><strong>{member.email}</strong><br/><small>Joined {date(member.created_at)}</small></td><td>{member.role}</td><td>{member.status}</td><td align="right">{member.role!=='owner'&&<div style={{display:'flex',gap:6,justifyContent:'flex-end',flexWrap:'wrap'}}><button className="secondary-button" type="button" onClick={()=>void memberAction(member,'update',member.role==='manager'?'staff':'manager')} disabled={Boolean(busy)}>Make {member.role==='manager'?'staff':'manager'}</button>{member.status==='active'?<button className="secondary-button" type="button" onClick={()=>void memberAction(member,'suspend')} disabled={Boolean(busy)}>Suspend</button>:<button className="secondary-button" type="button" onClick={()=>void memberAction(member,'resume')} disabled={Boolean(busy)}>Resume</button>}<button className="secondary-button" type="button" onClick={()=>void memberAction(member,'remove')} disabled={Boolean(busy)}>Remove</button></div>}</td></tr>)}</tbody></table></div></section>
  <section className="subscription-panel"><span className="subscription-kicker">Invite staff</span><h2>Add a team member</h2><div style={{display:'grid',gap:12,maxWidth:720}}><input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="staff@example.com"/><select value={inviteRole} onChange={event=>setInviteRole(event.target.value as 'manager'|'staff')}><option value="staff">Staff</option><option value="manager">Manager</option></select><select value={customRoleId} onChange={event=>setCustomRoleId(event.target.value)}><option value="">No custom role</option>{team.roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select><div><strong>Extra permissions</strong><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:8}}>{PERMISSIONS.map(permission=><label key={permission}><input type="checkbox" checked={permissions.includes(permission)} onChange={()=>toggle(permission,permissions,setPermissions)}/> {permission}</label>)}</div></div><button className="primary-button" type="button" onClick={()=>void invite()} disabled={busy==='invite'}>{busy==='invite'?'Inviting…':'Send invitation'}</button></div>{team.invites.length>0&&<><h3>Pending invitations</h3><ul>{team.invites.map(invite=><li key={invite.id}>{invite.email} · {invite.role} · expires {date(invite.expires_at)} <button type="button" onClick={()=>void revoke(invite.id)}>Revoke</button></li>)}</ul></>}</section>
  <section className="subscription-panel"><span className="subscription-kicker">Permission roles</span><h2>Custom roles</h2><div style={{display:'grid',gap:12,maxWidth:720}}><input value={roleName} onChange={event=>setRoleName(event.target.value)} placeholder="e.g. Shift supervisor"/><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{PERMISSIONS.map(permission=><label key={permission}><input type="checkbox" checked={rolePermissions.includes(permission)} onChange={()=>toggle(permission,rolePermissions,setRolePermissions)}/> {permission}</label>)}</div><button className="secondary-button" type="button" onClick={()=>void createRole()} disabled={busy==='role'}>Create role</button></div><ul>{team.roles.map(role=><li key={role.id}><strong>{role.name}</strong> · {role.permissions.join(', ')||'No permissions'} {!role.is_system&&<button type="button" onClick={()=>void deleteRole(role)}>Delete</button>}</li>)}</ul></section>
  <section className="subscription-panel"><span className="subscription-kicker">Activity log</span><h2>Recent team activity</h2>{team.activity.length===0?<p>No team changes recorded yet.</p>:<ul>{team.activity.slice(0,50).map(item=><li key={item.id}><strong>{item.action.replaceAll('_',' ')}</strong> · {date(item.created_at)}</li>)}</ul>}</section></>}
 </main>
}
