create or replace function private.ai_clamp(v numeric,lo numeric default 0,hi numeric default 100)
returns numeric language sql immutable set search_path='' as $$select least(hi,greatest(lo,coalesce(v,lo)))$$;
revoke all on function private.ai_clamp(numeric,numeric,numeric) from public;

create or replace function private.ai_put_insight(rid uuid,uid uuid,cat text,kind text,sev text,t text,s text,e text,conf numeric,ev jsonb,act jsonb,fp text,runid uuid,ttl interval default interval '14 days')
returns uuid language plpgsql security definer set search_path='' as $$
declare iid uuid;
begin
 insert into public.restaurant_ai_insights(restaurant_id,customer_user_id,category,insight_type,severity,title,summary,explanation,confidence,evidence,suggested_action,fingerprint,status,valid_until,run_id,generated_at)
 values(rid,uid,cat,kind,sev,t,s,e,private.ai_clamp(conf,0,1),coalesce(ev,'{}'),coalesce(act,'{}'),fp,'active',now()+ttl,runid,now())
 on conflict(restaurant_id,fingerprint) do update set customer_user_id=excluded.customer_user_id,category=excluded.category,insight_type=excluded.insight_type,severity=excluded.severity,title=excluded.title,summary=excluded.summary,explanation=excluded.explanation,confidence=excluded.confidence,evidence=excluded.evidence,suggested_action=excluded.suggested_action,status=case when public.restaurant_ai_insights.status='dismissed' then 'dismissed' else 'active' end,valid_until=excluded.valid_until,run_id=excluded.run_id,generated_at=now()
 returning id into iid;
 return iid;
end$$;
revoke all on function private.ai_put_insight(uuid,uuid,text,text,text,text,text,text,numeric,jsonb,jsonb,text,uuid,interval) from public;

create or replace function private.generate_restaurant_ai_intelligence(rid uuid,report_kind text default 'daily')
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 runid uuid;recent_rev numeric:=0;prev_rev numeric:=0;recent_orders numeric:=0;prev_orders numeric:=0;trend numeric:=1;conf numeric:=.45;
 wk timestamptz:=date_trunc('week',now())+interval '1 week';mo timestamptz:=date_trunc('month',now())+interval '1 month';
 growth numeric:=0;health numeric:=50;growth_score numeric:=50;customer_score numeric:=50;marketing_score numeric:=50;ops_score numeric:=50;
 avg_churn numeric:=50;repeat_pct numeric:=0;open_pct numeric:=0;conv_pct numeric:=0;cancel_pct numeric:=0;
 quiet_rec record;busy_rec record;send_rec record;x record;report_id uuid;scored int:=0;insights int:=0;
 rk text:=case when report_kind in('daily','weekly','monthly') then report_kind else 'daily' end;
begin
 insert into public.restaurant_ai_runs(restaurant_id,run_type,provider,model,methodology_version,input_window_days,status,trace)
 values(rid,case when report_kind='refresh' then 'refresh' else rk end,'internal','ordered-intelligence-v1','5.9.1',90,'running',jsonb_build_object('sources',jsonb_build_array('orders','order_items','marketing','loyalty','rewards','vip','referrals','challenges','fraud_flags'),'provider_adapter','internal')) returning id into runid;
 begin
  with universe as(
   select distinct customer_user_id uid from public.orders where restaurant_id=rid and customer_user_id is not null
   union select customer_user_id from public.customer_loyalty_accounts where restaurant_id=rid
   union select referrer_user_id from public.customer_referrals where restaurant_id=rid
   union select customer_user_id from public.customer_vip_memberships where restaurant_id=rid
  ),os as(
   select customer_user_id uid,count(*) filter(where payment_status='paid' and order_status<>'rejected')::numeric n,count(*) filter(where payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '90 days')::numeric n90,coalesce(sum(total_pence) filter(where payment_status='paid' and order_status<>'rejected'),0)::numeric ltv,coalesce(avg(total_pence) filter(where payment_status='paid' and order_status<>'rejected'),0)::numeric aov,min(created_at) filter(where payment_status='paid' and order_status<>'rejected') first_at,max(created_at) filter(where payment_status='paid' and order_status<>'rejected') last_at
   from public.orders where restaurant_id=rid and customer_user_id is not null group by customer_user_id
  ),m as(
   select customer_user_id uid,count(*)::numeric sent,count(*) filter(where opened_at is not null)::numeric opened,count(*) filter(where clicked_at is not null)::numeric clicked
   from public.restaurant_marketing_deliveries where restaurant_id=rid group by customer_user_id
  ),cv as(select customer_user_id uid,count(*)::numeric converted from public.restaurant_marketing_conversions where restaurant_id=rid group by customer_user_id),
  lo as(select customer_user_id uid,lifetime_points_earned::numeric pts,points_balance::numeric bal from public.customer_loyalty_accounts where restaurant_id=rid),
  rf as(select referrer_user_id uid,count(*) filter(where status in('qualified','rewarded'))::numeric refs from public.customer_referrals where restaurant_id=rid group by referrer_user_id),
  ch as(select customer_user_id uid,count(*) filter(where status='completed')::numeric done from public.customer_challenge_progress where restaurant_id=rid group by customer_user_id),
  b as(
   select u.uid,coalesce(os.n,0)n,coalesce(os.n90,0)n90,coalesce(os.ltv,0)ltv,coalesce(os.aov,0)aov,coalesce(m.sent,0)sent,coalesce(m.opened,0)opened,coalesce(m.clicked,0)clicked,coalesce(cv.converted,0)converted,coalesce(lo.pts,0)pts,coalesce(lo.bal,0)bal,coalesce(rf.refs,0)refs,coalesce(ch.done,0)done,
    case when os.last_at is null then 365 else extract(epoch from(now()-os.last_at))/86400 end recency,
    case when coalesce(os.n,0)>1 then greatest(7,extract(epoch from(os.last_at-os.first_at))/86400/nullif(os.n-1,0)) else 30 end cadence
   from universe u left join os using(uid) left join m using(uid) left join cv using(uid) left join lo using(uid) left join rf using(uid) left join ch using(uid)
  ),s as(
   select b.*,
    private.ai_clamp(case when n=0 then 95 else 20+80*(recency/greatest(30,cadence*2))-least(20,n90*5) end) churn,
    private.ai_clamp(n90*14+case when sent>0 then 30*opened/sent+35*clicked/sent else 0 end+least(20,converted*8)) engage,
    private.ai_clamp(least(50,pts/20)+least(20,bal/20)+done*10) loyal,
    private.ai_clamp(least(55,ltv/5000)+least(30,n*4)+least(15,n90*5)) vip,
    private.ai_clamp(refs*22+least(45,n90*6)+case when sent>0 then 25*clicked/sent else 0 end) refpot,
    private.ai_clamp(case when sent=0 then 25 else 100*(opened+2*clicked+3*converted)/nullif(sent*6,0) end) responsive
   from b
  )
  insert into public.restaurant_ai_customer_scores(restaurant_id,customer_user_id,lifetime_value_pence,predicted_future_value_pence,churn_risk,engagement_score,loyalty_score,vip_potential,referral_potential,campaign_responsiveness,return_probability,evidence,computed_at)
  select rid,uid,round(ltv)::bigint,round(aov*greatest(0,least(12,(90/greatest(7,cadence))*greatest(.05,1-churn/110))))::bigint,round(churn,2),round(engage,2),round(loyal,2),round(vip,2),round(refpot,2),round(responsive,2),round(private.ai_clamp((100-churn)*.7+engage*.3),2),jsonb_build_object('orders',n,'orders_90d',n90,'average_order_pence',round(aov),'days_since_last_order',round(recency,1),'estimated_cadence_days',round(cadence,1),'marketing_deliveries',sent,'opens',opened,'clicks',clicked,'conversions',converted,'lifetime_points',pts,'qualified_referrals',refs,'completed_challenges',done,'method','weighted behavioural scoring','protected_attributes_used',false),now()
  from s on conflict(restaurant_id,customer_user_id) do update set lifetime_value_pence=excluded.lifetime_value_pence,predicted_future_value_pence=excluded.predicted_future_value_pence,churn_risk=excluded.churn_risk,engagement_score=excluded.engagement_score,loyalty_score=excluded.loyalty_score,vip_potential=excluded.vip_potential,referral_potential=excluded.referral_potential,campaign_responsiveness=excluded.campaign_responsiveness,return_probability=excluded.return_probability,evidence=excluded.evidence,computed_at=now();
  get diagnostics scored=row_count;

  select coalesce(sum(total_pence),0),count(*) into recent_rev,recent_orders from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '28 days';
  select coalesce(sum(total_pence),0),count(*) into prev_rev,prev_orders from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '56 days' and created_at<now()-interval '28 days';
  trend:=least(1.5,greatest(.5,case when prev_rev>0 then recent_rev/prev_rev else 1 end));conf:=least(.92,.45+least(recent_orders,250)/550);
  insert into public.restaurant_ai_forecasts(restaurant_id,metric,horizon,period_start,period_end,predicted_value,lower_bound,upper_bound,confidence,explanation,evidence,run_id,generated_at)
  select rid,v.metric,v.horizon,v.start_at,v.end_at,round(v.val,2),round(v.val*(case when v.horizon='weekly' then .8 else .77 end),2),round(v.val*(case when v.horizon='weekly' then 1.2 else 1.23 end),2),case when v.horizon='weekly' then conf else greatest(.35,conf-.08) end,'Forecast uses recent paid-order behaviour, the preceding comparison window and a bounded trend factor. Confidence increases with observed order volume.',jsonb_build_object('recent_28d_revenue_pence',recent_rev,'previous_28d_revenue_pence',prev_rev,'recent_28d_orders',recent_orders,'trend_factor',round(trend,3)),runid,now()
  from(values
   ('revenue_pence','weekly',wk,wk+interval '7 days',(recent_rev/4)*trend),
   ('revenue_pence','monthly',mo,mo+interval '1 month',(recent_rev/28*30)*trend),
   ('delivery_orders_count','weekly',wk,wk+interval '7 days',(select count(*)/4.0*trend from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and fulfilment_method='delivery' and created_at>=now()-interval '28 days')),
   ('delivery_orders_count','monthly',mo,mo+interval '1 month',(select count(*)/28.0*30*trend from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and fulfilment_method='delivery' and created_at>=now()-interval '28 days')),
   ('collection_orders_count','weekly',wk,wk+interval '7 days',(select count(*)/4.0*trend from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and fulfilment_method='collection' and created_at>=now()-interval '28 days')),
   ('collection_orders_count','monthly',mo,mo+interval '1 month',(select count(*)/28.0*30*trend from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and fulfilment_method='collection' and created_at>=now()-interval '28 days'))
  )v(metric,horizon,start_at,end_at,val)
  on conflict(restaurant_id,metric,horizon,period_start) do update set predicted_value=excluded.predicted_value,lower_bound=excluded.lower_bound,upper_bound=excluded.upper_bound,confidence=excluded.confidence,explanation=excluded.explanation,evidence=excluded.evidence,run_id=excluded.run_id,generated_at=now();

  growth:=case when prev_rev>0 then 100*(recent_rev-prev_rev)/prev_rev else case when recent_rev>0 then 25 else 0 end end;
  perform private.ai_put_insight(rid,null,case when growth< -15 then 'revenue' else 'growth' end,case when growth< -15 then 'revenue_risk' else 'revenue_momentum' end,case when growth< -15 then 'warning' else 'opportunity' end,case when growth< -15 then 'Revenue is trending below the previous period' else 'Protect current revenue momentum' end,'Rolling revenue has been compared with the preceding equivalent period.','This is a transparent trend signal from paid, non-rejected orders; it is not a causal claim.',.78,jsonb_build_object('recent_28d_revenue_pence',recent_rev,'previous_28d_revenue_pence',prev_rev,'change_percent',round(growth,1)),jsonb_build_object('type','review_growth_plan','target','/insights/growth'),'revenue:trend',runid);insights:=insights+1;

  for x in select * from public.restaurant_ai_customer_scores where restaurant_id=rid and churn_risk>=70 and lifetime_value_pence>0 order by lifetime_value_pence desc limit 20 loop
   perform private.ai_put_insight(rid,x.customer_user_id,'customer','churn_risk',case when x.churn_risk>=90 then 'critical' else 'warning' end,'Customer may be at risk of churning','A customer with prior spend has a high behavioural churn score.','The score is driven by recency relative to estimated ordering cadence and recent engagement. No protected attributes are used.',least(.92,.55+x.churn_risk/250),jsonb_build_object('churn_risk',x.churn_risk,'lifetime_value_pence',x.lifetime_value_pence,'score_evidence',x.evidence),jsonb_build_object('type','create_marketing_campaign','segment_key','inactive_30_days','customer_user_id',x.customer_user_id,'suggested_discount_percent',case when x.churn_risk>=90 then 15 else 10 end,'target','/marketing/campaigns'),'customer:churn:'||x.customer_user_id::text,runid);insights:=insights+1;
  end loop;
  for x in select * from public.restaurant_ai_customer_scores where restaurant_id=rid and vip_potential>=75 order by vip_potential desc limit 10 loop
   if not exists(select 1 from public.customer_vip_memberships v where v.restaurant_id=rid and v.customer_user_id=x.customer_user_id and v.current_tier_id is not null) then perform private.ai_put_insight(rid,x.customer_user_id,'vip','vip_upgrade','opportunity','Strong VIP candidate identified','A high-value, high-frequency customer is not currently in a VIP tier.','VIP potential combines spend, frequency and recency; no membership change is automatic.',.8,jsonb_build_object('vip_potential',x.vip_potential,'lifetime_value_pence',x.lifetime_value_pence),jsonb_build_object('type','review_vip_candidate','target','/marketing/vip'),'vip:candidate:'||x.customer_user_id::text,runid,interval '30 days');insights:=insights+1;end if;
  end loop;
  for x in select * from public.restaurant_ai_customer_scores where restaurant_id=rid and referral_potential>=70 order by referral_potential desc limit 10 loop perform private.ai_put_insight(rid,x.customer_user_id,'referral','referral_campaign','opportunity','Customer has strong referral potential','High engagement or referral history makes this customer a promising advocate.','Referral potential uses referral history, recent ordering and campaign engagement.',.74,jsonb_build_object('referral_potential',x.referral_potential),jsonb_build_object('type','create_referral_campaign','target','/loyalty/referrals'),'referral:potential:'||x.customer_user_id::text,runid,interval '30 days');insights:=insights+1;end loop;
  for x in select s.customer_user_id,s.loyalty_score from public.restaurant_ai_customer_scores s where s.restaurant_id=rid and s.loyalty_score>=70 order by s.loyalty_score desc limit 10 loop perform private.ai_put_insight(rid,x.customer_user_id,'loyalty','reward_candidate','opportunity','Reward candidate identified','Strong loyalty behaviour suggests a recognition or reward may improve retention.','The recommendation uses existing loyalty activity and does not issue a reward automatically.',.72,jsonb_build_object('loyalty_score',x.loyalty_score),jsonb_build_object('type','review_reward','target','/loyalty/rewards'),'loyalty:reward:'||x.customer_user_id::text,runid,interval '30 days');insights:=insights+1;end loop;
  for x in select s.customer_user_id,s.engagement_score from public.restaurant_ai_customer_scores s where s.restaurant_id=rid and s.engagement_score>=70 order by s.engagement_score desc limit 10 loop perform private.ai_put_insight(rid,x.customer_user_id,'challenge','challenge_campaign','opportunity','Challenge campaign candidate','Highly engaged customers can be a good audience for missions or challenges.','This uses the existing challenge engine; it only suggests an audience and does not enrol customers automatically.',.68,jsonb_build_object('engagement_score',x.engagement_score),jsonb_build_object('type','create_challenge','target','/marketing/challenges'),'challenge:candidate:'||x.customer_user_id::text,runid,interval '30 days');insights:=insights+1;end loop;
  for x in select cp.user_id,cp.date_of_birth from public.customer_profiles cp join public.restaurant_ai_customer_scores s on s.customer_user_id=cp.user_id and s.restaurant_id=rid where cp.date_of_birth is not null and to_char(cp.date_of_birth,'MM-DD') between to_char(current_date,'MM-DD') and to_char(current_date+30,'MM-DD') limit 25 loop perform private.ai_put_insight(rid,x.user_id,'birthday','birthday_promotion','opportunity','Birthday promotion opportunity','A known customer birthday is approaching.','Use the existing birthday/milestone reward system rather than creating a duplicate reward.',.95,jsonb_build_object('birthday_month_day',to_char(x.date_of_birth,'MM-DD')),jsonb_build_object('type','review_birthday_reward','target','/marketing/milestones'),'birthday:'||x.user_id::text,runid,interval '31 days');insights:=insights+1;end loop;

  with h as(select extract(dow from created_at)::int dow,extract(hour from created_at)::int hour_of_day,count(*)::numeric orders,coalesce(sum(total_pence),0)::numeric revenue from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '90 days' group by 1,2) select * into quiet_rec from h order by orders,revenue limit 1;
  if quiet_rec.dow is not null then perform private.ai_put_insight(rid,null,'operations','quiet_period','opportunity','Target your quietest recurring period','A low-volume day/hour combination was identified from the last 90 days.','The suggested offer is bounded and should be validated against restaurant margins.',.7,jsonb_build_object('day_of_week',quiet_rec.dow,'hour',quiet_rec.hour_of_day,'orders',quiet_rec.orders),jsonb_build_object('type','create_marketing_campaign','suggested_discount_percent',10,'schedule',jsonb_build_object('day_of_week',quiet_rec.dow,'hour',quiet_rec.hour_of_day),'target','/marketing/campaigns'),'operations:quiet',runid);insights:=insights+1;end if;
  with h as(select extract(dow from created_at)::int dow,extract(hour from created_at)::int hour_of_day,count(*)::numeric orders,coalesce(sum(total_pence),0)::numeric revenue from public.orders where restaurant_id=rid and payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '90 days' group by 1,2) select * into busy_rec from h order by orders desc,revenue desc limit 1;
  if busy_rec.dow is not null then perform private.ai_put_insight(rid,null,'operations','busy_period','info','Plan staffing for the busiest recurring period','The highest-volume day/hour combination is a staffing and preparation signal.','This is a historical baseline; weather, holidays and special events are not modelled.',.75,jsonb_build_object('day_of_week',busy_rec.dow,'hour',busy_rec.hour_of_day,'orders',busy_rec.orders),jsonb_build_object('type','staffing_review','target','/insights/forecasting'),'operations:busy',runid);insights:=insights+1;end if;
  select extract(dow from coalesce(opened_at,clicked_at,sent_at))::int dow,extract(hour from coalesce(opened_at,clicked_at,sent_at))::int hour_of_day,count(*) n into send_rec from public.restaurant_marketing_deliveries where restaurant_id=rid and created_at>=now()-interval '180 days' and(opened_at is not null or clicked_at is not null) group by 1,2 order by n desc limit 1;
  if send_rec.dow is not null then perform private.ai_put_insight(rid,null,'marketing','best_send_time','opportunity','Use your strongest engagement window','Historical opens and clicks cluster in a recurring day/hour window.','The ranking uses existing delivery events and should be periodically retested.',.7,jsonb_build_object('day_of_week',send_rec.dow,'hour',send_rec.hour_of_day,'engagement_events',send_rec.n),jsonb_build_object('type','create_marketing_campaign','schedule',jsonb_build_object('day_of_week',send_rec.dow,'hour',send_rec.hour_of_day),'target','/marketing/campaigns'),'marketing:best-send',runid,interval '30 days');insights:=insights+1;end if;
  for x in select oi.menu_item_id,max(oi.item_name) name,sum(oi.quantity)::numeric units,sum(oi.line_total_pence)::numeric revenue from public.order_items oi join public.orders o on o.id=oi.order_id where o.restaurant_id=rid and o.payment_status='paid' and o.order_status<>'rejected' and o.created_at>=now()-interval '90 days' and oi.menu_item_id is not null group by oi.menu_item_id order by revenue asc limit 3 loop perform private.ai_put_insight(rid,null,'menu','menu_optimisation','opportunity','Review underperforming menu item: '||x.name,'This item contributes relatively little paid-order revenue.','Item cost data is not stored, so revenue contribution is used as an explicit profitability proxy; this is not gross profit.',.72,jsonb_build_object('menu_item_id',x.menu_item_id,'units',x.units,'revenue_pence',x.revenue,'profitability_proxy','revenue_contribution','cost_data_available',false),jsonb_build_object('type','review_menu_item','suggestions',jsonb_build_array('bundle','upsell','cross_sell','pricing_test'),'target','/menu'),'menu:underperformer:'||x.menu_item_id::text,runid,interval '30 days');insights:=insights+1;end loop;

  if exists(select 1 from public.referral_fraud_flags where restaurant_id=rid and status not in('resolved','dismissed','cleared','closed')) or exists(select 1 from public.customer_reward_fraud_flags where restaurant_id=rid and status not in('resolved','dismissed','cleared','closed')) or exists(select 1 from public.challenge_fraud_flags where restaurant_id=rid and status not in('resolved','dismissed','cleared','closed')) or exists(select 1 from public.vip_fraud_flags where restaurant_id=rid and status not in('resolved','dismissed','cleared','closed')) or exists(select 1 from public.orders o where o.restaurant_id=rid and o.payment_status='paid' and o.created_at>=now()-interval '30 days' and o.total_pence>3*(select coalesce(avg(total_pence),999999999) from public.orders where restaurant_id=rid and payment_status='paid' and created_at>=now()-interval '90 days')) then
   perform private.ai_put_insight(rid,null,'fraud','fraud_review','warning','Fraud and unusual activity signals need review','Existing fraud systems or an explicit order-value anomaly check have unresolved signals.','This combines existing reward/referral/challenge/VIP fraud flags with a transparent >3x recent-average order heuristic. It does not make a fraud determination.',.88,jsonb_build_object('uses_existing_fraud_infrastructure',true,'order_outlier_threshold','3x recent average'),jsonb_build_object('type','review_fraud_signals','target','/insights/recommendations'),'fraud:review',runid,interval '7 days');insights:=insights+1;
  end if;

  select coalesce(avg(churn_risk),50) into avg_churn from public.restaurant_ai_customer_scores where restaurant_id=rid;
  with c as(select customer_user_id,count(*) n from public.orders where restaurant_id=rid and customer_user_id is not null and payment_status='paid' and order_status<>'rejected' and created_at>=now()-interval '90 days' group by customer_user_id) select coalesce(100.0*count(*) filter(where n>=2)/nullif(count(*),0),0) into repeat_pct from c;
  select coalesce(100.0*count(*) filter(where opened_at is not null)/nullif(count(*),0),0) into open_pct from public.restaurant_marketing_deliveries where restaurant_id=rid and created_at>=now()-interval '90 days';
  select coalesce(100.0*count(distinct c.id)/nullif(count(distinct d.id),0),0) into conv_pct from public.restaurant_marketing_deliveries d left join public.restaurant_marketing_conversions c on c.delivery_id=d.id where d.restaurant_id=rid and d.created_at>=now()-interval '90 days';
  select coalesce(100.0*count(*) filter(where order_status in('rejected','cancelled'))/nullif(count(*),0),0) into cancel_pct from public.orders where restaurant_id=rid and created_at>=now()-interval '90 days';
  growth_score:=private.ai_clamp(50+growth/2);customer_score:=private.ai_clamp((100-avg_churn)*.65+repeat_pct*.35);marketing_score:=private.ai_clamp(20+open_pct*1.2+conv_pct*4);ops_score:=private.ai_clamp(100-cancel_pct);health:=private.ai_clamp(growth_score*.3+customer_score*.3+marketing_score*.2+ops_score*.2);
  insert into public.restaurant_ai_reports(restaurant_id,report_type,period_start,period_end,restaurant_health_score,growth_score,customer_health_score,marketing_score,operations_score,summary,sections,run_id,generated_at)
  values(rid,rk,case rk when 'monthly' then date_trunc('month',now()) when 'weekly' then date_trunc('week',now()) else date_trunc('day',now()) end,now(),round(health,2),round(growth_score,2),round(customer_score,2),round(marketing_score,2),round(ops_score,2),case when health>=80 then 'Restaurant health is strong. Protect retention and scale high-confidence opportunities.' when health>=60 then 'Restaurant health is stable with optimisation opportunities.' else 'Restaurant health needs attention. Prioritise revenue, churn and operational risks.' end,jsonb_build_object('revenue',jsonb_build_object('recent_28d_pence',recent_rev,'previous_28d_pence',prev_rev,'change_percent',round(growth,1)),'customers',jsonb_build_object('repeat_percent',round(repeat_pct,1),'average_churn_risk',round(avg_churn,1),'scored',scored),'marketing',jsonb_build_object('open_rate_percent',round(open_pct,1),'conversion_rate_percent',round(conv_pct,2)),'operations',jsonb_build_object('cancel_reject_percent',round(cancel_pct,1)),'methodology',jsonb_build_object('version','5.9.1','provider','internal','explainable',true)),runid,now())
  on conflict(restaurant_id,report_type,period_start) do update set period_end=excluded.period_end,restaurant_health_score=excluded.restaurant_health_score,growth_score=excluded.growth_score,customer_health_score=excluded.customer_health_score,marketing_score=excluded.marketing_score,operations_score=excluded.operations_score,summary=excluded.summary,sections=excluded.sections,run_id=excluded.run_id,generated_at=now() returning id into report_id;
  update public.restaurant_ai_runs set status='completed',completed_at=now(),trace=trace||jsonb_build_object('customers_scored',scored,'insights_generated',insights,'report_id',report_id) where id=runid;
  return jsonb_build_object('run_id',runid,'customers_scored',scored,'insights',insights,'report_id',report_id,'status','completed');
 exception when others then
  update public.restaurant_ai_runs set status='failed',error=sqlerrm,completed_at=now() where id=runid;
  raise;
 end;
end$$;
revoke all on function private.generate_restaurant_ai_intelligence(uuid,text) from public;
