revoke execute on function public.set_customer_date_of_birth(date) from public, anon;
revoke execute on function public.platform_set_customer_date_of_birth(uuid,date,text) from public, anon;
revoke execute on function public.get_customer_age_eligibility(uuid) from public, anon;
revoke execute on function public.save_restaurant_alcohol_setting(boolean) from public, anon;
revoke execute on function public.save_restaurant_birthday_program(boolean,text,integer,uuid,integer,integer,text[],text) from public, anon;
revoke execute on function public.save_restaurant_milestone_program(uuid,text,text,integer,boolean,text,integer,uuid,integer,integer,text[],text) from public, anon;
revoke execute on function public.delete_restaurant_milestone_program(uuid) from public, anon;
revoke execute on function public.get_customer_milestone_dashboard() from public, anon;
revoke execute on function public.get_restaurant_milestone_dashboard() from public, anon;
revoke execute on function public.get_restaurant_birthday_milestone_settings() from public, anon;
revoke execute on function public.get_platform_milestone_dashboard() from public, anon;
revoke execute on function public.platform_review_reward_fraud_flag(uuid,text,text) from public, anon;
revoke execute on function public.platform_set_birthday_program_disabled(uuid,boolean,text) from public, anon;
revoke execute on function public.platform_set_milestone_program_disabled(uuid,boolean,text) from public, anon;
revoke execute on function public.process_birthday_rewards(date) from public, anon, authenticated;
revoke execute on function public.process_reward_expiry_and_reminders(timestamptz) from public, anon, authenticated;

grant execute on function public.set_customer_date_of_birth(date) to authenticated;
grant execute on function public.platform_set_customer_date_of_birth(uuid,date,text) to authenticated;
grant execute on function public.get_customer_age_eligibility(uuid) to authenticated;
grant execute on function public.save_restaurant_alcohol_setting(boolean) to authenticated;
grant execute on function public.save_restaurant_birthday_program(boolean,text,integer,uuid,integer,integer,text[],text) to authenticated;
grant execute on function public.save_restaurant_milestone_program(uuid,text,text,integer,boolean,text,integer,uuid,integer,integer,text[],text) to authenticated;
grant execute on function public.delete_restaurant_milestone_program(uuid) to authenticated;
grant execute on function public.get_customer_milestone_dashboard() to authenticated;
grant execute on function public.get_restaurant_milestone_dashboard() to authenticated;
grant execute on function public.get_restaurant_birthday_milestone_settings() to authenticated;
grant execute on function public.get_platform_milestone_dashboard() to authenticated;
grant execute on function public.platform_review_reward_fraud_flag(uuid,text,text) to authenticated;
grant execute on function public.platform_set_birthday_program_disabled(uuid,boolean,text) to authenticated;
grant execute on function public.platform_set_milestone_program_disabled(uuid,boolean,text) to authenticated;
grant execute on function public.process_birthday_rewards(date) to service_role;
grant execute on function public.process_reward_expiry_and_reminders(timestamptz) to service_role;
