begin;

alter table public.restaurant_subscriptions
 add column if not exists pending_plan_id uuid references public.subscription_plans(id) on delete set null,
 add column if not exists pending_billing_interval text check(pending_billing_interval is null or pending_billing_interval in('monthly','annual'));

insert into public.restaurant_subscriptions(restaurant_id,plan_id,status,billing_interval,updated_at)
select r.id,p.id,'active','monthly',now() from public.restaurants r cross join lateral(select id from public.subscription_plans where code='free' and is_active limit 1)p where not exists(select 1 from public.restaurant_subscriptions s where s.restaurant_id=r.id);

create or replace function private.ensure_restaurant_free_subscription() returns trigger language plpgsql security definer set search_path='' as $$declare free_plan uuid;begin select id into free_plan from public.subscription_plans where code='free' and is_active limit 1;if free_plan is not null then insert into public.restaurant_subscriptions(restaurant_id,plan_id,status,billing_interval) values(new.id,free_plan,'active','monthly') on conflict(restaurant_id) do nothing;end if;return new;end$$;
drop trigger if exists ensure_restaurant_free_subscription on public.restaurants;
create trigger ensure_restaurant_free_subscription after insert on public.restaurants for each row execute function private.ensure_restaurant_free_subscription();

create or replace function public.get_restaurant_subscription_status() returns jsonb language plpgsql stable security definer set search_path='' as $$declare rid uuid;s public.restaurant_subscriptions%rowtype;p public.subscription_plans%rowtype;plans jsonb;allowed boolean:=false;reason text;begin select restaurant_id into rid from public.restaurant_members where user_id=(select auth.uid()) and status='active' order by created_at limit 1;if rid is null then raise exception 'Restaurant membership not found' using errcode='42501';end if;select * into s from public.restaurant_subscriptions where restaurant_id=rid;if s.id is not null then select * into p from public.subscription_plans where id=s.plan_id;end if;allowed:=s.id is not null and(s.status in('trialing','active') or(s.status='past_due' and s.grace_period_ends_at>now()) or s.comped_until>now());reason:=case when s.id is null then 'subscription_required' when s.comped_until>now() then 'comped' when s.status='past_due' and coalesce(s.grace_period_ends_at,'epoch'::timestamptz)<=now() then 'payment_overdue' else s.status end;select coalesce(jsonb_agg(to_jsonb(sp)-'stripe_monthly_price_id'-'stripe_annual_price_id' order by sp.sort_order),'[]'::jsonb) into plans from public.subscription_plans sp where sp.is_active and(sp.is_public or sp.id=s.plan_id);return jsonb_build_object('restaurant_id',rid,'subscription',case when s.id is null then null else jsonb_build_object('id',s.id,'status',s.status,'billing_interval',s.billing_interval,'trial_ends_at',s.trial_ends_at,'current_period_start',s.current_period_start,'current_period_end',s.current_period_end,'cancel_at_period_end',s.cancel_at_period_end,'grace_period_ends_at',s.grace_period_ends_at,'comped_until',s.comped_until,'pending_plan_id',s.pending_plan_id,'pending_billing_interval',s.pending_billing_interval,'plan',to_jsonb(p)-'stripe_monthly_price_id'-'stripe_annual_price_id') end,'plans',plans,'access',jsonb_build_object('allowed',allowed,'reason',reason));end$$;

create or replace function public.get_restaurant_billing_dashboard() returns jsonb language plpgsql stable security definer set search_path='' as $$declare rid uuid;result jsonb;has_subscription boolean;begin select restaurant_id into rid from public.restaurant_members where user_id=(select auth.uid()) and status='active' order by created_at limit 1;if rid is null then raise exception 'Restaurant membership not found' using errcode='42501';end if;select exists(select 1 from public.restaurant_subscriptions where restaurant_id=rid) into has_subscription;select jsonb_build_object('restaurant_id',rid,'subscription',case when s.id is null then null else jsonb_build_object('id',s.id,'status',s.status,'billing_interval',s.billing_interval,'trial_ends_at',s.trial_ends_at,'current_period_start',s.current_period_start,'current_period_end',s.current_period_end,'cancel_at_period_end',s.cancel_at_period_end,'grace_period_ends_at',s.grace_period_ends_at,'paused_at',s.paused_at,'resume_at',s.resume_at,'comped_until',s.comped_until,'custom_price_pence',s.custom_price_pence,'pending_plan_id',s.pending_plan_id,'pending_billing_interval',s.pending_billing_interval,'pending_plan',case when pp.id is null then null else to_jsonb(pp)-'stripe_monthly_price_id'-'stripe_annual_price_id' end,'plan',to_jsonb(p)-'stripe_monthly_price_id'-'stripe_annual_price_id') end,'plans',coalesce((select jsonb_agg(to_jsonb(sp)-'stripe_monthly_price_id'-'stripe_annual_price_id' order by sp.sort_order) from public.subscription_plans sp where sp.is_active and(sp.is_public or sp.id=s.plan_id)),'[]'::jsonb),'usage',case when has_subscription then public.get_restaurant_subscription_usage() else '{}'::jsonb end,'invoices',coalesce((select jsonb_agg(to_jsonb(i) order by i.created_at desc) from(select * from public.restaurant_subscription_invoices where restaurant_id=rid order by created_at desc limit 24)i),'[]'::jsonb),'credits',coalesce((select jsonb_agg(to_jsonb(c) order by c.created_at desc) from(select * from public.restaurant_billing_credits where restaurant_id=rid order by created_at desc limit 24)c),'[]'::jsonb),'enterprise',coalesce((select to_jsonb(e) from public.restaurant_enterprise_settings e where e.restaurant_id=rid),'{}'::jsonb)) into result from(select rid)x left join public.restaurant_subscriptions s on s.restaurant_id=rid left join public.subscription_plans p on p.id=s.plan_id left join public.subscription_plans pp on pp.id=s.pending_plan_id;return result;end$$;

revoke all on function public.get_restaurant_subscription_status() from public,anon,authenticated;
grant execute on function public.get_restaurant_subscription_status() to authenticated;

commit;
