-- Challenge-aware reward semantics and deep links.
create or replace function private.queue_campaign_notification(p_issuance_id uuid,p_event_type text,p_title text,p_body text)
returns void language plpgsql security definer set search_path='' as $$
declare rw public.customer_reward_issuances%rowtype; action text; dedupe text;
begin
  select * into rw from public.customer_reward_issuances where id=p_issuance_id;
  if not found then return; end if;
  action:=case rw.source_type when 'vip' then '/account/vip' when 'challenge' then '/account/challenges' else '/account/milestones' end;
  dedupe:='reward:'||rw.id::text||':'||p_event_type;
  insert into public.customer_notifications(customer_user_id,restaurant_id,notification_type,title,body,action_url,metadata,dedupe_key)
  values(rw.customer_user_id,rw.restaurant_id,p_event_type,p_title,p_body,action,jsonb_build_object('reward_issuance_id',rw.id,'source_type',rw.source_type,'source_id',rw.source_id),dedupe)
  on conflict do nothing;
  insert into public.reward_notification_queue(reward_issuance_id,restaurant_id,customer_user_id,event_type,subject,body,action_url,push_payload,dedupe_key)
  values(rw.id,rw.restaurant_id,rw.customer_user_id,p_event_type,p_title,p_body,action,jsonb_build_object('type',p_event_type,'reward_issuance_id',rw.id,'action_url',action),dedupe)
  on conflict do nothing;
end $$;

create or replace function private.issue_campaign_reward(p_issuance_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare rw public.customer_reward_issuances%rowtype; acct public.customer_credit_accounts%rowtype; lacct public.customer_loyalty_accounts%rowtype; ledger uuid; vid uuid; v_code text; title text; body text; duplicate_accounts integer:=0; dob_changed timestamptz; dob_set timestamptz; multiplier integer:=10000; base_value integer; reward_row public.restaurant_loyalty_rewards%rowtype; credit_entry text; loyalty_entry text;
begin
  select * into rw from public.customer_reward_issuances where id=p_issuance_id for update;
  if not found or rw.status<>'pending' then return; end if;
  if rw.source_type='birthday' then
    select p.date_of_birth_set_at,p.date_of_birth_last_changed_at into dob_set,dob_changed from public.customer_profiles p where p.user_id=rw.customer_user_id;
    if dob_set is not null and dob_set > now()-interval '14 days' then perform private.flag_campaign_fraud(rw.restaurant_id,rw.customer_user_id,rw.id,'birthday','recent_dob_set','high',jsonb_build_object('set_at',dob_set)); update public.customer_reward_issuances set status='blocked',metadata=metadata||jsonb_build_object('blocked_reason','recent_dob_set'),updated_at=now() where id=rw.id; return; end if;
    if dob_changed is not null and dob_changed > now()-interval '30 days' then perform private.flag_campaign_fraud(rw.restaurant_id,rw.customer_user_id,rw.id,'birthday','recent_dob_change','high',jsonb_build_object('changed_at',dob_changed)); update public.customer_reward_issuances set status='blocked',metadata=metadata||jsonb_build_object('blocked_reason','recent_dob_change'),updated_at=now() where id=rw.id; return; end if;
    select count(*) into duplicate_accounts from public.customer_profiles p join public.customer_profiles self on self.user_id=rw.customer_user_id where p.user_id<>self.user_id and p.date_of_birth=self.date_of_birth and self.phone is not null and p.phone is not null and regexp_replace(p.phone,'\\D','','g')=regexp_replace(self.phone,'\\D','','g');
    if duplicate_accounts>0 then perform private.flag_campaign_fraud(rw.restaurant_id,rw.customer_user_id,rw.id,'birthday','shared_phone_and_dob','high',jsonb_build_object('matching_accounts',duplicate_accounts)); update public.customer_reward_issuances set status='blocked',metadata=metadata||jsonb_build_object('blocked_reason','shared_phone_and_dob','matching_accounts',duplicate_accounts),updated_at=now() where id=rw.id; return; end if;
    multiplier:=private.get_customer_vip_multiplier(rw.restaurant_id,rw.customer_user_id,'birthday_bonus_multiplier');
    if multiplier>10000 and coalesce((rw.metadata->>'vip_multiplier_applied')::boolean,false)=false and rw.reward_type not in ('free_item','free_delivery') then base_value:=rw.reward_value; rw.reward_value:=round(base_value*multiplier/10000.0); update public.customer_reward_issuances set reward_value=rw.reward_value,metadata=metadata||jsonb_build_object('vip_multiplier_applied',true,'vip_multiplier_basis_points',multiplier,'base_reward_value',base_value),updated_at=now() where id=rw.id; end if;
  end if;
  credit_entry:=case rw.source_type when 'birthday' then 'birthday_credit' when 'vip' then 'vip_credit' when 'challenge' then 'challenge_credit' else 'milestone_credit' end;
  loyalty_entry:=case rw.source_type when 'birthday' then 'birthday_bonus' when 'vip' then 'vip_bonus' when 'challenge' then 'challenge_bonus' else 'milestone_bonus' end;
  if rw.reward_type='wallet_credit' then
    insert into public.customer_credit_accounts(restaurant_id,customer_user_id,balance_pence) values(rw.restaurant_id,rw.customer_user_id,0) on conflict(restaurant_id,customer_user_id) do nothing;
    select * into acct from public.customer_credit_accounts where restaurant_id=rw.restaurant_id and customer_user_id=rw.customer_user_id for update;
    insert into public.customer_credit_ledger(credit_account_id,restaurant_id,customer_user_id,amount_pence,entry_type,note,reward_issuance_id) values(acct.id,rw.restaurant_id,rw.customer_user_id,rw.reward_value,credit_entry,case rw.source_type when 'challenge' then 'Challenge reward' when 'birthday' then 'Birthday reward' when 'vip' then 'VIP reward' else 'Milestone reward' end,rw.id) on conflict(reward_issuance_id) where reward_issuance_id is not null do nothing returning id into ledger;
    if ledger is not null then update public.customer_credit_accounts set balance_pence=balance_pence+rw.reward_value,updated_at=now() where id=acct.id; end if;
    update public.customer_reward_issuances set status='available',issued_at=coalesce(issued_at,now()),campaign_cost_pence=reward_value,metadata=metadata||jsonb_build_object('credit_ledger_id',ledger),updated_at=now() where id=rw.id;
  elsif rw.reward_type='loyalty_points' then
    insert into public.customer_loyalty_accounts(restaurant_id,customer_user_id,points_balance,lifetime_points_earned,lifetime_points_redeemed) values(rw.restaurant_id,rw.customer_user_id,0,0,0) on conflict(restaurant_id,customer_user_id) do nothing;
    select * into lacct from public.customer_loyalty_accounts where restaurant_id=rw.restaurant_id and customer_user_id=rw.customer_user_id for update;
    insert into public.customer_loyalty_ledger(loyalty_account_id,restaurant_id,customer_user_id,points_delta,entry_type,note,reward_issuance_id) values(lacct.id,rw.restaurant_id,rw.customer_user_id,rw.reward_value,loyalty_entry,case rw.source_type when 'challenge' then 'Challenge reward' when 'birthday' then 'Birthday reward' when 'vip' then 'VIP reward' else 'Milestone reward' end,rw.id) on conflict(reward_issuance_id) where reward_issuance_id is not null do nothing returning id into ledger;
    if ledger is not null then update public.customer_loyalty_accounts set points_balance=points_balance+rw.reward_value,lifetime_points_earned=lifetime_points_earned+rw.reward_value,updated_at=now() where id=lacct.id; end if;
    update public.customer_reward_issuances set status='available',issued_at=coalesce(issued_at,now()),loyalty_ledger_id=coalesce(loyalty_ledger_id,ledger),updated_at=now() where id=rw.id;
  else
    if rw.reward_catalogue_id is null then raise exception 'Reward catalogue entry is missing'; end if;
    select * into reward_row from public.restaurant_loyalty_rewards where id=rw.reward_catalogue_id;
    loop v_code:=case rw.source_type when 'birthday' then 'BD-' when 'vip' then 'VIP-' when 'challenge' then 'CH-' else 'MS-' end||upper(substr(encode(extensions.gen_random_bytes(10),'hex'),1,14)); exit when not exists(select 1 from public.customer_reward_vouchers v where v.restaurant_id=rw.restaurant_id and v.code=v_code); end loop;
    insert into public.customer_reward_vouchers(reward_id,restaurant_id,customer_user_id,code,points_spent,expires_at,reward_issuance_id,override_fixed_value_pence,override_percentage_basis_points,benefit_source_type,benefit_source_id)
    values(rw.reward_catalogue_id,rw.restaurant_id,rw.customer_user_id,v_code,0,rw.expires_at,rw.id,case when rw.reward_type in ('fixed_discount','voucher') and rw.reward_value<>coalesce(reward_row.fixed_value_pence,0) then rw.reward_value else null end,case when rw.reward_type='percentage_discount' and rw.reward_value<>coalesce(reward_row.percentage_basis_points,0) then least(rw.reward_value,10000) else null end,rw.source_type,rw.source_id)
    on conflict(reward_issuance_id) where reward_issuance_id is not null do nothing returning id into vid;
    if vid is null then select id into vid from public.customer_reward_vouchers where reward_issuance_id=rw.id; end if;
    update public.customer_reward_issuances set status='available',issued_at=coalesce(issued_at,now()),voucher_id=vid,campaign_cost_pence=case when reward_type in('fixed_discount','voucher') then reward_value else campaign_cost_pence end,updated_at=now() where id=rw.id;
  end if;
  title:=case rw.source_type when 'birthday' then 'Birthday reward available' when 'vip' then 'VIP reward available' when 'challenge' then 'Challenge reward earned' else 'Reward earned' end;
  body:=coalesce(rw.metadata->>'campaign_message',case rw.source_type when 'birthday' then 'Happy Birthday! Your reward is ready.' when 'vip' then 'A new VIP reward is ready in your account.' when 'challenge' then 'Your challenge reward is ready in your account.' else 'You reached a new milestone. Your reward is ready!' end);
  perform private.queue_campaign_notification(rw.id,case rw.source_type when 'birthday' then 'birthday_reward_available' when 'vip' then 'vip_reward_available' when 'challenge' then 'challenge_reward_earned' else 'reward_earned' end,title,body);
end $$;

create or replace function private.issue_challenge_reward(p_progress_id uuid,p_reward_id uuid,p_order_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$
declare cp public.customer_challenge_progress%rowtype; rw public.restaurant_challenge_rewards%rowtype; c public.restaurant_challenges%rowtype; iid uuid; mapped text; v_source_key text; ledger uuid; acct public.customer_loyalty_accounts%rowtype; vip_key text;
begin
  select * into cp from public.customer_challenge_progress where id=p_progress_id; select * into rw from public.restaurant_challenge_rewards where id=p_reward_id and challenge_id=cp.challenge_id; select * into c from public.restaurant_challenges where id=cp.challenge_id;
  if cp.id is null or rw.id is null then return null; end if;
  v_source_key:=cp.cycle_key||':'||rw.id::text;
  mapped:=case rw.reward_type when 'fixed_voucher' then 'fixed_discount' when 'percentage_voucher' then 'percentage_discount' when 'store_credit' then 'wallet_credit' else rw.reward_type end;
  insert into public.customer_reward_issuances(restaurant_id,customer_user_id,source_type,source_id,source_key,triggering_order_id,reward_type,reward_value,reward_catalogue_id,status,eligible_at,expires_at,metadata)
  values(cp.restaurant_id,cp.customer_user_id,'challenge',cp.challenge_id,v_source_key,p_order_id,mapped,rw.reward_value,rw.reward_catalogue_id,'pending',now(),case when rw.validity_days is null then null else now()+make_interval(days=>rw.validity_days) end,jsonb_build_object('challenge_name',c.name,'challenge_progress_id',cp.id,'challenge_reward_id',rw.id,'campaign_message','Challenge complete: '||c.name)) on conflict(restaurant_id,customer_user_id,source_type,source_id,source_key) do nothing returning id into iid;
  if iid is null then select i.id into iid from public.customer_reward_issuances i where i.restaurant_id=cp.restaurant_id and i.customer_user_id=cp.customer_user_id and i.source_type='challenge' and i.source_id=cp.challenge_id and i.source_key=v_source_key; return iid; end if;
  if rw.reward_type='bonus_stamps' then perform public.add_customer_stamp_progress(rw.stamp_program_id,cp.customer_user_id,greatest(rw.reward_value,1),'challenge_bonus','Challenge reward: '||c.name,null); update public.customer_reward_issuances set status='available',issued_at=now(),campaign_cost_pence=0,updated_at=now() where id=iid; perform private.queue_campaign_notification(iid,'challenge_reward_earned','Challenge reward earned','Bonus stamps from '||c.name||' are now on your stamp card.');
  elsif rw.reward_type='vip_bonus' then vip_key:=coalesce(nullif(rw.config->>'metric_key',''),'challenge_bonus'); insert into public.customer_vip_custom_metrics(restaurant_id,customer_user_id,metric_key,metric_value,updated_by) values(cp.restaurant_id,cp.customer_user_id,vip_key,greatest(rw.reward_value,1),null) on conflict(restaurant_id,customer_user_id,metric_key) do update set metric_value=public.customer_vip_custom_metrics.metric_value+excluded.metric_value,updated_at=now(); perform private.evaluate_customer_vip_tier(cp.restaurant_id,cp.customer_user_id,'challenge_reward','system',null); update public.customer_reward_issuances set status='available',issued_at=now(),updated_at=now() where id=iid; perform private.queue_campaign_notification(iid,'challenge_reward_earned','Challenge reward earned','Your VIP progress bonus from '||c.name||' has been applied.');
  elsif rw.reward_type='referral_bonus' then insert into public.customer_loyalty_accounts(restaurant_id,customer_user_id,points_balance,lifetime_points_earned,lifetime_points_redeemed) values(cp.restaurant_id,cp.customer_user_id,0,0,0) on conflict(restaurant_id,customer_user_id) do nothing; select * into acct from public.customer_loyalty_accounts where restaurant_id=cp.restaurant_id and customer_user_id=cp.customer_user_id for update; insert into public.customer_loyalty_ledger(loyalty_account_id,restaurant_id,customer_user_id,points_delta,entry_type,note,reward_issuance_id) values(acct.id,cp.restaurant_id,cp.customer_user_id,greatest(rw.reward_value,1),'challenge_bonus','Referral challenge bonus',iid) on conflict(reward_issuance_id) where reward_issuance_id is not null do nothing returning id into ledger; if ledger is not null then update public.customer_loyalty_accounts set points_balance=points_balance+greatest(rw.reward_value,1),lifetime_points_earned=lifetime_points_earned+greatest(rw.reward_value,1),updated_at=now() where id=acct.id; end if; update public.customer_reward_issuances set status='available',issued_at=now(),loyalty_ledger_id=ledger,updated_at=now() where id=iid; perform private.queue_campaign_notification(iid,'challenge_reward_earned','Challenge reward earned','Your referral challenge bonus from '||c.name||' has been applied.');
  else perform private.issue_campaign_reward(iid); end if;
  return iid;
end $$;

create or replace function private.process_stamp_challenges() returns trigger language plpgsql security definer set search_path='' as $$ declare c record; begin if new.customer_user_id is null then return new; end if; for c in select id from public.restaurant_challenges where restaurant_id=new.restaurant_id and is_active and platform_disabled_at is null and starts_at<=new.created_at and (ends_at is null or ends_at>=new.created_at) loop perform private.evaluate_customer_challenge(c.id,new.customer_user_id,'stamp:'||new.id::text,new.order_id); end loop; perform private.evaluate_customer_achievements(new.restaurant_id,new.customer_user_id,new.order_id); return new; end $$;
drop trigger if exists challenge_stamp_event_trigger on public.customer_stamp_events;
create trigger challenge_stamp_event_trigger after insert on public.customer_stamp_events for each row execute function private.process_stamp_challenges();
create or replace function private.process_loyalty_challenges() returns trigger language plpgsql security definer set search_path='' as $$ declare c record; begin if new.customer_user_id is null then return new; end if; for c in select id from public.restaurant_challenges where restaurant_id=new.restaurant_id and is_active and platform_disabled_at is null and starts_at<=new.created_at and (ends_at is null or ends_at>=new.created_at) loop perform private.evaluate_customer_challenge(c.id,new.customer_user_id,'points:'||new.id::text,new.order_id); end loop; perform private.evaluate_customer_achievements(new.restaurant_id,new.customer_user_id,new.order_id); return new; end $$;
drop trigger if exists challenge_loyalty_event_trigger on public.customer_loyalty_ledger;
create trigger challenge_loyalty_event_trigger after insert on public.customer_loyalty_ledger for each row execute function private.process_loyalty_challenges();
create or replace function private.process_referral_challenges() returns trigger language plpgsql security definer set search_path='' as $$ declare c record; begin if new.status='qualified' and (tg_op='INSERT' or old.status is distinct from new.status) then for c in select id from public.restaurant_challenges where restaurant_id=new.restaurant_id and is_active and platform_disabled_at is null and starts_at<=coalesce(new.qualified_at,now()) and (ends_at is null or ends_at>=coalesce(new.qualified_at,now())) loop perform private.evaluate_customer_challenge(c.id,new.referrer_user_id,'referral:'||new.id::text,null); end loop; perform private.evaluate_customer_achievements(new.restaurant_id,new.referrer_user_id,null); end if; return new; end $$;
drop trigger if exists challenge_referral_trigger on public.customer_referrals;
create trigger challenge_referral_trigger after insert or update of status on public.customer_referrals for each row execute function private.process_referral_challenges();
create or replace function private.process_vip_challenges() returns trigger language plpgsql security definer set search_path='' as $$ declare c record; begin if new.current_tier_id is distinct from old.current_tier_id then for c in select id from public.restaurant_challenges where restaurant_id=new.restaurant_id and is_active and platform_disabled_at is null and starts_at<=now() and (ends_at is null or ends_at>=now()) loop perform private.evaluate_customer_challenge(c.id,new.customer_user_id,'vip:'||new.membership_version::text,null); end loop; perform private.evaluate_customer_achievements(new.restaurant_id,new.customer_user_id,null); end if; return new; end $$;
drop trigger if exists challenge_vip_membership_trigger on public.customer_vip_memberships;
create trigger challenge_vip_membership_trigger after update of current_tier_id on public.customer_vip_memberships for each row execute function private.process_vip_challenges();
create or replace function private.announce_new_challenge() returns trigger language plpgsql security definer set search_path='' as $$ declare u record; begin if not new.is_active or new.platform_disabled_at is not null or new.visibility='hidden' then return new; end if; for u in select distinct customer_user_id from (select customer_user_id from public.orders where restaurant_id=new.restaurant_id and customer_user_id is not null union select customer_user_id from public.customer_loyalty_accounts where restaurant_id=new.restaurant_id union select customer_user_id from public.customer_stamp_cards where restaurant_id=new.restaurant_id union select referrer_user_id from public.customer_referrals where restaurant_id=new.restaurant_id union select customer_user_id from public.customer_vip_memberships where restaurant_id=new.restaurant_id) candidates loop if private.challenge_audience_matches(new,u.customer_user_id) then perform private.queue_challenge_notification(new.id,null,null,new.restaurant_id,u.customer_user_id,'challenge_new','New challenge',new.name||' is now available.','challenge-new:'||new.id::text||':'||u.customer_user_id::text); end if; end loop; return new; end $$;
drop trigger if exists announce_new_challenge_trigger on public.restaurant_challenges;
create trigger announce_new_challenge_trigger after insert on public.restaurant_challenges for each row execute function private.announce_new_challenge();
create or replace function public.get_customer_challenge_leaderboards() returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid(); s record; result jsonb:='[]'::jsonb; rows jsonb;
begin
  if uid is null then raise exception 'Authentication required' using errcode='42501'; end if;
  for s in select ls.*,r.name restaurant_name from public.restaurant_leaderboard_settings ls join public.restaurants r on r.id=ls.restaurant_id where ls.is_enabled and (exists(select 1 from public.orders o where o.restaurant_id=ls.restaurant_id and o.customer_user_id=uid) or exists(select 1 from public.customer_challenge_progress cp where cp.restaurant_id=ls.restaurant_id and cp.customer_user_id=uid)) loop
    select coalesce(jsonb_agg(jsonb_build_object('rank',rank_no,'display_name',display_name,'score',score,'is_you',customer_user_id=uid) order by rank_no),'[]'::jsonb) into rows from (select x.customer_user_id,row_number() over(order by x.score desc,x.customer_user_id)::int rank_no,case when x.customer_user_id=uid then 'You' when coalesce(pref.leaderboard_visibility,'anonymous')='nickname' then coalesce(pref.nickname,'Player') else 'Anonymous' end display_name,x.score from (select u.customer_user_id,case s.metric when 'points' then coalesce((select a.points_balance from public.customer_loyalty_accounts a where a.restaurant_id=s.restaurant_id and a.customer_user_id=u.customer_user_id),0) when 'challenges' then (select count(*) from public.customer_challenge_progress p where p.restaurant_id=s.restaurant_id and p.customer_user_id=u.customer_user_id and p.status='completed') when 'referrals' then (select count(*) from public.customer_referrals r where r.restaurant_id=s.restaurant_id and r.referrer_user_id=u.customer_user_id and r.status='qualified') when 'stamps' then coalesce((select sum(e.stamps_delta) filter(where e.stamps_delta>0) from public.customer_stamp_events e where e.restaurant_id=s.restaurant_id and e.customer_user_id=u.customer_user_id),0) else (select count(*) from public.orders o where o.restaurant_id=s.restaurant_id and o.customer_user_id=u.customer_user_id and o.payment_status='paid' and o.order_status='completed') end::bigint score from (select distinct customer_user_id from public.orders where restaurant_id=s.restaurant_id and customer_user_id is not null union select distinct customer_user_id from public.customer_challenge_progress where restaurant_id=s.restaurant_id)u)x left join public.customer_gamification_preferences pref on pref.restaurant_id=s.restaurant_id and pref.customer_user_id=x.customer_user_id where coalesce(pref.leaderboard_visibility,'anonymous')<>'hidden' order by x.score desc limit s.max_entries) ranked;
    result:=result||jsonb_build_array(jsonb_build_object('restaurant_id',s.restaurant_id,'restaurant_name',s.restaurant_name,'metric',s.metric,'entries',rows,'preference',coalesce((select to_jsonb(p)-'customer_user_id' from public.customer_gamification_preferences p where p.restaurant_id=s.restaurant_id and p.customer_user_id=uid),jsonb_build_object('restaurant_id',s.restaurant_id,'leaderboard_visibility','anonymous','nickname',null))));
  end loop;
  return result;
end $$;
revoke all on function public.get_customer_challenge_leaderboards() from public;
grant execute on function public.get_customer_challenge_leaderboards() to authenticated;
