create or replace function public.save_restaurant_group_department(p_group_id uuid,p_department_id uuid,p_restaurant_id uuid,p_parent_department_id uuid,p_name text,p_department_type text default 'custom') returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'staff:manage',p_restaurant_id) then raise exception 'Staff management permission required' using errcode='42501'; end if;
 if p_restaurant_id is not null and not exists(select 1 from public.restaurant_group_locations where group_id=p_group_id and restaurant_id=p_restaurant_id) then raise exception 'Restaurant is outside this organisation'; end if;
 if p_parent_department_id is not null and not exists(select 1 from public.restaurant_group_departments where id=p_parent_department_id and group_id=p_group_id) then raise exception 'Parent department is outside this organisation'; end if;
 if p_department_id is null then insert into public.restaurant_group_departments(group_id,restaurant_id,parent_department_id,name,department_type) values(p_group_id,p_restaurant_id,p_parent_department_id,btrim(p_name),coalesce(nullif(btrim(p_department_type),''),'custom')) returning id into v_id;
 else update public.restaurant_group_departments set restaurant_id=p_restaurant_id,parent_department_id=p_parent_department_id,name=btrim(p_name),department_type=coalesce(nullif(btrim(p_department_type),''),'custom'),updated_at=now() where id=p_department_id and group_id=p_group_id returning id into v_id; end if;
 if v_id is null then raise exception 'Department not found'; end if; perform private.restaurant_group_log(p_group_id,'department.saved','department',v_id,null,jsonb_build_object('restaurant_id',p_restaurant_id,'name',p_name)); return v_id; end $$;
create or replace function public.assign_restaurant_group_location(p_group_id uuid,p_restaurant_id uuid,p_brand_id uuid default null,p_region_id uuid default null,p_currency text default null,p_country_code text default null) returns void language plpgsql security definer set search_path='' as $$
begin if not private.restaurant_group_member_permission(p_group_id,'locations:manage',p_restaurant_id,p_brand_id,p_region_id) then raise exception 'Location management permission required' using errcode='42501'; end if;
 update public.restaurant_group_locations set brand_id=p_brand_id,region_id=p_region_id,currency=coalesce(upper(nullif(btrim(p_currency),'')),currency),country_code=coalesce(upper(nullif(btrim(p_country_code),'')),country_code),updated_at=now() where group_id=p_group_id and restaurant_id=p_restaurant_id;
 if not found then raise exception 'Restaurant is outside this organisation'; end if; perform private.restaurant_group_log(p_group_id,'location.structure_updated','restaurant',p_restaurant_id,null,jsonb_build_object('brand_id',p_brand_id,'region_id',p_region_id)); end $$;
create or replace function public.save_restaurant_group_menu_template(p_group_id uuid,p_template_id uuid,p_name text,p_scope_type text,p_brand_id uuid default null,p_region_id uuid default null,p_status text default 'draft',p_auto_publish boolean default false) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'menu:manage',null,p_brand_id,p_region_id) then raise exception 'Menu management permission required' using errcode='42501'; end if;
 if p_template_id is null then insert into public.restaurant_group_menu_templates(group_id,name,scope_type,brand_id,region_id,status,auto_publish,created_by) values(p_group_id,btrim(p_name),p_scope_type,p_brand_id,p_region_id,p_status,p_auto_publish,auth.uid()) returning id into v_id;
 else update public.restaurant_group_menu_templates set name=btrim(p_name),scope_type=p_scope_type,brand_id=p_brand_id,region_id=p_region_id,status=p_status,auto_publish=p_auto_publish,updated_at=now() where id=p_template_id and group_id=p_group_id returning id into v_id; end if;
 if v_id is null then raise exception 'Menu template not found'; end if; perform private.restaurant_group_log(p_group_id,'menu.template_saved','menu_template',v_id,null,jsonb_build_object('name',p_name,'scope_type',p_scope_type,'auto_publish',p_auto_publish)); return v_id; end $$;
create or replace function public.save_restaurant_group_menu_category(p_template_id uuid,p_category_id uuid,p_name text,p_description text default null,p_sort_order integer default 0,p_is_active boolean default true) returns uuid language plpgsql security definer set search_path='' as $$
declare v_group uuid; v_id uuid;
begin select group_id into v_group from public.restaurant_group_menu_templates where id=p_template_id; if v_group is null or not private.restaurant_group_member_permission(v_group,'menu:manage') then raise exception 'Menu management permission required' using errcode='42501'; end if;
 if p_category_id is null then insert into public.restaurant_group_menu_categories(template_id,name,description,sort_order,is_active) values(p_template_id,btrim(p_name),nullif(btrim(p_description),''),p_sort_order,p_is_active) returning id into v_id;
 else update public.restaurant_group_menu_categories set name=btrim(p_name),description=nullif(btrim(p_description),''),sort_order=p_sort_order,is_active=p_is_active,updated_at=now() where id=p_category_id and template_id=p_template_id returning id into v_id; end if; if v_id is null then raise exception 'Menu category not found'; end if; return v_id; end $$;
create or replace function public.save_restaurant_group_menu_item(p_template_id uuid,p_item_id uuid,p_category_id uuid,p_name text,p_description text,p_base_price_pence integer,p_image_url text default null,p_is_available boolean default true,p_is_vegetarian boolean default false,p_is_vegan boolean default false,p_sort_order integer default 0) returns uuid language plpgsql security definer set search_path='' as $$
declare v_group uuid;v_id uuid;
begin select group_id into v_group from public.restaurant_group_menu_templates where id=p_template_id; if v_group is null or not private.restaurant_group_member_permission(v_group,'menu:manage') then raise exception 'Menu management permission required' using errcode='42501'; end if; if not exists(select 1 from public.restaurant_group_menu_categories where id=p_category_id and template_id=p_template_id) then raise exception 'Category is outside this template'; end if;
 if p_item_id is null then insert into public.restaurant_group_menu_items(template_id,category_id,name,description,base_price_pence,image_url,is_available,is_vegetarian,is_vegan,sort_order) values(p_template_id,p_category_id,btrim(p_name),nullif(btrim(p_description),''),p_base_price_pence,nullif(btrim(p_image_url),''),p_is_available,p_is_vegetarian,p_is_vegan,p_sort_order) returning id into v_id;
 else update public.restaurant_group_menu_items set category_id=p_category_id,name=btrim(p_name),description=nullif(btrim(p_description),''),base_price_pence=p_base_price_pence,image_url=nullif(btrim(p_image_url),''),is_available=p_is_available,is_vegetarian=p_is_vegetarian,is_vegan=p_is_vegan,sort_order=p_sort_order,updated_at=now() where id=p_item_id and template_id=p_template_id returning id into v_id; end if; if v_id is null then raise exception 'Menu item not found'; end if; return v_id; end $$;
create or replace function public.save_restaurant_group_menu_override(p_group_id uuid,p_restaurant_id uuid,p_template_item_id uuid,p_override_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_template uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'menu:manage',p_restaurant_id) then raise exception 'Menu management permission required' using errcode='42501'; end if; select template_id into v_template from public.restaurant_group_menu_items where id=p_template_item_id; if not exists(select 1 from private.restaurant_group_template_targets(v_template)t where t.restaurant_id=p_restaurant_id) then raise exception 'Restaurant is outside menu template scope'; end if;
 insert into public.restaurant_group_menu_overrides(group_id,restaurant_id,template_item_id,override_data,updated_by) values(p_group_id,p_restaurant_id,p_template_item_id,coalesce(p_override_data,'{}'::jsonb),auth.uid()) on conflict(restaurant_id,template_item_id) do update set override_data=excluded.override_data,updated_by=auth.uid(),updated_at=now() returning id into v_id; if exists(select 1 from public.restaurant_group_menu_templates where id=v_template and auto_publish and status='active') then perform private.publish_restaurant_group_menu_template(v_template,auth.uid(),array[p_restaurant_id]); end if; return v_id; end $$;
create or replace function public.save_restaurant_group_price_override(p_group_id uuid,p_override_id uuid,p_template_item_id uuid,p_scope_type text,p_brand_id uuid default null,p_region_id uuid default null,p_restaurant_id uuid default null,p_price_pence integer default 0,p_starts_at timestamptz default null,p_ends_at timestamptz default null,p_priority integer default 0) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_template uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'pricing:manage',p_restaurant_id,p_brand_id,p_region_id) then raise exception 'Pricing management permission required' using errcode='42501'; end if; select template_id into v_template from public.restaurant_group_menu_items where id=p_template_item_id; if v_template is null then raise exception 'Template item not found'; end if;
 if p_override_id is null then insert into public.restaurant_group_price_overrides(group_id,template_item_id,scope_type,brand_id,region_id,restaurant_id,price_pence,starts_at,ends_at,priority,created_by) values(p_group_id,p_template_item_id,p_scope_type,p_brand_id,p_region_id,p_restaurant_id,p_price_pence,p_starts_at,p_ends_at,p_priority,auth.uid()) returning id into v_id;
 else update public.restaurant_group_price_overrides set scope_type=p_scope_type,brand_id=p_brand_id,region_id=p_region_id,restaurant_id=p_restaurant_id,price_pence=p_price_pence,starts_at=p_starts_at,ends_at=p_ends_at,priority=p_priority,updated_at=now() where id=p_override_id and group_id=p_group_id returning id into v_id; end if; if v_id is null then raise exception 'Price override not found'; end if; perform private.restaurant_group_log(p_group_id,'pricing.override_saved','price_override',v_id,null,jsonb_build_object('scope_type',p_scope_type,'price_pence',p_price_pence)); return v_id; end $$;
create or replace function public.save_restaurant_group_campaign_target(p_group_id uuid,p_campaign_id uuid,p_target_id uuid,p_target_type text,p_scope_id uuid default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_source uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'marketing:manage') then raise exception 'Marketing management permission required' using errcode='42501'; end if; select restaurant_id into v_source from public.restaurant_marketing_campaigns where id=p_campaign_id; if not exists(select 1 from public.restaurant_group_locations where group_id=p_group_id and restaurant_id=v_source) then raise exception 'Campaign source is outside this organisation'; end if;
 if p_target_id is null then insert into public.restaurant_group_campaign_targets(group_id,campaign_id,target_type,brand_id,region_id,restaurant_id,created_by) values(p_group_id,p_campaign_id,p_target_type,case when p_target_type='brand' then p_scope_id end,case when p_target_type='region' then p_scope_id end,case when p_target_type='restaurant' then p_scope_id end,auth.uid()) returning id into v_id;
 else update public.restaurant_group_campaign_targets set target_type=p_target_type,brand_id=case when p_target_type='brand' then p_scope_id end,region_id=case when p_target_type='region' then p_scope_id end,restaurant_id=case when p_target_type='restaurant' then p_scope_id end where id=p_target_id and group_id=p_group_id and campaign_id=p_campaign_id returning id into v_id; end if; if v_id is null then raise exception 'Campaign target not found'; end if; return v_id; end $$;
create or replace function public.save_restaurant_group_integration(p_group_id uuid,p_integration_id uuid,p_type text,p_name text,p_config jsonb default '{}'::jsonb,p_secret_reference text default null,p_status text default 'active') returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;
begin if not private.restaurant_group_member_permission(p_group_id,'enterprise:manage') then raise exception 'Enterprise management permission required' using errcode='42501'; end if; if p_integration_id is null then insert into public.restaurant_group_integrations(group_id,integration_type,name,status,config,secret_reference,created_by) values(p_group_id,p_type,btrim(p_name),p_status,coalesce(p_config,'{}'::jsonb),p_secret_reference,auth.uid()) returning id into v_id; else update public.restaurant_group_integrations set integration_type=p_type,name=btrim(p_name),status=p_status,config=coalesce(p_config,'{}'::jsonb),secret_reference=p_secret_reference,updated_at=now() where id=p_integration_id and group_id=p_group_id returning id into v_id; end if; if v_id is null then raise exception 'Integration not found'; end if; perform private.restaurant_group_log(p_group_id,'integration.saved','integration',v_id,null,jsonb_build_object('type',p_type,'status',p_status)); return v_id; end $$;
create or replace function public.create_restaurant_group_api_key(p_group_id uuid,p_name text,p_scopes text[] default array['analytics:read']::text[],p_expires_at timestamptz default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_raw text;v_hash text;v_id uuid;v_prefix text;
begin if not private.restaurant_group_member_permission(p_group_id,'enterprise:manage') then raise exception 'Enterprise management permission required' using errcode='42501'; end if; if not coalesce((select api_enabled from public.restaurant_group_enterprise_settings where group_id=p_group_id),false) then raise exception 'Corporate API access is disabled'; end if;
 v_raw:='of_ent_'||encode(gen_random_bytes(28),'hex');v_prefix:=left(v_raw,14);v_hash:=encode(digest(v_raw,'sha256'),'hex');insert into public.restaurant_group_api_keys(group_id,name,key_prefix,key_hash,scopes,expires_at,created_by) values(p_group_id,btrim(p_name),v_prefix,v_hash,coalesce(p_scopes,array[]::text[]),p_expires_at,auth.uid()) returning id into v_id;perform private.restaurant_group_log(p_group_id,'api_key.created','api_key',v_id,null,jsonb_build_object('name',p_name,'prefix',v_prefix,'scopes',p_scopes));return jsonb_build_object('id',v_id,'api_key',v_raw,'prefix',v_prefix,'scopes',p_scopes,'expires_at',p_expires_at); end $$;
create or replace function public.revoke_restaurant_group_api_key(p_group_id uuid,p_key_id uuid) returns void language plpgsql security definer set search_path='' as $$
begin if not private.restaurant_group_member_permission(p_group_id,'enterprise:manage') then raise exception 'Enterprise management permission required' using errcode='42501'; end if;update public.restaurant_group_api_keys set status='revoked',revoked_at=now() where id=p_key_id and group_id=p_group_id;if not found then raise exception 'API key not found';end if;perform private.restaurant_group_log(p_group_id,'api_key.revoked','api_key',p_key_id,null,'{}'::jsonb);end $$;
create or replace function private.validate_restaurant_group_api_key(p_raw_key text,p_required_scope text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_group uuid;
begin update public.restaurant_group_api_keys set last_used_at=now() where key_hash=encode(digest(p_raw_key,'sha256'),'hex') and status='active' and(expires_at is null or expires_at>now()) and(p_required_scope is null or p_required_scope=any(scopes)) returning group_id into v_group;return v_group;end $$;

create or replace function private.calculate_customer_vip_metrics(p_restaurant_id uuid,p_customer_user_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p public.restaurant_vip_programs%rowtype;cutoff timestamptz;spend bigint:=0;orders_count bigint:=0;points bigint:=0;stamps bigint:=0;referrals bigint:=0;custom jsonb:='{}'::jsonb;
begin select * into p from public.restaurant_vip_programs where restaurant_id=p_restaurant_id;if not found then return jsonb_build_object('lifetime_spend_pence',0,'orders_completed',0,'loyalty_points',0,'stamp_cards_completed',0,'referral_count',0,'custom_metrics','{}'::jsonb);end if;if p.qualification_window='rolling' then cutoff:=now()-make_interval(days=>p.rolling_days);end if;
 select count(*),coalesce(sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence+o.reward_discount_pence+o.vip_discount_pence),0) into orders_count,spend from public.orders o where o.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'vip')x) and o.customer_user_id=p_customer_user_id and o.order_status='completed' and o.payment_status in('paid','partially_refunded','succeeded') and(cutoff is null or coalesce(o.completed_at,o.updated_at)>=cutoff);
 if cutoff is null then select coalesce(sum(a.lifetime_points_earned),0) into points from public.customer_loyalty_accounts a where a.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'loyalty')x) and a.customer_user_id=p_customer_user_id;select coalesce(sum(c.completed_cycles),0) into stamps from public.customer_stamp_cards c where c.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'stamp_cards')x) and c.customer_user_id=p_customer_user_id;
 else select coalesce(sum(greatest(l.points_delta,0)),0) into points from public.customer_loyalty_ledger l where l.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'loyalty')x) and l.customer_user_id=p_customer_user_id and l.created_at>=cutoff;select count(*) into stamps from public.customer_stamp_events e where e.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'stamp_cards')x) and e.customer_user_id=p_customer_user_id and e.event_type='completion' and e.created_at>=cutoff;end if;
 select count(*) into referrals from public.customer_referrals r where r.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'referrals')x) and r.referrer_user_id=p_customer_user_id and r.status in('qualified','rewarded') and(cutoff is null or coalesce(r.qualified_at,r.updated_at)>=cutoff);
 select coalesce(jsonb_object_agg(m.metric_key,m.metric_value),'{}'::jsonb) into custom from public.customer_vip_custom_metrics m where m.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(p_restaurant_id,'vip')x) and m.customer_user_id=p_customer_user_id;
 return jsonb_build_object('lifetime_spend_pence',coalesce(spend,0),'orders_completed',coalesce(orders_count,0),'loyalty_points',coalesce(points,0),'stamp_cards_completed',coalesce(stamps,0),'referral_count',coalesce(referrals,0),'custom_metrics',custom,'qualification_window',p.qualification_window,'rolling_days',case when p.qualification_window='rolling' then p.rolling_days else null end,'shared_scope',coalesce(private.restaurant_group_feature_scope(private.restaurant_group_for_restaurant(p_restaurant_id),'vip'),'restaurant'));end $$;
create or replace function public.award_order_stamp_cards(p_order_id uuid) returns integer language plpgsql security definer set search_path='' as $$
declare order_row public.orders%rowtype;program public.restaurant_stamp_programs%rowtype;card public.customer_stamp_cards%rowtype;eligible_quantity integer;stamps_to_add integer;total_stamps integer;completed integer;remainder integer;awarded_count integer:=0;source_template uuid;
begin select * into order_row from public.orders where id=p_order_id for update;if not found or order_row.customer_user_id is null or order_row.order_status<>'completed' then return 0;end if;
 for program in select * from public.restaurant_stamp_programs where restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(order_row.restaurant_id,'stamp_cards')x) and is_active and starts_at<=now() and(ends_at is null or ends_at>now()) loop
  if exists(select 1 from public.customer_stamp_events where order_id=order_row.id and program_id=program.id and event_type='earned') then continue;end if;if order_row.subtotal_pence<program.minimum_order_pence then continue;end if;
  if program.eligibility_type='menu_item' then select group_template_item_id into source_template from public.menu_items where id=program.menu_item_id;if program.restaurant_id=order_row.restaurant_id then select coalesce(sum(quantity),0) into eligible_quantity from public.order_items where order_id=order_row.id and menu_item_id=program.menu_item_id;
   elsif source_template is not null then select coalesce(sum(oi.quantity),0) into eligible_quantity from public.order_items oi join public.menu_items mi on mi.id=oi.menu_item_id where oi.order_id=order_row.id and mi.group_template_item_id=source_template;else eligible_quantity:=0;end if;stamps_to_add:=eligible_quantity*program.stamps_per_qualifying_order;else stamps_to_add:=program.stamps_per_qualifying_order;end if;if stamps_to_add<=0 then continue;end if;
  insert into public.customer_stamp_cards(program_id,restaurant_id,customer_user_id,current_stamps,lifetime_stamps,expires_at,last_stamp_at) values(program.id,program.restaurant_id,order_row.customer_user_id,0,0,case when program.card_expiry_days is null then null else now()+make_interval(days=>program.card_expiry_days) end,now()) on conflict(program_id,customer_user_id) do update set is_active=true,updated_at=now() returning * into card;
  if card.expires_at is not null and card.expires_at<=now() then update public.customer_stamp_cards set current_stamps=0,cycle_number=cycle_number+1,expires_at=case when program.card_expiry_days is null then null else now()+make_interval(days=>program.card_expiry_days) end,updated_at=now() where id=card.id returning * into card;end if;total_stamps:=card.current_stamps+stamps_to_add;completed:=total_stamps/program.stamps_required;remainder:=total_stamps%program.stamps_required;if not program.repeatable and card.completed_cycles>0 then continue;end if;if not program.repeatable and completed>1 then completed:=1;remainder:=0;end if;
  insert into public.customer_stamp_events(card_id,program_id,restaurant_id,customer_user_id,order_id,event_type,stamps_delta,cycle_number,note) values(card.id,program.id,program.restaurant_id,order_row.customer_user_id,order_row.id,'earned',stamps_to_add,card.cycle_number,case when program.restaurant_id=order_row.restaurant_id then 'Automatic stamps from completed order' else 'Shared stamp-card progress from completed group order' end);
  update public.customer_stamp_cards set current_stamps=case when completed>0 then remainder else total_stamps end,lifetime_stamps=lifetime_stamps+stamps_to_add,completed_cycles=completed_cycles+completed,cycle_number=cycle_number+completed,last_stamp_at=now(),is_active=case when not program.repeatable and completed>0 then false else true end,updated_at=now() where id=card.id returning * into card;
  if completed>0 then for eligible_quantity in 1..completed loop perform public.issue_stamp_completion_reward(card.id);insert into public.customer_stamp_events(card_id,program_id,restaurant_id,customer_user_id,order_id,event_type,stamps_delta,cycle_number,note) values(card.id,program.id,program.restaurant_id,order_row.customer_user_id,order_row.id,'completion',-program.stamps_required,card.cycle_number-1,'Stamp card completed and reward issued');end loop;end if;awarded_count:=awarded_count+stamps_to_add;end loop;return awarded_count;end $$;
create or replace function private.evaluate_referral(p_referral_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare ref public.customer_referrals%rowtype;p public.restaurant_referral_programs%rowtype;qcount integer;revenue integer;first_order uuid;oldstatus text;available timestamptz;rw_id uuid;
begin select * into ref from public.customer_referrals where id=p_referral_id for update;if not found or ref.status='rejected' or ref.referred_user_id is null then return;end if;select * into p from public.restaurant_referral_programs where id=ref.program_id;
 select count(*),coalesce(sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence+coalesce(o.reward_discount_pence,0)),0),(array_agg(o.id order by o.created_at,o.id))[1] into qcount,revenue,first_order from public.orders o where o.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(ref.restaurant_id,'referrals')x) and o.customer_user_id=ref.referred_user_id and o.payment_status in('paid','succeeded') and o.order_status='completed' and o.created_at>=coalesce(ref.registered_at,ref.created_at) and o.subtotal_pence>=p.minimum_qualifying_order_pence;
 update public.customer_referrals set qualifying_order_count=qcount,qualifying_revenue_pence=revenue,qualifying_order_id=case when qcount>0 then coalesce(qualifying_order_id,first_order)else null end,ordered_at=case when qcount>0 then coalesce(ordered_at,now())else ordered_at end,updated_at=now() where id=ref.id;
 if qcount>0 and ref.status='registered' then update public.customer_referrals set status='ordered',ordered_at=coalesce(ordered_at,now()),updated_at=now() where id=ref.id;insert into public.referral_events(referral_id,restaurant_id,event_type,old_status,new_status,order_id,actor_kind)values(ref.id,ref.restaurant_id,'ordered','registered','ordered',first_order,'system');ref.status:='ordered';end if;
 if qcount>=p.qualifying_order_count and ref.status in('registered','ordered') then oldstatus:=ref.status;available:=now()+make_interval(hours=>p.reward_delay_hours);update public.customer_referrals set status='qualified',qualified_at=now(),reward_available_at=available,updated_at=now() where id=ref.id;insert into public.referral_events(referral_id,restaurant_id,event_type,old_status,new_status,order_id,actor_kind,metadata)values(ref.id,ref.restaurant_id,'qualified',oldstatus,'qualified',first_order,'system',jsonb_build_object('qualifying_orders',qcount,'qualifying_revenue_pence',revenue,'shared_group_scope',true));
  insert into public.referral_rewards(referral_id,restaurant_id,customer_user_id,recipient_role,reward_type,reward_value,status,available_at)values(ref.id,ref.restaurant_id,ref.referrer_user_id,'referrer',p.referrer_reward_type,p.referrer_reward_value,'pending',available)on conflict(referral_id,recipient_role)do nothing returning id into rw_id;perform private.queue_referral_notification(ref.id,rw_id,ref.referrer_user_id,ref.restaurant_id,'friend_qualified','Your friend qualified','Your referral has qualified. '||private.referral_reward_label(p.referrer_reward_type,p.referrer_reward_value));rw_id:=null;
  insert into public.referral_rewards(referral_id,restaurant_id,customer_user_id,recipient_role,reward_type,reward_value,status,available_at)values(ref.id,ref.restaurant_id,ref.referred_user_id,'referee',p.referee_reward_type,p.referee_reward_value,'pending',available)on conflict(referral_id,recipient_role)do nothing returning id into rw_id;perform private.queue_referral_notification(ref.id,rw_id,ref.referred_user_id,ref.restaurant_id,'reward_earned','Referral reward earned','You earned '||private.referral_reward_label(p.referee_reward_type,p.referee_reward_value));if p.reward_delay_hours=0 then for rw_id in select id from public.referral_rewards where referral_id=ref.id and status='pending' loop perform private.issue_referral_reward(rw_id);end loop;end if;
 elsif qcount<p.qualifying_order_count and ref.status in('qualified','rewarded') then perform private.reverse_referral_rewards(ref.id,'Qualifying group order was refunded or cancelled');update public.customer_referrals set status='rejected',rejected_at=now(),rejection_reason='qualification_reversed',updated_at=now() where id=ref.id;insert into public.referral_events(referral_id,restaurant_id,event_type,old_status,new_status,actor_kind,metadata)values(ref.id,ref.restaurant_id,'qualification_reversed',ref.status,'rejected','system',jsonb_build_object('qualifying_orders_remaining',qcount));end if;end $$;
create or replace function private.process_order_referral_status() returns trigger language plpgsql security definer set search_path='' as $$
declare refid uuid;
begin if new.customer_user_id is null then return new;end if;select r.id into refid from public.customer_referrals r where r.referred_user_id=new.customer_user_id and r.status<>'rejected' and new.restaurant_id in(select x.restaurant_id from private.restaurant_group_feature_restaurants(r.restaurant_id,'referrals')x) order by r.created_at desc limit 1;if refid is not null then update public.orders set referral_id=refid where id=new.id and referral_id is null;perform private.evaluate_referral(refid);end if;return new;end $$;

revoke all on function public.save_restaurant_group_department(uuid,uuid,uuid,uuid,text,text),public.assign_restaurant_group_location(uuid,uuid,uuid,uuid,text,text),public.save_restaurant_group_menu_template(uuid,uuid,text,text,uuid,uuid,text,boolean),public.save_restaurant_group_menu_category(uuid,uuid,text,text,integer,boolean),public.save_restaurant_group_menu_item(uuid,uuid,uuid,text,text,integer,text,boolean,boolean,boolean,integer),public.save_restaurant_group_menu_override(uuid,uuid,uuid,jsonb),public.save_restaurant_group_price_override(uuid,uuid,uuid,text,uuid,uuid,uuid,integer,timestamptz,timestamptz,integer),public.save_restaurant_group_campaign_target(uuid,uuid,uuid,text,uuid),public.save_restaurant_group_integration(uuid,uuid,text,text,jsonb,text,text),public.create_restaurant_group_api_key(uuid,text,text[],timestamptz),public.revoke_restaurant_group_api_key(uuid,uuid) from public;
grant execute on function public.save_restaurant_group_department(uuid,uuid,uuid,uuid,text,text),public.assign_restaurant_group_location(uuid,uuid,uuid,uuid,text,text),public.save_restaurant_group_menu_template(uuid,uuid,text,text,uuid,uuid,text,boolean),public.save_restaurant_group_menu_category(uuid,uuid,text,text,integer,boolean),public.save_restaurant_group_menu_item(uuid,uuid,uuid,text,text,integer,text,boolean,boolean,boolean,integer),public.save_restaurant_group_menu_override(uuid,uuid,uuid,jsonb),public.save_restaurant_group_price_override(uuid,uuid,uuid,text,uuid,uuid,uuid,integer,timestamptz,timestamptz,integer),public.save_restaurant_group_campaign_target(uuid,uuid,uuid,text,uuid),public.save_restaurant_group_integration(uuid,uuid,text,text,jsonb,text,text),public.create_restaurant_group_api_key(uuid,text,text[],timestamptz),public.revoke_restaurant_group_api_key(uuid,uuid) to authenticated;
