create or replace function private.challenge_audience_matches(c public.restaurant_challenges, uid uuid)
returns boolean language plpgsql stable security definer set search_path='' as $$
declare order_count bigint; tier_id uuid; target_tier uuid; dob date; referral_count bigint; completed_count bigint;
begin
  if c.max_completions is not null then
    select count(*) into completed_count from public.customer_challenge_progress p where p.challenge_id=c.id and p.customer_user_id=uid and p.status='completed';
    if completed_count>=c.max_completions then return false; end if;
  end if;
  if c.target_audience='all' then return true; end if;
  if c.target_audience='vip' then return exists(select 1 from public.customer_vip_memberships m where m.restaurant_id=c.restaurant_id and m.customer_user_id=uid and m.current_tier_id is not null); end if;
  if c.target_audience='tier' then target_tier:=nullif(c.target_config->>'tier_id','')::uuid; select current_tier_id into tier_id from public.customer_vip_memberships where restaurant_id=c.restaurant_id and customer_user_id=uid; return target_tier is not null and tier_id=target_tier; end if;
  select count(*) into order_count from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed';
  if c.target_audience='new' then return order_count<=1; end if;
  if c.target_audience='returning' then return order_count>1; end if;
  if c.target_audience='birthday' then select date_of_birth into dob from public.customer_profiles where user_id=uid; return dob is not null and extract(month from dob)=extract(month from now()) and extract(day from dob)=extract(day from now()); end if;
  if c.target_audience='referral' then select count(*) into referral_count from public.customer_referrals where restaurant_id=c.restaurant_id and referrer_user_id=uid and status='qualified'; return referral_count>0; end if;
  if c.target_audience='custom' then return exists(select 1 from public.customer_challenge_custom_metrics m where m.restaurant_id=c.restaurant_id and m.customer_user_id=uid and m.metric_key=coalesce(c.target_config->>'metric_key','') and m.metric_value>=coalesce((c.target_config->>'minimum_value')::bigint,1)); end if;
  return false;
end $$;

create or replace function private.challenge_metric_value(cond public.restaurant_challenge_conditions,c public.restaurant_challenges,uid uuid,trigger_order_id uuid)
returns bigint language plpgsql stable security definer set search_path='' as $$
declare v bigint:=0; start_time timestamptz:=c.starts_at; finish_time timestamptz:=coalesce(c.ends_at,'infinity'::timestamptz); key text; cycle_start timestamptz; cycle_end timestamptz;
begin
  if c.repeatable then
    if c.repeat_period='daily' then cycle_start:=date_trunc('day',now() at time zone 'Europe/London') at time zone 'Europe/London'; cycle_end:=cycle_start+interval '1 day';
    elsif c.repeat_period='weekly' then cycle_start:=date_trunc('week',now() at time zone 'Europe/London') at time zone 'Europe/London'; cycle_end:=cycle_start+interval '1 week';
    elsif c.repeat_period='monthly' then cycle_start:=date_trunc('month',now() at time zone 'Europe/London') at time zone 'Europe/London'; cycle_end:=cycle_start+interval '1 month'; end if;
    if cycle_start is not null then start_time:=greatest(start_time,cycle_start); finish_time:=least(finish_time,cycle_end); end if;
  end if;
  if cond.condition_type='order_count' then select count(*) into v from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed' and coalesce(completed_at,updated_at)>=start_time and coalesce(completed_at,updated_at)<finish_time;
  elsif cond.condition_type='total_spend' then select coalesce(sum(total_pence+customer_credit_used_pence+gift_card_used_pence+reward_discount_pence+vip_discount_pence+vip_delivery_discount_pence+vip_menu_item_discount_pence),0) into v from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed' and coalesce(completed_at,updated_at)>=start_time and coalesce(completed_at,updated_at)<finish_time;
  elsif cond.condition_type='single_order_spend' then select coalesce(max(total_pence+customer_credit_used_pence+gift_card_used_pence+reward_discount_pence+vip_discount_pence+vip_delivery_discount_pence+vip_menu_item_discount_pence),0) into v from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed' and coalesce(completed_at,updated_at)>=start_time and coalesce(completed_at,updated_at)<finish_time;
  elsif cond.condition_type in ('breakfast_orders','lunch_orders','dinner_orders') then select count(*) into v from public.orders o where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time and case cond.condition_type when 'breakfast_orders' then extract(hour from o.created_at at time zone 'Europe/London') between 5 and 10 when 'lunch_orders' then extract(hour from o.created_at at time zone 'Europe/London') between 11 and 15 else extract(hour from o.created_at at time zone 'Europe/London') between 16 and 23 end;
  elsif cond.condition_type='weekend_orders' then select count(*) into v from public.orders o where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time and extract(isodow from o.created_at at time zone 'Europe/London') in (6,7);
  elsif cond.condition_type='weekday_orders' then select count(*) into v from public.orders o where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time and extract(isodow from o.created_at at time zone 'Europe/London') between 1 and 5;
  elsif cond.condition_type='distinct_menu_items' then select count(distinct oi.menu_item_id) into v from public.order_items oi join public.orders o on o.id=oi.order_id where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and oi.menu_item_id is not null and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time;
  elsif cond.condition_type='distinct_categories' then select count(distinct mi.category_id) into v from public.order_items oi join public.menu_items mi on mi.id=oi.menu_item_id join public.orders o on o.id=oi.order_id where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time;
  elsif cond.condition_type='featured_item' then select coalesce(sum(oi.quantity),0) into v from public.order_items oi join public.orders o on o.id=oi.order_id where o.restaurant_id=c.restaurant_id and o.customer_user_id=uid and o.payment_status='paid' and o.order_status='completed' and oi.menu_item_id=cond.menu_item_id and coalesce(o.completed_at,o.updated_at)>=start_time and coalesce(o.completed_at,o.updated_at)<finish_time;
  elsif cond.condition_type='vip_only' then select case when exists(select 1 from public.customer_vip_memberships m where m.restaurant_id=c.restaurant_id and m.customer_user_id=uid and m.current_tier_id is not null) then cond.target_value else 0 end into v;
  elsif cond.condition_type='referral_count' then select count(*) into v from public.customer_referrals r where r.restaurant_id=c.restaurant_id and r.referrer_user_id=uid and r.status='qualified' and r.qualified_at>=start_time and r.qualified_at<finish_time;
  elsif cond.condition_type='stamp_count' then select coalesce(sum(e.stamps_delta) filter(where e.stamps_delta>0),0) into v from public.customer_stamp_events e where e.restaurant_id=c.restaurant_id and e.customer_user_id=uid and e.created_at>=start_time and e.created_at<finish_time;
  elsif cond.condition_type='points_balance' then select coalesce(points_balance,0) into v from public.customer_loyalty_accounts where restaurant_id=c.restaurant_id and customer_user_id=uid;
  elsif cond.condition_type='points_earned' then select coalesce(sum(points_delta) filter(where points_delta>0),0) into v from public.customer_loyalty_ledger where restaurant_id=c.restaurant_id and customer_user_id=uid and created_at>=start_time and created_at<finish_time;
  elsif cond.condition_type='consecutive_weeks' then select coalesce(max(run),0) into v from (select count(*) over(partition by grp) run from (select week_start,week_start-(row_number() over(order by week_start)::int*7)*interval '1 day' grp from (select distinct date_trunc('week',coalesce(completed_at,updated_at))::date week_start from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed' and coalesce(completed_at,updated_at)>=start_time and coalesce(completed_at,updated_at)<finish_time) w) x) y;
  elsif cond.condition_type='consecutive_months' then select coalesce(max(run),0) into v from (select count(*) over(partition by grp) run from (select month_start,month_start-(row_number() over(order by month_start)::int*interval '1 month') grp from (select distinct date_trunc('month',coalesce(completed_at,updated_at)) month_start from public.orders where restaurant_id=c.restaurant_id and customer_user_id=uid and payment_status='paid' and order_status='completed' and coalesce(completed_at,updated_at)>=start_time and coalesce(completed_at,updated_at)<finish_time) m) x) y;
  elsif cond.condition_type in ('seasonal','holiday') then v:=case when now() between coalesce(nullif(cond.config->>'window_start','')::timestamptz,start_time) and coalesce(nullif(cond.config->>'window_end','')::timestamptz,finish_time) then cond.target_value else 0 end;
  elsif cond.condition_type='custom' then key:=coalesce(cond.config->>'metric_key',''); select coalesce(metric_value,0) into v from public.customer_challenge_custom_metrics where restaurant_id=c.restaurant_id and customer_user_id=uid and metric_key=key;
  end if;
  return coalesce(v,0);
end $$;
