create index if not exists customer_vip_benefit_events_benefit_idx on public.customer_vip_benefit_events(benefit_id);
create index if not exists customer_vip_benefit_events_reward_issuance_idx on public.customer_vip_benefit_events(reward_issuance_id) where reward_issuance_id is not null;
create index if not exists customer_vip_benefit_events_tier_idx on public.customer_vip_benefit_events(tier_id);
create index if not exists customer_vip_custom_metric_events_actor_idx on public.customer_vip_custom_metric_events(actor_user_id) where actor_user_id is not null;
create index if not exists customer_vip_custom_metric_events_customer_idx on public.customer_vip_custom_metric_events(customer_user_id);
create index if not exists customer_vip_custom_metrics_customer_idx on public.customer_vip_custom_metrics(customer_user_id);
create index if not exists customer_vip_custom_metrics_updated_by_idx on public.customer_vip_custom_metrics(updated_by) where updated_by is not null;
create index if not exists customer_vip_memberships_current_tier_idx on public.customer_vip_memberships(current_tier_id) where current_tier_id is not null;
create index if not exists customer_vip_tier_history_actor_idx on public.customer_vip_tier_history(actor_user_id) where actor_user_id is not null;
create index if not exists customer_vip_tier_history_from_tier_idx on public.customer_vip_tier_history(from_tier_id) where from_tier_id is not null;
create index if not exists customer_vip_tier_history_to_tier_idx on public.customer_vip_tier_history(to_tier_id) where to_tier_id is not null;
create index if not exists orders_vip_tier_idx on public.orders(vip_tier_id) where vip_tier_id is not null;
create index if not exists restaurant_vip_programs_created_by_idx on public.restaurant_vip_programs(created_by) where created_by is not null;
create index if not exists restaurant_vip_tier_benefits_menu_item_idx on public.restaurant_vip_tier_benefits(menu_item_id) where menu_item_id is not null;
create index if not exists restaurant_vip_tier_benefits_restaurant_idx on public.restaurant_vip_tier_benefits(restaurant_id);
create index if not exists restaurant_vip_tier_benefits_reward_catalogue_idx on public.restaurant_vip_tier_benefits(reward_catalogue_id) where reward_catalogue_id is not null;
create index if not exists restaurant_vip_tier_rules_restaurant_idx on public.restaurant_vip_tier_rules(restaurant_id);
create index if not exists restaurant_vip_tiers_created_by_idx on public.restaurant_vip_tiers(created_by) where created_by is not null;
create index if not exists reward_notification_queue_vip_history_idx on public.reward_notification_queue(vip_tier_history_id) where vip_tier_history_id is not null;
create index if not exists vip_fraud_flags_customer_idx on public.vip_fraud_flags(customer_user_id);
create index if not exists vip_fraud_flags_membership_idx on public.vip_fraud_flags(membership_id) where membership_id is not null;
create index if not exists vip_fraud_flags_reviewed_by_idx on public.vip_fraud_flags(reviewed_by) where reviewed_by is not null;
create index if not exists vip_fraud_flags_tier_history_idx on public.vip_fraud_flags(tier_history_id) where tier_history_id is not null;
