create or replace function public.get_platform_marketing_analytics(p_days integer default 90)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_period integer:=least(greatest(coalesce(p_days,90),1),730);v_since timestamptz:=now()-(v_period||' days')::interval;v_prev timestamptz:=now()-(v_period*2||' days')::interval;v_result jsonb;
begin
  if not private.has_platform_admin_permission('overview:view') then raise exception 'Platform overview permission required' using errcode='42501'; end if;
  with current_active as(select distinct restaurant_id,customer_user_id from public.orders where customer_user_id is not null and payment_status='paid' and order_status<>'rejected' and created_at>=v_since),previous_active as(select distinct restaurant_id,customer_user_id from public.orders where customer_user_id is not null and payment_status='paid' and order_status<>'rejected' and created_at>=v_prev and created_at<v_since),retained as(select count(*)::numeric n from previous_active p where exists(select 1 from current_active c where c.restaurant_id=p.restaurant_id and c.customer_user_id=p.customer_user_id)),previous_count as(select count(*)::numeric n from previous_active)
  select jsonb_build_object('restaurants_adopted',(select count(distinct restaurant_id) from public.restaurant_marketing_campaigns),'campaign_volume',(select count(*) from public.restaurant_marketing_campaign_runs where created_at>=v_since),'email_volume',(select count(*) from public.restaurant_marketing_deliveries where channel='email' and created_at>=v_since),'notifications_volume',(select count(*) from public.restaurant_marketing_deliveries where channel='in_app' and created_at>=v_since),'revenue_generated_pence',(select coalesce(sum(revenue_pence),0) from public.restaurant_marketing_conversions where attributed_at>=v_since),'reward_cost_pence',(select coalesce(sum(reward_cost_pence),0) from public.restaurant_marketing_conversions where attributed_at>=v_since),'engaged_customers',(select count(distinct customer_user_id) from public.restaurant_marketing_deliveries where created_at>=v_since and(opened_at is not null or clicked_at is not null)),'automation_usage',(select count(distinct restaurant_id) from public.restaurant_marketing_automations where status='active'),'active_automations',(select count(*) from public.restaurant_marketing_automations where status='active'),'retention_percent',coalesce((select round(100.0*r.n/nullif(p.n,0),1) from retained r cross join previous_count p),0),'customer_growth',(select count(*) from current_active c where not exists(select 1 from previous_active p where p.restaurant_id=c.restaurant_id and p.customer_user_id=c.customer_user_id))) into v_result;
  return v_result;
end $$;
