create index if not exists customer_referral_codes_customer_user_idx on public.customer_referral_codes(customer_user_id);
create index if not exists customer_referral_codes_restaurant_idx on public.customer_referral_codes(restaurant_id);
create index if not exists customer_referrals_referrer_user_idx on public.customer_referrals(referrer_user_id);
create index if not exists customer_referrals_referred_user_idx on public.customer_referrals(referred_user_id) where referred_user_id is not null;
create index if not exists customer_referrals_qualifying_order_idx on public.customer_referrals(qualifying_order_id) where qualifying_order_id is not null;
create index if not exists customer_referrals_referral_code_id_idx on public.customer_referrals(referral_code_id) where referral_code_id is not null;
create index if not exists referral_attribution_tokens_program_idx on public.referral_attribution_tokens(program_id);
create index if not exists referral_attribution_tokens_code_idx on public.referral_attribution_tokens(referral_code_id);
create index if not exists referral_attribution_tokens_referral_idx on public.referral_attribution_tokens(referral_id) where referral_id is not null;
create index if not exists referral_attribution_tokens_claimed_user_idx on public.referral_attribution_tokens(claimed_by_user_id) where claimed_by_user_id is not null;
create index if not exists referral_events_order_idx on public.referral_events(order_id) where order_id is not null;
create index if not exists referral_events_actor_idx on public.referral_events(actor_user_id) where actor_user_id is not null;
create index if not exists referral_fraud_flags_referral_idx on public.referral_fraud_flags(referral_id) where referral_id is not null;
create index if not exists referral_fraud_flags_reviewer_idx on public.referral_fraud_flags(reviewed_by) where reviewed_by is not null;
create index if not exists referral_notification_queue_referral_idx on public.referral_notification_queue(referral_id) where referral_id is not null;
create index if not exists referral_notification_queue_reward_idx on public.referral_notification_queue(referral_reward_id) where referral_reward_id is not null;
create index if not exists referral_notification_queue_restaurant_idx on public.referral_notification_queue(restaurant_id) where restaurant_id is not null;
create index if not exists referral_notification_queue_customer_idx on public.referral_notification_queue(customer_user_id);
create index if not exists referral_rewards_restaurant_idx on public.referral_rewards(restaurant_id);
create index if not exists referral_rewards_customer_idx on public.referral_rewards(customer_user_id);
create index if not exists referral_rewards_credit_ledger_idx on public.referral_rewards(credit_ledger_id) where credit_ledger_id is not null;
create index if not exists referral_rewards_loyalty_ledger_idx on public.referral_rewards(loyalty_ledger_id) where loyalty_ledger_id is not null;
create index if not exists referral_rewards_voucher_idx on public.referral_rewards(voucher_id) where voucher_id is not null;
create index if not exists restaurant_referral_programs_referrer_catalogue_idx on public.restaurant_referral_programs(referrer_reward_catalogue_id) where referrer_reward_catalogue_id is not null;
create index if not exists restaurant_referral_programs_referee_catalogue_idx on public.restaurant_referral_programs(referee_reward_catalogue_id) where referee_reward_catalogue_id is not null;
create index if not exists restaurant_referral_programs_created_by_idx on public.restaurant_referral_programs(created_by) where created_by is not null;
