begin;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  order_number bigint generated by default as identity,
  customer_user_id uuid references auth.users(id) on delete set null,
  customer_first_name text not null,
  customer_last_name text not null,
  customer_email text not null,
  customer_phone text not null,
  fulfilment_method text not null check (fulfilment_method in ('delivery', 'collection')),
  address_line_1 text,
  address_line_2 text,
  town_city text,
  postcode text,
  delivery_instructions text,
  subtotal_pence integer not null check (subtotal_pence >= 0),
  delivery_fee_pence integer not null default 0 check (delivery_fee_pence >= 0),
  discount_pence integer not null default 0 check (discount_pence >= 0),
  total_pence integer not null check (total_pence >= 0),
  currency text not null default 'gbp' check (currency = 'gbp'),
  payment_status text not null default 'pending' check (
    payment_status in ('pending', 'requires_action', 'paid', 'failed', 'refunded', 'partially_refunded')
  ),
  order_status text not null default 'pending_payment' check (
    order_status in (
      'pending_payment',
      'placed',
      'accepted',
      'preparing',
      'ready',
      'out_for_delivery',
      'completed',
      'cancelled',
      'rejected'
    )
  ),
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text unique,
  restaurant_notes text,
  estimated_ready_at timestamptz,
  paid_at timestamptz,
  accepted_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_address_required check (
    fulfilment_method = 'collection'
    or (
      nullif(trim(address_line_1), '') is not null
      and nullif(trim(town_city), '') is not null
      and nullif(trim(postcode), '') is not null
    )
  ),
  constraint order_total_matches check (
    total_pence = greatest(subtotal_pence + delivery_fee_pence - discount_pence, 0)
  )
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  item_name text not null,
  unit_price_pence integer not null check (unit_price_pence >= 0),
  quantity integer not null check (quantity > 0),
  line_total_pence integer generated always as (unit_price_pence * quantity) stored,
  customer_notes text,
  item_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create unique index if not exists orders_restaurant_order_number_idx
  on public.orders (restaurant_id, order_number);

create index if not exists orders_restaurant_status_created_idx
  on public.orders (restaurant_id, order_status, created_at desc);

create index if not exists orders_customer_user_created_idx
  on public.orders (customer_user_id, created_at desc)
  where customer_user_id is not null;

create index if not exists orders_payment_status_idx
  on public.orders (payment_status, created_at desc);

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create index if not exists order_status_history_order_created_idx
  on public.order_status_history (order_id, created_at);

create or replace function public.set_order_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_order_updated_at();

create or replace function public.record_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.order_status_history (order_id, from_status, to_status, changed_by)
    values (new.id, null, new.order_status, auth.uid());
  elsif new.order_status is distinct from old.order_status then
    insert into public.order_status_history (order_id, from_status, to_status, changed_by)
    values (new.id, old.order_status, new.order_status, auth.uid());
  end if;

  return new;
end;
$$;

drop trigger if exists record_order_status_change on public.orders;
create trigger record_order_status_change
after insert or update of order_status on public.orders
for each row execute function public.record_order_status_change();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

create policy "Restaurant members can view orders"
on public.orders
for select
to authenticated
using (
  exists (
    select 1
    from public.restaurant_members member
    where member.restaurant_id = orders.restaurant_id
      and member.user_id = auth.uid()
  )
  or customer_user_id = auth.uid()
);

create policy "Restaurant members can update orders"
on public.orders
for update
to authenticated
using (
  exists (
    select 1
    from public.restaurant_members member
    where member.restaurant_id = orders.restaurant_id
      and member.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.restaurant_members member
    where member.restaurant_id = orders.restaurant_id
      and member.user_id = auth.uid()
  )
);

create policy "Customers and restaurant members can view order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders customer_order
    where customer_order.id = order_items.order_id
      and (
        customer_order.customer_user_id = auth.uid()
        or exists (
          select 1
          from public.restaurant_members member
          where member.restaurant_id = customer_order.restaurant_id
            and member.user_id = auth.uid()
        )
      )
  )
);

create policy "Customers and restaurant members can view order history"
on public.order_status_history
for select
to authenticated
using (
  exists (
    select 1
    from public.orders customer_order
    where customer_order.id = order_status_history.order_id
      and (
        customer_order.customer_user_id = auth.uid()
        or exists (
          select 1
          from public.restaurant_members member
          where member.restaurant_id = customer_order.restaurant_id
            and member.user_id = auth.uid()
        )
      )
  )
);

comment on table public.orders is 'Customer orders. Creation should occur only through a trusted server-side checkout function.';
comment on table public.order_items is 'Immutable order line snapshots used for fulfilment and accounting.';
comment on table public.order_status_history is 'Audit trail for every order status transition.';

commit;
