create or replace function public.get_restaurant_vip_dashboard()
returns jsonb language plpgsql security definer set search_path='' as $$
declare rid uuid; result jsonb; total_members integer; upgrades_30 integer; downgrades_30 integer;
begin
  select restaurant_id into rid from public.restaurant_members where user_id=auth.uid() order by created_at limit 1;
  if rid is null then raise exception 'Restaurant membership not found' using errcode='42501'; end if;
  select count(*) into total_members from public.customer_vip_memberships where restaurant_id=rid and current_tier_id is not null;
  select count(*) filter(where change_type in ('initial','upgrade')),count(*) filter(where change_type in ('downgrade','removed')) into upgrades_30,downgrades_30 from public.customer_vip_tier_history where restaurant_id=rid and created_at>=now()-interval '30 days';
  select jsonb_build_object(
    'program',coalesce((select to_jsonb(p)-'created_by' from public.restaurant_vip_programs p where p.restaurant_id=rid),'{}'::jsonb),
    'tiers',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'colour',t.colour,'icon',t.icon,'description',t.description,'priority',t.priority,'qualification_match',t.qualification_match,'is_active',t.is_active,'rules',coalesce((select jsonb_agg(to_jsonb(r)-'restaurant_id'-'tier_id' order by r.created_at) from public.restaurant_vip_tier_rules r where r.tier_id=t.id),'[]'::jsonb),'benefits',coalesce((select jsonb_agg((to_jsonb(b)-'restaurant_id'-'tier_id')||jsonb_build_object('menu_item_name',mi.name,'reward_name',lr.name) order by b.created_at) from public.restaurant_vip_tier_benefits b left join public.menu_items mi on mi.id=b.menu_item_id left join public.restaurant_loyalty_rewards lr on lr.id=b.reward_catalogue_id where b.tier_id=t.id),'[]'::jsonb)) order by t.priority) from public.restaurant_vip_tiers t where t.restaurant_id=rid and t.archived_at is null),'[]'::jsonb),
    'catalogue_rewards',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'reward_type',r.reward_type) order by r.name) from public.restaurant_loyalty_rewards r where r.restaurant_id=rid),'[]'::jsonb),
    'menu_items',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'name',m.name) order by m.name) from public.menu_items m where m.restaurant_id=rid and m.is_available),'[]'::jsonb),
    'stamp_programs',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'is_active',s.is_active) order by s.name) from public.restaurant_stamp_programs s where s.restaurant_id=rid),'[]'::jsonb),
    'summary',jsonb_build_object('vip_customers',total_members,'revenue_90d_pence',coalesce((select sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence) from public.orders o where o.restaurant_id=rid and o.vip_tier_id is not null and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'average_spend_pence',coalesce((select round(avg(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence)) from public.orders o where o.restaurant_id=rid and o.vip_tier_id is not null and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'upgrades_30d',upgrades_30,'downgrades_30d',downgrades_30,'upgrade_rate',case when total_members=0 then 0 else round(100.0*upgrades_30/total_members,1) end,'downgrade_rate',case when total_members=0 then 0 else round(100.0*downgrades_30/total_members,1) end,'reward_events_90d',(select count(*) from public.customer_vip_benefit_events e where e.restaurant_id=rid and e.created_at>=now()-interval '90 days'),'open_fraud_flags',(select count(*) from public.vip_fraud_flags f where f.restaurant_id=rid and f.status='open')),
    'tier_analytics',coalesce((select jsonb_agg(jsonb_build_object('tier_id',t.id,'tier_name',t.name,'colour',t.colour,'customers',(select count(*) from public.customer_vip_memberships m where m.restaurant_id=rid and m.current_tier_id=t.id),'revenue_pence',coalesce((select sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence) from public.orders o where o.restaurant_id=rid and o.vip_tier_id=t.id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'orders',(select count(*) from public.orders o where o.restaurant_id=rid and o.vip_tier_id=t.id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),'average_spend_pence',coalesce((select round(avg(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence)) from public.orders o where o.restaurant_id=rid and o.vip_tier_id=t.id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'visit_frequency_90d',coalesce((select round(count(*)::numeric/nullif(count(distinct o.customer_user_id),0),2) from public.orders o where o.restaurant_id=rid and o.vip_tier_id=t.id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'retention_percent',coalesce((select round(100.0*count(*) filter(where recent_orders>0 and prior_orders>0)/nullif(count(*) filter(where prior_orders>0),0),1) from (select m.customer_user_id,(select count(*) from public.orders o where o.restaurant_id=rid and o.customer_user_id=m.customer_user_id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days') recent_orders,(select count(*) from public.orders o where o.restaurant_id=rid and o.customer_user_id=m.customer_user_id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '180 days' and o.completed_at<now()-interval '90 days') prior_orders from public.customer_vip_memberships m where m.restaurant_id=rid and m.current_tier_id=t.id) x),0),'reward_usage',(select count(*) from public.customer_vip_benefit_events e where e.restaurant_id=rid and e.tier_id=t.id and e.created_at>=now()-interval '90 days')) order by t.priority) from public.restaurant_vip_tiers t where t.restaurant_id=rid and t.archived_at is null),'[]'::jsonb),
    'top_customers',coalesce((select jsonb_agg(row_to_json(x) order by x.lifetime_value_pence desc) from (select m.customer_user_id,t.name tier_name,t.colour tier_colour,coalesce((select o.customer_first_name||' '||o.customer_last_name from public.orders o where o.restaurant_id=rid and o.customer_user_id=m.customer_user_id order by o.created_at desc limit 1),'Customer') customer_name,coalesce((select o.customer_email from public.orders o where o.restaurant_id=rid and o.customer_user_id=m.customer_user_id order by o.created_at desc limit 1),'') customer_email,coalesce((select sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence) from public.orders o where o.restaurant_id=rid and o.customer_user_id=m.customer_user_id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded')),0) lifetime_value_pence,coalesce((m.metrics->>'orders_completed')::integer,0) orders_completed,m.tier_changed_at from public.customer_vip_memberships m left join public.restaurant_vip_tiers t on t.id=m.current_tier_id where m.restaurant_id=rid and m.current_tier_id is not null order by lifetime_value_pence desc limit 50) x),'[]'::jsonb)
  ) into result;
  return result;
end $$;

create or replace function public.get_platform_vip_dashboard()
returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb; total_active integer;
begin
  if not private.has_platform_admin_permission('overview:view') then raise exception 'Platform overview permission required' using errcode='42501'; end if;
  select count(*) into total_active from public.restaurants where status='active';
  select jsonb_build_object(
    'summary',jsonb_build_object('restaurants_using_vip',(select count(*) from public.restaurant_vip_programs where is_enabled and not disabled_by_platform),'total_vip_customers',(select count(*) from public.customer_vip_memberships where current_tier_id is not null),'restaurant_adoption_percent',case when total_active=0 then 0 else round(100.0*(select count(*) from public.restaurant_vip_programs p join public.restaurants r on r.id=p.restaurant_id where p.is_enabled and not p.disabled_by_platform and r.status='active')/total_active,1) end,'vip_revenue_90d_pence',coalesce((select sum(total_pence+customer_credit_used_pence+gift_card_used_pence) from public.orders where vip_tier_id is not null and order_status='completed' and payment_status in ('paid','partially_refunded') and completed_at>=now()-interval '90 days'),0),'average_customer_value_pence',coalesce((select round(sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence)::numeric/nullif(count(distinct o.customer_user_id),0)) from public.orders o where o.vip_tier_id is not null and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0),'open_fraud_flags',(select count(*) from public.vip_fraud_flags where status='open'),'benefit_events_90d',(select count(*) from public.customer_vip_benefit_events where created_at>=now()-interval '90 days')),
    'tier_distribution',coalesce((select jsonb_agg(jsonb_build_object('tier_name',x.name,'customers',x.customers,'revenue_pence',x.revenue_pence) order by x.customers desc) from (select t.name,count(distinct m.id) customers,coalesce(sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence) filter(where o.completed_at>=now()-interval '90 days'),0) revenue_pence from public.restaurant_vip_tiers t left join public.customer_vip_memberships m on m.current_tier_id=t.id left join public.orders o on o.vip_tier_id=t.id and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') group by t.name) x),'[]'::jsonb),
    'restaurants',coalesce((select jsonb_agg(row_to_json(x) order by x.vip_revenue_90d_pence desc) from (select r.id restaurant_id,r.name restaurant_name,p.is_enabled,p.disabled_by_platform,(select count(*) from public.customer_vip_memberships m where m.restaurant_id=r.id and m.current_tier_id is not null) vip_customers,coalesce((select sum(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence) from public.orders o where o.restaurant_id=r.id and o.vip_tier_id is not null and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0) vip_revenue_90d_pence,coalesce((select round(avg(o.total_pence+o.customer_credit_used_pence+o.gift_card_used_pence)) from public.orders o where o.restaurant_id=r.id and o.vip_tier_id is not null and o.order_status='completed' and o.payment_status in ('paid','partially_refunded') and o.completed_at>=now()-interval '90 days'),0) avg_spend_pence,(select count(*) from public.customer_vip_tier_history h where h.restaurant_id=r.id and h.change_type in ('initial','upgrade') and h.created_at>=now()-interval '30 days') upgrades_30d,(select count(*) from public.customer_vip_tier_history h where h.restaurant_id=r.id and h.change_type in ('downgrade','removed') and h.created_at>=now()-interval '30 days') downgrades_30d,(select count(*) from public.vip_fraud_flags f where f.restaurant_id=r.id and f.status='open') open_fraud_flags from public.restaurants r join public.restaurant_vip_programs p on p.restaurant_id=r.id) x),'[]'::jsonb),
    'fraud_flags',coalesce((select jsonb_agg(jsonb_build_object('id',f.id,'restaurant_id',f.restaurant_id,'restaurant_name',r.name,'customer_user_id',f.customer_user_id,'flag_type',f.flag_type,'severity',f.severity,'status',f.status,'details',f.details,'created_at',f.created_at,'reviewed_at',f.reviewed_at,'review_note',f.review_note) order by f.created_at desc) from (select * from public.vip_fraud_flags order by created_at desc limit 200) f join public.restaurants r on r.id=f.restaurant_id),'[]'::jsonb)
  ) into result;
  return result;
end $$;

create or replace function public.platform_review_vip_fraud_flag(p_flag_id uuid,p_status text,p_note text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare f public.vip_fraud_flags%rowtype;
begin
  if not private.has_platform_admin_permission('restaurants:manage') then raise exception 'Restaurant management permission required' using errcode='42501'; end if;
  if p_status not in ('reviewed','dismissed','actioned') then raise exception 'Unsupported review status'; end if;
  update public.vip_fraud_flags set status=p_status,reviewed_by=auth.uid(),reviewed_at=now(),review_note=nullif(trim(p_note),''),updated_at=now() where id=p_flag_id returning * into f;
  if not found then raise exception 'VIP fraud flag not found'; end if;
  insert into public.platform_admin_audit_log(actor_user_id,action,target_type,target_id,details) values(auth.uid(),'vip_fraud_reviewed','vip_fraud_flag',f.id,jsonb_build_object('status',p_status,'restaurant_id',f.restaurant_id,'note',p_note));
  return to_jsonb(f);
end $$;

create or replace function public.platform_set_vip_program_disabled(p_restaurant_id uuid,p_disabled boolean,p_reason text default null)
returns void language plpgsql security definer set search_path='' as $$
begin
  if not private.has_platform_admin_permission('restaurants:manage') then raise exception 'Restaurant management permission required' using errcode='42501'; end if;
  if p_disabled and nullif(trim(p_reason),'') is null then raise exception 'A reason is required to disable a VIP programme'; end if;
  update public.restaurant_vip_programs set disabled_by_platform=p_disabled,platform_disable_reason=case when p_disabled then trim(p_reason) else null end,updated_at=now() where restaurant_id=p_restaurant_id;
  if not found then raise exception 'VIP programme not found'; end if;
  insert into public.platform_admin_audit_log(actor_user_id,action,target_type,target_id,details) values(auth.uid(),case when p_disabled then 'vip_program_disabled' else 'vip_program_enabled' end,'restaurant',p_restaurant_id,jsonb_build_object('reason',p_reason));
end $$;

create or replace function public.save_restaurant_vip_tier(p_tier_id uuid,p_name text,p_colour text,p_icon text,p_description text,p_priority integer,p_qualification_match text,p_is_active boolean,p_rules jsonb,p_benefits jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare rid uuid; tier public.restaurant_vip_tiers%rowtype; item jsonb; metric text; benefit text; menu_id uuid; reward_id uuid; val integer; program_id uuid;
begin
  select restaurant_id into rid from public.restaurant_members where user_id=auth.uid() order by created_at limit 1; if rid is null then raise exception 'Restaurant membership not found' using errcode='42501'; end if;
  if nullif(trim(p_name),'') is null then raise exception 'Tier name is required'; end if; if p_colour !~ '^#[0-9A-Fa-f]{6}$' then raise exception 'Tier colour must be a 6 digit hex colour'; end if; if p_qualification_match not in ('all','any') then raise exception 'Choose whether all or any rules must match'; end if;
  if p_tier_id is null then insert into public.restaurant_vip_tiers(restaurant_id,name,colour,icon,description,priority,qualification_match,is_active,created_by) values(rid,trim(p_name),p_colour,coalesce(nullif(trim(p_icon),''),'star'),nullif(trim(p_description),''),p_priority,p_qualification_match,p_is_active,auth.uid()) returning * into tier; else update public.restaurant_vip_tiers set name=trim(p_name),colour=p_colour,icon=coalesce(nullif(trim(p_icon),''),'star'),description=nullif(trim(p_description),''),priority=p_priority,qualification_match=p_qualification_match,is_active=p_is_active,updated_at=now() where id=p_tier_id and restaurant_id=rid and archived_at is null returning * into tier; if not found then raise exception 'VIP tier not found'; end if; delete from public.restaurant_vip_tier_rules where tier_id=tier.id; delete from public.restaurant_vip_tier_benefits where tier_id=tier.id; end if;
  for item in select value from jsonb_array_elements(coalesce(p_rules,'[]'::jsonb)) loop metric:=item->>'metric_type'; if metric not in ('lifetime_spend','orders_completed','loyalty_points','stamp_cards_completed','referral_count','custom_metric') then raise exception 'Unsupported VIP metric: %',metric; end if; insert into public.restaurant_vip_tier_rules(tier_id,restaurant_id,metric_type,custom_metric_key,threshold_value) values(tier.id,rid,metric,case when metric='custom_metric' then lower(item->>'custom_metric_key') else null end,coalesce((item->>'threshold_value')::bigint,0)); end loop;
  for item in select value from jsonb_array_elements(coalesce(p_benefits,'[]'::jsonb)) loop benefit:=item->>'benefit_type'; val:=case when item ? 'value' and item->>'value' is not null then (item->>'value')::integer else null end; menu_id:=case when nullif(item->>'menu_item_id','') is null then null else (item->>'menu_item_id')::uuid end; reward_id:=case when nullif(item->>'reward_catalogue_id','') is null then null else (item->>'reward_catalogue_id')::uuid end; if benefit not in ('bonus_loyalty_points','bonus_stamps','percentage_discount','fixed_discount','free_delivery','free_menu_item','birthday_bonus_multiplier','referral_multiplier','exclusive_reward','early_access_promotions','priority_customer_support') then raise exception 'Unsupported VIP benefit: %',benefit; end if; if benefit='free_menu_item' and not exists(select 1 from public.menu_items mi where mi.id=menu_id and mi.restaurant_id=rid) then raise exception 'Free menu item does not belong to this restaurant'; end if; if benefit='exclusive_reward' and not exists(select 1 from public.restaurant_loyalty_rewards lr where lr.id=reward_id and lr.restaurant_id=rid) then raise exception 'Exclusive reward does not belong to this restaurant'; end if; if benefit='bonus_stamps' then program_id:=case when nullif(item->'metadata'->>'program_id','') is null then null else (item->'metadata'->>'program_id')::uuid end; if program_id is null or not exists(select 1 from public.restaurant_stamp_programs sp where sp.id=program_id and sp.restaurant_id=rid) then raise exception 'Choose a stamp programme for the VIP stamp bonus'; end if; end if; insert into public.restaurant_vip_tier_benefits(tier_id,restaurant_id,benefit_type,value,menu_item_id,reward_catalogue_id,metadata,is_active) values(tier.id,rid,benefit,val,menu_id,reward_id,coalesce(item->'metadata','{}'::jsonb),coalesce((item->>'is_active')::boolean,true)); end loop;
  return to_jsonb(tier)-'created_by';
end $$;

revoke all on function public.get_platform_vip_dashboard(),public.platform_review_vip_fraud_flag(uuid,text,text),public.platform_set_vip_program_disabled(uuid,boolean,text) from public,anon;
grant execute on function public.get_platform_vip_dashboard() to authenticated,service_role;
grant execute on function public.platform_review_vip_fraud_flag(uuid,text,text),public.platform_set_vip_program_disabled(uuid,boolean,text) to authenticated,service_role;
