import Stripe from 'npm:stripe@^22'
import { createClient } from 'npm:@supabase/supabase-js@2'

const MAX_BODY_BYTES=1024*1024,MAX_EVENT_AGE_SECONDS=4*24*60*60,MAX_FUTURE_SKEW_SECONDS=5*60
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})
const paymentIntentId=(value:string|Stripe.PaymentIntent|null)=>!value?null:typeof value==='string'?value:value.id
const idOf=(value:unknown)=>!value?null:typeof value==='string'?value:typeof value==='object'&&value!==null&&'id'in value?String((value as{id:unknown}).id):null
const toIso=(unix:number|null|undefined)=>unix?new Date(unix*1000).toISOString():null

Deno.serve(async(request)=>{
 if(request.method!=='POST')return json({error:'Method not allowed.'},405)
 const contentLength=Number(request.headers.get('content-length')??0);if(Number.isFinite(contentLength)&&contentLength>MAX_BODY_BYTES)return json({error:'Webhook payload is too large.'},413)
 const stripeSecretKey=Deno.env.get('STRIPE_SECRET_KEY'),webhookSecret=Deno.env.get('STRIPE_WEBHOOK_SECRET'),supabaseUrl=Deno.env.get('SUPABASE_URL'),serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
 if(!stripeSecretKey||!webhookSecret||!supabaseUrl||!serviceRoleKey)return json({error:'Webhook is not configured.'},500)
 const signature=request.headers.get('stripe-signature');if(!signature)return json({error:'Missing Stripe signature.'},400)
 const rawBody=await request.text();if(new TextEncoder().encode(rawBody).byteLength>MAX_BODY_BYTES)return json({error:'Webhook payload is too large.'},413)
 const stripe=new Stripe(stripeSecretKey);let event:Stripe.Event
 try{event=await stripe.webhooks.constructEventAsync(rawBody,signature,webhookSecret,300,Stripe.createSubtleCryptoProvider())}catch{return json({error:'Invalid Stripe signature.'},400)}
 const nowSeconds=Math.floor(Date.now()/1000);if(event.created<nowSeconds-MAX_EVENT_AGE_SECONDS||event.created>nowSeconds+MAX_FUTURE_SKEW_SECONDS)return json({error:'Stripe event is outside the accepted time window.'},400)
 const supabase=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}})
 const{data:claim,error:claimError}=await supabase.rpc('claim_stripe_webhook_event',{p_event_id:event.id,p_event_type:event.type});if(claimError)return json({error:'Unable to process webhook.'},500);if(!(claim as{claimed?:boolean}|null)?.claimed)return json({received:true,duplicate:true})

 async function addSubscriptionEvent(restaurantId:string,subscriptionId:string|null,eventType:string,details:Record<string,unknown>={}){const eventKey=`${event.id}:${eventType}`;const{error}=await supabase.from('restaurant_subscription_events').insert({restaurant_id:restaurantId,subscription_id:subscriptionId,event_type:eventType,stripe_event_id:eventKey,details});if(error&&error.code!=='23505')throw error}
 async function upsertInvoice(invoice:Stripe.Invoice,subscriptionId:string|null,restaurantId:string){const anyInvoice=invoice as Stripe.Invoice&{total_taxes?:Array<{amount?:number}>;total_excluding_tax?:number|null};const period=invoice.lines.data[0]?.period;const tax=(anyInvoice.total_taxes??[]).reduce((n,t)=>n+(t.amount??0),0);const{error}=await supabase.from('restaurant_subscription_invoices').upsert({restaurant_id:restaurantId,subscription_id:subscriptionId,stripe_invoice_id:invoice.id,invoice_number:invoice.number,status:invoice.status??'draft',currency:invoice.currency,subtotal_pence:invoice.subtotal??0,discount_pence:Math.max(0,(invoice.subtotal??0)-(anyInvoice.total_excluding_tax??invoice.subtotal??0)),tax_pence:tax,total_pence:invoice.total??0,amount_paid_pence:invoice.amount_paid??0,amount_due_pence:invoice.amount_due??0,hosted_invoice_url:invoice.hosted_invoice_url,invoice_pdf_url:invoice.invoice_pdf,period_start:toIso(period?.start),period_end:toIso(period?.end),due_at:toIso(invoice.due_date),paid_at:invoice.status_transitions?.paid_at?toIso(invoice.status_transitions.paid_at):null,updated_at:new Date().toISOString()},{onConflict:'stripe_invoice_id'});if(error)throw error}
 async function upsertSubscription(subscription:Stripe.Subscription,eventType:string){
  const item=subscription.items.data[0],price=item?.price,restaurantId=subscription.metadata?.restaurant_id,planId=subscription.metadata?.plan_id||price?.metadata?.ordered_food_plan_id,userId=subscription.metadata?.user_id||null
  if(!restaurantId)throw new Error('Stripe subscription is missing restaurant metadata')
  const statusMap:Record<string,string>={incomplete:'incomplete',incomplete_expired:'unpaid',trialing:'trialing',active:'active',past_due:'past_due',canceled:'cancelled',unpaid:'unpaid',paused:'paused'}
  const status=subscription.pause_collection?'paused':(statusMap[subscription.status]??'incomplete'),grace=status==='past_due'?new Date(Date.now()+7*24*60*60*1000).toISOString():null,interval=price?.recurring?.interval==='year'?'annual':'monthly'
  const payload={restaurant_id:restaurantId,plan_id:planId||null,stripe_customer_id:idOf(subscription.customer),stripe_subscription_id:subscription.id,stripe_price_id:price?.id??null,status,billing_interval:interval,trial_started_at:toIso(subscription.trial_start),trial_ends_at:toIso(subscription.trial_end),current_period_start:toIso(subscription.current_period_start),current_period_end:toIso(subscription.current_period_end),cancel_at_period_end:subscription.cancel_at_period_end,cancelled_at:toIso(subscription.canceled_at),ended_at:toIso(subscription.ended_at),paused_at:subscription.pause_collection?new Date(event.created*1000).toISOString():null,grace_period_ends_at:grace,updated_at:new Date().toISOString()}
  const{data,error}=await supabase.from('restaurant_subscriptions').upsert(payload,{onConflict:'restaurant_id'}).select('id,plan_id').single();if(error)throw error
  if(subscription.status==='trialing'&&subscription.trial_start){const{error:trialError}=await supabase.from('restaurant_subscription_trial_history').insert({restaurant_id:restaurantId,user_id:userId,plan_id:planId||null,started_at:toIso(subscription.trial_start),ended_at:null,source:'stripe',metadata:{stripe_subscription_id:subscription.id}});if(trialError&&trialError.code!=='23505')throw trialError}
  if(subscription.status==='active'){await supabase.from('restaurant_subscription_trial_history').update({ended_at:new Date(event.created*1000).toISOString()}).eq('restaurant_id',restaurantId).is('ended_at',null)}
  await addSubscriptionEvent(restaurantId,data.id,eventType,{stripe_status:subscription.status,cancel_at_period_end:subscription.cancel_at_period_end,paused:Boolean(subscription.pause_collection),plan_id:planId||null,billing_interval:interval})
  return{restaurantId,subscriptionId:data.id,planId:planId||null,status,interval}
 }

 try{
  switch(event.type){
   case 'checkout.session.completed':{
    const session=event.data.object as Stripe.Checkout.Session
    if(session.mode==='subscription'){const subscriptionId=idOf(session.subscription);if(!subscriptionId)throw new Error('Subscription checkout is missing a subscription');const subscription=await stripe.subscriptions.retrieve(subscriptionId);await upsertSubscription(subscription,'checkout_completed');break}
    const orderId=session.metadata?.order_id??session.client_reference_id;if(!orderId)throw new Error('Checkout Session is missing order metadata');const intentId=paymentIntentId(session.payment_intent);if(!intentId)throw new Error('Checkout Session is missing a PaymentIntent');const intent=await stripe.paymentIntents.retrieve(intentId);if(intent.status!=='requires_capture'&&intent.status!=='succeeded')break;const authorized=intent.status==='requires_capture';const{error}=await supabase.from('orders').update({payment_status:authorized?'authorized':'paid',order_status:'placed',paid_at:authorized?null:new Date(event.created*1000).toISOString(),stripe_checkout_session_id:session.id,stripe_payment_intent_id:intent.id}).eq('id',orderId).in('payment_status',['pending','requires_action']);if(error)throw error;if(!authorized){const{error:redemptionError}=await supabase.rpc('record_order_promotion_redemption',{p_order_id:orderId});if(redemptionError)throw redemptionError}break
   }
   case 'customer.subscription.created':{await upsertSubscription(event.data.object as Stripe.Subscription,event.type);break}
   case 'customer.subscription.updated':{const subscription=event.data.object as Stripe.Subscription,before=(event.data as unknown as{previous_attributes?:Record<string,unknown>}).previous_attributes??{},state=await upsertSubscription(subscription,event.type);if('cancel_at_period_end'in before){if(subscription.cancel_at_period_end)await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_cancelled',{at_period_end:true,source:'stripe'});else await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_resumed',{restart:true,source:'stripe'})}if('pause_collection'in before){await addSubscriptionEvent(state.restaurantId,state.subscriptionId,subscription.pause_collection?'subscription_paused':'subscription_resumed',{source:'stripe'})}break}
   case 'customer.subscription.deleted':{const subscription=event.data.object as Stripe.Subscription,restaurantId=subscription.metadata?.restaurant_id;if(!restaurantId)break;const{data:local,error:localError}=await supabase.from('restaurant_subscriptions').select('id,pending_plan_id,pending_billing_interval').eq('restaurant_id',restaurantId).maybeSingle();if(localError)throw localError;if(local?.pending_plan_id){const{error:updateError}=await supabase.from('restaurant_subscriptions').update({plan_id:local.pending_plan_id,billing_interval:local.pending_billing_interval??'monthly',status:'active',stripe_subscription_id:null,stripe_price_id:null,stripe_latest_invoice_id:null,trial_started_at:null,trial_ends_at:null,current_period_start:null,current_period_end:null,cancel_at_period_end:false,cancelled_at:null,paused_at:null,resume_at:null,pending_plan_id:null,pending_billing_interval:null,ended_at:new Date(event.created*1000).toISOString(),updated_at:new Date().toISOString()}).eq('id',local.id);if(updateError)throw updateError;await addSubscriptionEvent(restaurantId,local.id,'subscription_downgrade_applied',{source:'stripe',to_plan_id:local.pending_plan_id});break}const state=await upsertSubscription(subscription,event.type);await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_cancelled',{effective:true,source:'stripe'});break}
   case 'customer.subscription.paused':{const state=await upsertSubscription(event.data.object as Stripe.Subscription,event.type);await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_paused',{source:'stripe_status'});break}
   case 'customer.subscription.resumed':{const state=await upsertSubscription(event.data.object as Stripe.Subscription,event.type);await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_resumed',{source:'stripe_status'});break}
   case 'invoice.finalized':{const invoice=event.data.object as Stripe.Invoice,remoteId=idOf(invoice.subscription);if(!remoteId)break;const subscription=await stripe.subscriptions.retrieve(remoteId),state=await upsertSubscription(subscription,'invoice_finalized');await upsertInvoice(invoice,state.subscriptionId,state.restaurantId);await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'invoice_available',{invoice_id:invoice.id,invoice_number:invoice.number});break}
   case 'invoice.payment_succeeded':{const invoice=event.data.object as Stripe.Invoice,remoteId=idOf(invoice.subscription);if(!remoteId)break;const subscription=await stripe.subscriptions.retrieve(remoteId),state=await upsertSubscription(subscription,'invoice_payment_succeeded');await upsertInvoice(invoice,state.subscriptionId,state.restaurantId);await supabase.from('restaurant_subscriptions').update({stripe_latest_invoice_id:invoice.id,last_payment_succeeded_at:new Date(event.created*1000).toISOString(),last_payment_failed_at:null,grace_period_ends_at:null,status:subscription.pause_collection?'paused':subscription.status==='trialing'?'trialing':'active',updated_at:new Date().toISOString()}).eq('restaurant_id',state.restaurantId);if(invoice.billing_reason==='subscription_cycle'||invoice.billing_reason==='subscription_create')await addSubscriptionEvent(state.restaurantId,state.subscriptionId,'subscription_renewed',{invoice_id:invoice.id,billing_reason:invoice.billing_reason});break}
   case 'invoice.payment_failed':{const invoice=event.data.object as Stripe.Invoice,remoteId=idOf(invoice.subscription);if(!remoteId)break;const subscription=await stripe.subscriptions.retrieve(remoteId),restaurantId=subscription.metadata?.restaurant_id;if(!restaurantId)break;const gracePeriodEndsAt=new Date(Date.now()+7*24*60*60*1000).toISOString();const{data:row,error}=await supabase.from('restaurant_subscriptions').update({stripe_latest_invoice_id:invoice.id,status:'past_due',last_payment_failed_at:new Date(event.created*1000).toISOString(),grace_period_ends_at:gracePeriodEndsAt,updated_at:new Date().toISOString()}).eq('restaurant_id',restaurantId).select('id').single();if(error)throw error;await upsertInvoice(invoice,row.id,restaurantId);await addSubscriptionEvent(restaurantId,row.id,'invoice_payment_failed',{invoice_id:invoice.id,grace_period_ends_at:gracePeriodEndsAt});break}
   case 'payment_intent.amount_capturable_updated':{const intent=event.data.object as Stripe.PaymentIntent,orderId=intent.metadata?.order_id;if(!orderId||intent.status!=='requires_capture')break;const{error}=await supabase.from('orders').update({payment_status:'authorized',order_status:'placed',stripe_payment_intent_id:intent.id}).eq('id',orderId).in('payment_status',['pending','requires_action']);if(error)throw error;break}
   case 'payment_intent.succeeded':{const intent=event.data.object as Stripe.PaymentIntent,orderId=intent.metadata?.order_id;if(!orderId)break;const{error}=await supabase.from('orders').update({payment_status:'paid',paid_at:new Date(event.created*1000).toISOString(),stripe_payment_intent_id:intent.id}).eq('id',orderId).neq('payment_status','paid');if(error)throw error;const{error:redemptionError}=await supabase.rpc('record_order_promotion_redemption',{p_order_id:orderId});if(redemptionError)throw redemptionError;break}
   case 'payment_intent.canceled':{const intent=event.data.object as Stripe.PaymentIntent,orderId=intent.metadata?.order_id;if(!orderId)break;const{error}=await supabase.from('orders').update({payment_status:'cancelled',stripe_payment_intent_id:intent.id,manual_payout_status:'not_applicable'}).eq('id',orderId).eq('payment_status','authorized');if(error)throw error;break}
   case 'payment_intent.payment_failed':case 'checkout.session.async_payment_failed':{const object=event.data.object as Stripe.PaymentIntent|Stripe.Checkout.Session,orderId=object.metadata?.order_id;if(!orderId)break;const updates:Record<string,unknown>={payment_status:'failed'};if('payment_intent'in object)updates.stripe_payment_intent_id=paymentIntentId(object.payment_intent);else updates.stripe_payment_intent_id=object.id;const{error}=await supabase.from('orders').update(updates).eq('id',orderId).eq('order_status','pending_payment');if(error)throw error;break}
   case 'charge.refunded':{const charge=event.data.object as Stripe.Charge,intentId=paymentIntentId(charge.payment_intent);if(!intentId)break;const paymentStatus=charge.amount_refunded>=charge.amount?'refunded':'partially_refunded';const{error}=await supabase.from('orders').update({payment_status:paymentStatus,refunded_pence:charge.amount_refunded,last_refunded_at:new Date(event.created*1000).toISOString()}).eq('stripe_payment_intent_id',intentId);if(error)throw error;break}
   default:console.log('Ignoring unhandled Stripe event',{eventId:event.id,type:event.type})
  }
  const{error:completeError}=await supabase.rpc('complete_stripe_webhook_event',{p_event_id:event.id,p_succeeded:true,p_error_message:null});if(completeError)throw completeError;return json({received:true})
 }catch(error){const internalMessage=error instanceof Error?error.message:'Webhook processing failed';console.error('Failed to process Stripe webhook',{eventId:event.id,type:event.type,message:internalMessage});await supabase.rpc('complete_stripe_webhook_event',{p_event_id:event.id,p_succeeded:false,p_error_message:internalMessage});return json({error:'Webhook processing failed.'},500)}
})
